<div class="nav">
    <ul class="nav-wrap">
        <li class="<?php echo $this->controller() =='default' ? 'active' : ''?>">
            <a href="<?php echo $this->url('default/index')?>">
                <span class="icon-wrap"><i class="icon-house"></i></span>
                <span class="text-wrap">首页</span>
            </a>
        </li>
        <li class="<?php echo $this->controller() =='customer' ? 'active' : ''?>">
            <a href="<?php echo $this->url('customer/list')?>">
                <span class="icon-wrap"><i class="icon-house"></i></span>
                <span class="text-wrap">会员列表</span>
            </a>
        </li>
        <li class="<?php echo $this->controller() == 'task' ? 'active' : ''?>">
            <a href="<?php echo $this->url('task/read-list')?>">
                <span class="icon-wrap"><i class="icon-report"></i></span>
                <span class="text-wrap">任务中心</span>
            </a>
            <ul class="<?php echo $this->controller() != 'task' ? 'none' : ''?>">
                <li class="<?php echo in_array($this->action(), array('read-list', 'read-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('task/read-list');?>">
                        <span class="hidden-sm">阅读任务</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('question-list', 'question-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('task/question-list');?>">
                        <span class="hidden-sm">答题任务</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('turntable-list', 'turntable-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('task/turntable-list');?>">
                        <span class="hidden-sm">转盘设置</span>
                    </a>
                </li>
            </ul>
        </li>
        <li class="<?php echo $this->controller() == 'basic' ? 'active' : ''?>">
            <a href="<?php echo $this->url('basic/district-list')?>">
                <span class="icon-wrap"><i class="icon-report"></i></span>
                <span class="text-wrap">基本信息设置</span>
            </a>
            <ul class="<?php echo $this->controller() != 'basic' ? 'none' : ''?>">
                <li class="<?php echo in_array($this->action(), array('district-list', 'district-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('basic/district-list');?>">
                        <span class="hidden-sm">城市设置</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('config-list', 'config-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('basic/config-list');?>">
                        <span class="hidden-sm">网站配置</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('score-level')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('basic/score-level');?>">
                        <span class="hidden-sm">积分级别设置</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('home-image')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('basic/home-image');?>">
                        <span class="hidden-sm">首页图片</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('video')) ? 'active' : ''?> none">
                    <a href="<?php echo $this->url('basic/video');?>">
                        <span class="hidden-sm">视频素材</span>
                    </a>
                </li>
            </ul>
        </li>
        <li class="<?php echo $this->controller() == 'admin' ? 'active' : ''?>">
            <a href="<?php echo $this->url('admin/member-list')?>">
                <span class="icon-wrap"><i class="icon-report"></i></span>
                <span class="text-wrap">后台设置</span>
            </a>
            <ul class="<?php echo $this->controller() != 'admin' ? 'none' : ''?>">
                <li class="<?php echo in_array($this->action(), array('member-list', 'member-edit')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('admin/member-list');?>">
                        <span class="hidden-sm">人员管理</span>
                    </a>
                </li>
                <li class="<?php echo in_array($this->action(), array('password-forget')) ? 'active' : ''?>">
                    <a href="<?php echo $this->url('admin/password-forget');?>">
                        <span class="hidden-sm">修改密码</span>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</div>

<span id="short-sidebar" class="short-menu-bar clearfix">
    <i class="icon-arrow-left-strong short-right"></i>
</span>

<script type="text/javascript">
    $(function() {
        $('#short-sidebar').click(function() {
            var iObj = $(this).children('i');
            if (iObj.hasClass('icon-arrow-left-strong')) {
                iObj.attr('class', 'icon-arrow-right-strong');
                $('#main').toggleClass('to-left');
                $(this).prev('.nav').toggleClass('short-menu');
            } else {
                iObj.attr('class', 'icon-arrow-left-strong short-right');
                $('#main').removeClass('to-left');
                $(this).prev('.nav').removeClass('short-menu');
            }
        });
    });
</script>