<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        <?php if ($this->title) : ?>
            <?php echo $this->escape($this->title);?>
        <?php else : ?>
            白领
        <?php endif;?>
    </title>

    <?php echo $this->css('weui.min.css')->wrap();?>
    <?php echo $this->css('jquery-weui.min.css')->wrap();?>
    <?php echo $this->css('index.css')->wrap();?>

    <?php echo $this->js('jquery.min.js')->wrap();?>
    <?php echo $this->js('jquery-weui.min.js')->wrap();?>
    <?php echo $this->js('core.popup.js')->wrap();?>
    <?php echo $this->js('core.ajaxauto.js')->wrap();?>
    <?php echo $this->js('core.extend.js')->wrap();?>
</head>
<body class="<?php echo $this->class ?: ''?>">
    <?php echo $this->__header; ?>

    <?php echo $this->__content; ?>

    <?php echo $this->__footer; ?>
</body>
</html>