<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>
        <?php if ($this->title) : ?>
            <?php echo $this->escape($this->title);?>
        <?php else : ?>
            白领
        <?php endif;?>
    </title>

    <?php echo $this->css('weui.min.css')->wrap();?>
    <?php echo $this->css('jquery-weui.css')->wrap();?>
    <?php echo $this->css('swiper.min.css')->wrap();?>
    <?php echo $this->css('common.css')->wrap();?>
    <?php echo $this->css('index.css')->wrap();?>

    <?php echo $this->js('jquery-2.1.4.js')->wrap();?>
    <?php echo $this->js('fastclick.js')->wrap();?>
    <script type="text/javascript">
        $(function() {
          FastClick.attach(document.body);
        });
    </script>
    <?php echo $this->js('jquery-weui.js')->wrap();?>
    <?php echo $this->js('swiper.min.js')->wrap();?>
    <script type="text/javascript">
        $().ready(function () {
            var swiper8 = new Swiper('.m_nav', {
               slidesPerView: 'auto',
               paginationClickable: true,
               spaceBetween: 5,
               initialSlide :0, //这里要程序处理成当前页面的id。
             });
        });
    </script>
    <?php echo $this->js('core.popup.js')->wrap();?>
    <?php echo $this->js('core.ajaxauto.js')->wrap();?>
    <?php echo $this->js('core.extend.js')->wrap();?>

    <!-- mobileBUGFix.js 兼容修复移动设备 -->
    <?php echo $this->js('mobileBUGFix.mini.js')->wrap();?>
</head>
<body ontouchstart class="<?php echo $this->class ?: ''?>" style="<?php echo $this->style ?: ''?>">
    <?php echo $this->__header; ?>

    <?php echo $this->__content; ?>

    <?php echo $this->__footer; ?>
</body>
</html>