<div class="feedback">
  <div class="feedback_place">请填写您宝贵的意见，非常感谢！</div>
  <textarea name="" rows="" cols=""></textarea>   
  <button class="feedback_tj">提交</button>
</div>

<script type="text/javascript">
  $(".feedback textarea").focus(function(){
    $(".feedback_place").hide()
  })
  $(".feedback textarea").blur(function(){
    if($(this).val()==""){
      $(".feedback_place").show()
    } 
  })
</script>