<div class="help">
  <div class="weui-cells">              
    <a class="weui-cell weui-cell_access" href="<?php echo $this->url('help/feedback')?>">
      <div class="weui-cell__bd">
           <p>意见反馈</p>
      </div>
      <div class="weui-cell__ft">
      </div>
    </a>
   <a class="weui-cell weui-cell_access" href="<?php echo $this->url('help/protocol', array('status' => 'fwxy'))?>">
      <div class="weui-cell__bd">
           <p>服务协议</p>
      </div>
      <div class="weui-cell__ft">
      </div>
    </a>
    <a class="weui-cell weui-cell_access" href="tel:400-123-9834">
      <div class="weui-cell__hd"><p>联系客服</p></div>
      <div class="weui-cell__bd">
           <h5>400-123-9834</h5>
      </div>
      <div class="weui-cell__ft">
      </div>
    </a>
  </div>
</div>

<?php echo $this->js('ignore-history.js')->wrap();?>