<?php echo $this->css('umeditor/default/css/umeditor.css')->wrap();?>

<?php echo $this->js('umeditor/third-party/jquery.min.js')->wrap();?>
<?php echo $this->js('umeditor/third-party/template.min.js')->wrap();?>
<?php echo $this->js('umeditor/umeditor.config.js')->wrap();?>
<?php echo $this->js('umeditor/umeditor.js')->wrap();?>
<?php echo $this->js('umeditor/lang/zh-cn/zh-cn.js')->wrap();?>

<script type="text/plain" id="myEditor" style="width:1000px;height:240px;">
    <p>这里我可以写一些输入提示</p>
</script>

<script type="text/javascript">
	//实例化编辑器
	var um = UM.getEditor('myEditor');
</script>