<div class="prod_dt bgwhite mb15">
    <div class="swiper-container m_banner img pr">
        <div class="swiper-wrapper">
            <?php foreach($info['images']['banner'] as $row) : ?>
                <div class="swiper-slide">
                    <img src="<?php echo $this->uploadUrl($row['image_path'], 'product')?>">
                </div>
            <?php endforeach;?>
        </div>
        <div class="pa" style="z-index: 10;">
            <p class="lr1">
                <i class="iconfont">&#xe620;</i>
                <?php if (strtotime($info['product_end']) < time()) : ?>
                    <span>领取时间已过</span>
                <?php else : ?>
                    <span>
                        距离兑换结束还有
                        <label id="time" data-time="<?php echo strtotime($info['product_end']) - time()?>">
                            <?php echo $this->funcs->showTime(strtotime($info['product_end']) - time())?>
                        </label>
                    </span>
                <?php endif;?>

            </p>
        </div>
        <?php if ($info['product_quantity'] < 1) : ?>
            <span class="pa tip">
              商品已领完了，下次早些来
            </span>
        <?php endif;?>
    </div>
    <div class="t_info wrap">
        <h4><?php echo $info['product_name']?></h4>
        <div class="jg clearfix">
            <span class="fl">
                免费领取<b>[<?php echo sprintf("%.2f", $info['product_virtual_price'])?>]</b>
            </span>
            <span class="fr">
                每人限领取一份<?php echo $info['product_shaping_status'] ? '&nbsp;|&nbsp;支持配送' : ''?>
            </span>
        </div>
        <p>推荐理由：<?php echo $info['product_desc']?></p>
    </div>
</div>
<!-- 组团说明 -->
<?php if ($info['product_type'] == 2) : ?>
  <div class="tuan bgwhite">
      <a href="#" class="eval_title wrap clearfix">
      <b class="fl">组团说明</b>
      </a>
      <div class="wrap info">
          <p><?php echo $info['product_group_num']?>人以上才可参加组团东西好价钱实惠，服务态度超级棒欢迎下次继续光临本店.</p>
      </div>
  </div>
<?php endif;?>
<!-- 评价 -->
<?php if ($reviewList) : ?>
    <div class="eval bgwhite mb15">
        <a href="<?php echo $this->url('product/review', array('id' => $info['product_id']))?>" class="eval_title wrap clearfix">
            <b class="fl">评论</b>
            <span class="fr">更多<i class="iconfont">&#xe628;</i></span>
        </a>
    <!-- 评价列表 -->
        <?php foreach($reviewList as $row) : ?>
              <div class="eval_box">
                <a href="<?php echo $this->url('product/review-detail', array('id' => $row['review_id']))?>" class="pjxq">
                  <div class="peo_photo clearfix pr wrap">
                    <div class="img fl">
                      <img src="<?php echo $this->uploadUrl($row['customer_headimg'], 'user')?>">
                    </div>
                    <h3><?php echo $row['customer_name']?></h3>
                    <p><span style="width:<?php echo sprintf("%d%%", $row['review_score'])?>;"></span></p>
                    <div class="pa"><?php echo date("Y-m-d", strtotime($row['review_time']))?></div>
                  </div>
                  <div class="wrap">
                    <p>评论内容：<?php echo $row['review_content']?></p>
                    <?php if ($row['images']) : ?>
                        <div class="pj_img clearfix">
                            <?php foreach($row['images'] as $image) : ?>
                                <img src="<?php echo $this->uploadUrl($image['image_path'], 'review')?>" class="fl">
                            <?php endforeach;?>
                        </div>
                    <?php endif;?>
                  </div>
                </a>
                <div class="jubao wrap clearfix">
                    <a class="jb fl show-confirm" href="javascript:;" data-id="<?php echo $row['review_id']?>" data-status="<?php echo $row['review_attr']?>">举报</a>
                    <a href="javascript:void(0);" class="fr tac <?php echo $row['log_id'] ? 'on' : ''?> js-up" data-id="<?php echo $row['review_id']?>">
                        <i class="iconfont">&#xe609;</i>
                        <span><?php echo $row['review_vote_up']?></span>
                    </a>
                </div>
              </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<!-- 图文详情 -->
<div class="dt_pic bgwhite">
  <a href="javascript:;" class="eval_title wrap clearfix">
    <b class="fl">图文详情</b>
  </a>
    <?php foreach($info['images']['detail'] as $row) : ?>
        <img src="<?php echo $this->uploadUrl($row['image_path'], 'product')?>" alt="">
    <?php endforeach;?>
</div>

<!-- footer -->
<?php if (strtotime($info['product_end']) < time()) : ?>
    <div class="pf pro_foot clearfix">
      <a href="javascript:void(0);" class="sc fl js-collection <?php echo $info['collection_id'] ? 'on' : ''?>" style="color: <?php echo $info['collection_id'] ? '#ff7c00;' : '#999;'?>" data-id="<?php echo $info['product_id']?>"><i class="iconfont">&#xe614;</i><span>收藏</span></a>
      <a href="#" class="fr lq" style="color: #fff; background-color: #f3f3f3;">已过领取时间</a>
    </div>
<?php elseif ($info['product_quantity'] < 1) : ?>
    <div class="pf pro_foot clearfix">
      <a href="javascript:void(0);" class="sc fl js-collection <?php echo $info['collection_id'] ? 'on' : ''?>" style="color: <?php echo $info['collection_id'] ? '#ff7c00;' : '#999;'?>" data-id="<?php echo $info['product_id']?>"><i class="iconfont">&#xe614;</i><span>收藏</span></a>
        <a href="javascript:void(0);" class="fr lq" style="color: #fff; background-color: #999;">商品已领完</a>
    </div>
<?php elseif ($info['product_type'] == 2) : ?>
    <div class="pf pro_foot clearfix">
      <a href="javascript:void(0);" class="sc fl js-collection <?php echo $info['collection_id'] ? 'on' : ''?>" style="color: <?php echo $info['collection_id'] ? '#ff7c00;' : '#999;'?>" data-id="<?php echo $info['product_id']?>"><i class="iconfont">&#xe614;</i><span>收藏</span></a>
        <?php if ($info['order_num']) : ?>
            <a href="javascript:void(0);" class="fr lq" style="color: #fff; background-color: #999;">每人限领取一份</a>
        <?php else : ?>
            <a href="<?php echo $this->url('cart/index', array('id' => $info['product_id']))?>" class="fr lq">立即组团领</a>
        <?php endif;?>
    </div>
<?php else : ?>
    <div class="pf pro_foot clearfix">
      <a href="javascript:void(0);" class="sc fl js-collection <?php echo $info['collection_id'] ? 'on' : ''?>" style="color: <?php echo $info['collection_id'] ? '#ff7c00;' : '#999;'?>" data-id="<?php echo $info['product_id']?>"><i class="iconfont">&#xe614;</i><span>收藏</span></a>
      <?php if ($info['order_num']) : ?>
          <a href="javascript:void(0);" class="fr lq" style="color: #fff; background-color: #999;">每人限领取一份</a>
      <?php else : ?>
          <a href="<?php echo $this->url('cart/index', array('id' => $info['product_id']))?>" class="fr lq">立即白领</a>
      <?php endif;?>
    </div>
<?php endif;?>

<script type="text/javascript">
    $(".m_banner").swiper({
        loop: true,
        autoplay: 3000
    });

    setInterval(function () {
        var $$ = $('#time');
        var time = parseInt($$.data('time'));
        if (time < 0) {
            time = 0;

            window.location.reload();
            return false;
        }

        var init = {
            'year': [31536000, '年'],
            'month': [2592000, '月'],
            'day': [86400, '天'],
            'hour': [3600, '小时'],
            'minute': [60, '分'],
            'second': [1, '秒'],
        };
        var str = '';
        for(key in init) {
            num = Math.floor(time / init[key][0]);
            if (num) {
                str += num + init[key][1];
                time -= num * init[key][0];
            }
        }

        if (!str) {
            str = '0秒';
        }

        $$.data('time', parseInt($$.data('time')) - 1);
        $$.html(str);
    }, 1000);

    //举报弹窗
    $(document).on("click", ".show-confirm", function() {
        var $$ = $(this);
        var status = $$.data('status');
        var id = $$.data('id');

        if (status == 'pending') {
            $.toast("该条评论已被别人举报过！");
        } else {
            $.confirm("确定要举报此条评论吗?", "", function() {
                $$.removeAttr('href');
                $$.ajaxAuto({
                    url: '<?php echo $this->url('product/review-edit')?>',
                    data: {id: id},
                    success: function (re) {
                        if (re.status == 'ok') {
                            $$.data('status', 'pending');
                        }
                    }
                });
            }, function() {
                //取消操作
            });
        }
    });

    init();

    //收藏
    $('.js-collection').click(function() {
        var $$ = $(this);
        var id = $$.data('id');
        var type = $$.hasClass('on') ? 'del' : 'add';
        var num = parseInt($$.find('span').text());

        $$.removeAttr('href');

        $$.ajaxAuto({
            url: '<?php echo $this->url('product/collection')?>',
            data: {id: id, type: type},
            success: function (re) {
                if (re.status == 'ok') {
                    if (type == 'del') {
                        $$.removeClass('on');
                        $$.css({color: '#999'});
                    } else {
                        $$.addClass('on');
                        $$.css({color: '#ff7c00'});
                    }
                }
            }
        });
        return false;
    });

    function init() {
        //赞
        $('.js-up').click(function() {
            var $$ = $(this);
            if ($$.hasClass('on')) {
                return false;
            }

            var id = $$.data('id');
            var num = parseInt($$.find('span').text());

            $$.removeAttr('href');

            $$.ajaxAuto({
                url: '<?php echo $this->url('product/review-up')?>',
                data: {id: id},
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.addClass('on');
                        $$.find('span').html(num + 1);
                    }
                }
            });
            return false;
        });
    }
</script>