<?= $this->render('includes/header')?>

<?= $this->render('includes/nav', array('attrList' => $attrList))?>

<!-- 分类列表 -->
<?php if ($productList) : ?>
<div id="m_pro" class='demos-content-padded mt98'>
    <?php foreach($productList as $row) : ?>
        <div class="prod_list">
            <img src="<?php echo $this->uploadUrl($row['images']['home'][0]['image_path'], 'product')?>">
            <div class="info wrap pr">
                <h4 class="lr1"><?php echo $row['product_name']?></h4>
                <span class="jg pa">[<?php echo sprintf("%.2f", $row['product_virtual_price'])?>]</span>
                <span class="pa orange"><?php echo $this->funcs->showValue($row['product_price'])?>积分</span>
            </div>
            <div class="info info_click wrap clearfix">
                <a href="javascript:void(0);" class="fl tac js-collection <?php echo $row['collection_id'] ? 'on' : ''?>" data-id="<?php echo $row['product_id']?>">
                    <i class="iconfont">&#xe60b;</i>
                    <span><?php echo $row['collection_num']?></span>
                </a>
                <a href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>" class="fr tac">
                    <i class="iconfont ling">&#xe605;</i><span><?php echo $row['product_type'] == 2 ? '组团领' : '立即白领'?></span>
                </a>
            </div>
        </div>
    <?php endforeach;?>
</div>
<?php else : ?>
    <div class="noproduct">
      <p class="tac">
        你所在的城市暂无商品，先去参互互动赚积分吧
      </p>
    </div>
<?php endif;?>

<div class="mask"></div>

<div class="weui-loadmore none">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
</div>

<!-- 搜索按钮 -->
<a class="search_btn pf" href="<?php echo $this->url('default/search')?>"><i class="iconfont">&#xe60a;</i></a>

<script type="text/javascript">
    var wh=$(window).height();
    var ww=$(window).width();
    $(".noproduct").height(wh-50);
    $(".noproduct").width(ww);

    $(".prod_list").last().css("margin-bottom",0);

    init();

    var pageSize = 1;
    var loading = false;  //状态标记
    $(document.body).infinite().on("infinite", function() {
        if (loading) {
            return false;
        } else {
            $('.weui-loadmore').fadeIn();
            loading = true;
        }
        
        $(this).ajaxAuto({
            data: {type: 'page', pageSize: pageSize},
            success: function (re) {
                var ali="";
                if (re.status == 'ok') {
                    pageSize++;

                    $(re.data).each(function (key, row) {
                        ali +='<div class="prod_list"><img src="' + row.image_path + '"><div class="info wrap pr"><h4 class="lr1">' + row.product_name + '</h4><span class="jg pa">[' + row.product_virtual_price + ']</span><span class="pa orange">' + row.product_price + '积分</span></div><div class="info info_click wrap clearfix"><a href="javascript:void(0);" class="fl tac js-collection ' + row.collection_status + '" data-id="' + row.product_id + '"><i class="iconfont">&#xe60b;</i><span>' + row.collection_num + '</span></a><a href="' + row.href + '" class="fr tac"><i class="iconfont ling">&#xe605;</i><span>' + row.button + '</span></a></div></div>';
                    });
                }

                $("#m_pro").append(ali);
                init();
                
                $('.weui-loadmore').fadeOut();
                loading = false;
            }
        });
    });

    function init() {
        //收藏
        $('.js-collection').click(function() {
            var $$ = $(this);
            var id = $$.data('id');
            var type = $$.hasClass('on') ? 'del' : 'add';
            var num = parseInt($$.find('span').text());

            $$.removeAttr('href');

            $$.ajaxAuto({
                url: '<?php echo $this->url('product/collection')?>',
                data: {id: id, type: type},
                success: function (re) {
                    if (re.status == 'ok') {
                        if (type == 'del') {
                            $$.removeClass('on');
                            $$.find('span').html(num - 1);
                            $$.find('i').html("&#xe60b;");
                        } else {
                            $$.addClass('on');
                            $$.find('span').html(num + 1);
                            $$.find('i').html("&#xe614;");
                        }
                    }
                }
            });
            return false;
        });
    }
</script>