<?= $this->render('includes/nav', array('attrList' => $attrList))?>

    <!-- 分类列表 -->
    <div id="m_pro" class='demos-content-padded mt98'>

      <div class="prod_list">
        <img src="images/prod_01.jpg">
        <div class="info wrap pr">
          <h4 class="lr1">比利时啤酒艺术的极致呈现</h4>
          <span class="jg pa">[98.00]</span>
          <span class="pa orange">100积分</span>
        </div>
        <div class="info info_click wrap clearfix">
          <a href="javascript:void(0);" class="fl tac"><i class="iconfont">&#xe60b;</i><span>1000</span></a>
          <a href="立即白领详情页.html" class="fr tac"><i class="iconfont ling">&#xe605;</i><span>立即白领</span></a>
        </div>
      </div>

      <div class="prod_list">
        <img src="images/prod_02.jpg">
        <div class="info wrap pr">
          <h4 class="lr1">比利时啤酒艺术的极致呈现</h4>
          <span class="jg pa">[98.00]</span>
          <span class="pa orange">100积分</span>
        </div>
        <div class="info info_click wrap clearfix">
          <a href="javascript:void(0);" class="fl tac"><i class="iconfont">&#xe60b;</i><span>1000</span></a>
          <a href="立即白领详情页.html" class="fr tac"><i class="iconfont ling">&#xe605;</i><span>立即白领</span></a>
        </div>
      </div>
      
    </div>
    <div class="weui-loadmore">
      <i class="weui-loading"></i>
      <span class="weui-loadmore__tips">正在加载</span>
    </div>
    
    <!-- 搜索按钮 -->
    <a class="search_btn pf" href="搜索.html"><i class="iconfont">&#xe60a;</i></a>

    <script src="../jquery-2.1.4.js"></script>
    <script src="../fastclick.js"></script>
    <script>
      $(function() {
        FastClick.attach(document.body);
      });
    </script>
    <script src="../jquery-weui.js"></script>
    <script src="../swiper.min.js"></script>
    <script src="js/index.js"></script>
    <script>
      var swiper8 = new Swiper('.m_nav', {
          slidesPerView: 'auto',
          paginationClickable: true,
          spaceBetween: 5,
          initialSlide :0, //这里要程序处理成当前页面的id。
        });
      // 上拉加载
      var loading = false;
      $(document.body).infinite().on("infinite", function() {
        if(loading) return;
        loading = true;
        setTimeout(function() {
          $("#m_pro").append("<div class='prod_list'><img src='images/prod_02.jpg'><div class='info wrap pr'><h4 class='lr1'>比利时啤酒艺术的极致呈现</h4><span class='jg pa'>[98.00]</span><span class='pa orange'>100积分</span></div><div class='info info_click wrap clearfix'><a href='javascript:void(0);' class='fl tac'><i class='iconfont'>&#xe60b;</i><span>1000</span></a><a href='#' class='fr tac'><i class='iconfont ling'>&#xe605;</i><span>立即白领</span></a></div></div>");
          loading = false;
          //加载后点击收藏
          $(".prod_list").each(function() {
            $(this).find('.fl').on('click', function(event) {
            var num=$(this).find('span').html();
              if($(this).hasClass('on')){
                $(this).removeClass('on');
                num--;
                $(this).find('span').html(num);

              }else{
                $(this).addClass('on')
                num++;
                $(this).find('span').html(num)
              }
            });
          });
          }, 2000);

      });
    </script>