<div class="eval bgwhite" id="m_pro">
<!-- 评价列表 -->
    <?php if ($reviewList) : ?>
        <?php foreach($reviewList as $row) : ?>
            <div class="eval_box">
                <a href="<?php echo $this->url('product/review-detail', array('id' => $row['review_id']))?>" class="pjxq">
                    <div class="peo_photo clearfix pr wrap">
                        <div class="img fl">
                            <img src="<?php echo $this->uploadUrl($row['customer_headimg'], 'user')?>">
                        </div>
                        <h3><?php echo $row['customer_name']?></h3>
                        <p><span style="width:<?php echo sprintf("%d%%", $row['review_score'])?>;"></span></p>
                        <div class="pa"><?php echo date("Y-m-d", strtotime($row['review_time']))?></div>
                    </div>
                    <div class="wrap">
                        <p>评论内容：<?php echo $row['review_content']?></p>
                        <?php if ($row['images']) : ?>
                            <div class="pj_img clearfix">
                                <?php foreach($row['images'] as $image) : ?>
                                    <img src="<?php echo $this->uploadUrl($image['image_path'], 'review')?>" class="fl">
                                <?php endforeach;?>
                            </div>
                        <?php endif;?>
                    </div>
                </a>
                <div class="jubao wrap clearfix">
                    <a class="jb fl show-confirm" href="javascript:;" data-id="<?php echo $row['review_id']?>" data-status="<?php echo $row['review_attr']?>">举报</a>
                    <a href="javascript:void(0);" class="fr tac <?php echo $row['log_id'] ? 'on' : ''?> js-up" data-id="<?php echo $row['review_id']?>">
                        <i class="iconfont">&#xe609;</i>
                        <span><?php echo $row['review_vote_up']?></span>
                    </a>
                </div>
            </div>
        <?php endforeach;?>
    <?php endif;?>
</div>

<div class="mask"></div>

<div class="weui-loadmore none">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
</div>

<script type="text/javascript">
    //举报弹窗
    $(document).on("click", ".show-confirm", function() {
        var $$ = $(this);
        var status = $$.data('status');
        var id = $$.data('id');

        if (status == 'pending') {
            $.toast("该条评论已被别人举报过！");
        } else {
            $.confirm("确定要举报此条评论吗?", "", function() {
                $$.removeAttr('href');
                $$.ajaxAuto({
                    url: '<?php echo $this->url('product/review-edit')?>',
                    data: {id: id},
                    success: function (re) {
                        if (re.status == 'ok') {
                            $$.data('status', 'pending');
                        }
                    }
                });
            }, function() {
                //取消操作
            });
        }
    });

    init();

    var pageSize = 1;
    var loading = false;  //状态标记
    $(document.body).infinite().on("infinite", function() {
        if (loading) {
            return false;
        } else {
            $('.weui-loadmore').fadeIn();
            loading = true;
        }
        
        $(this).ajaxAuto({
            data: {type: 'page', pageSize: pageSize},
            success: function (re) {
                var ali="";
                if (re.status == 'ok') {
                    pageSize++;

                    $(re.data).each(function (key, row) {
                        ali +='<div class="eval_box"><a href="' + row.href + '" class="pjxq"><div class="peo_photo clearfix pr wrap"><div class="img fl"><img src="' + row.customer_headimg + '"></div><h3>' + row.customer_name + '</h3><p><span style="width:' + row.review_score + ';"></span></p><div class="pa">' + row.review_time + '</div></div><div class="wrap"><p>评论内容：' + row.review_content + '</p>';
                        if (row.images.length > 1) {
                            ali += '<div class="pj_img clearfix">';
                            $(row.images).each(function (k, r) {
                                ali += '<img src="' + r.image_path + '" class="fl">';
                            });
                            ali += '</div>';
                        }

                        ali +='</div></a><div class="jubao wrap clearfix"><a class="jb fl show-confirm" href="javascript:;" data-id="' + row.review_id + '" data-status="' + row.review_attr + '">举报</a><a href="javascript:void(0);" class="fr tac ' + row.log_id + ' js-up" data-id="' + row.review_id + '"><i class="iconfont">&#xe609;</i><span>' + row.review_vote_up + '</span></a></div></div>';
                    });
                }

                $("#m_pro").append(ali);
                init();
                
                $('.weui-loadmore').fadeOut();
                loading = false;
            }
        });
    });

    function init() {
        //赞
        $('.js-up').click(function() {
            var $$ = $(this);
            if ($$.hasClass('on')) {
                return false;
            }

            var id = $$.data('id');
            var num = parseInt($$.find('span').text());

            $$.removeAttr('href');

            $$.ajaxAuto({
                url: '<?php echo $this->url('product/review-up')?>',
                data: {id: id},
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.addClass('on');
                        $$.find('span').html(num + 1);
                    }
                }
            });
            return false;
        });
    }
</script>