<div class="eval bgwhite">
<!-- 评价列表 -->
    <div class="eval_box">
        <div class="peo_photo clearfix pr wrap">
            <div class="img fl">
                <img src="<?php echo $this->uploadUrl($info['customer_headimg'], 'user')?>">
            </div>
            <h3><?php echo $info['customer_name']?></h3>
            <p><span style="width:<?php echo sprintf("%d%%", $info['review_score'])?>"></span></p>
            <div class="pa"><?php echo date("Y-m-d", strtotime($info['review_time']))?></div>
        </div>
        <div class="wrap">
        <p>评论内容：<?php echo $info['review_content']?></p>
        <?php if ($info['images']) : ?>
            <div class="pj_img clearfix">
                <?php foreach($info['images'] as $image) : ?>
                    <img src="<?php echo $this->uploadUrl($image['image_path'], 'review')?>" class="fl">
                <?php endforeach;?>
            </div>
        <?php endif;?>
        </div>
        <div class="jubao wrap clearfix">
            <a class="jb fl show-confirm" href="javascript:;" data-id="<?php echo $info['review_id']?>" data-status="<?php echo $info['review_attr']?>">举报</a>
            <a href="javascript:void(0);" class="fr tac <?php echo $info['log_id'] ? 'on' : ''?> js-up" data-id="<?php echo $info['review_id']?>">
                <i class="iconfont">&#xe609;</i>
                <span><?php echo $info['review_vote_up']?></span>
            </a>
        </div>
    </div>
</div>

<script type="text/javascript">
    //举报弹窗
    $(document).on("click", ".show-confirm", function() {
        var $$ = $(this);
        var status = $$.data('status');
        var id = $$.data('id');

        if (status == 'pending') {
            $.toast("该条评论已被别人举报过！");
        } else {
            $.confirm("确定要举报此条评论吗?", "", function() {
                $$.removeAttr('href');
                $$.ajaxAuto({
                    url: '<?php echo $this->url('product/review-edit')?>',
                    data: {id: id},
                    success: function (re) {
                        if (re.status == 'ok') {
                            $$.data('status', 'pending');
                        }
                    }
                });
            }, function() {
                //取消操作
            });
        }
    });

    init();

    // 点击图片放大
    $(".pj_img img").click(function(event) {
        var phot=[]; 
         var inx=$(this).index();
         $(this).parent().find("img").each(function(index, el) {
            var pho_img=$(this).attr("src");
                phot.push(pho_img)
          });           
        $.tpyl(phot,inx)       
    });
    $.tpyl = function(phot,inx) {
      var pb1 = $.photoBrowser({
            items: phot,

            onSlideChange: function(index) {
              console.log(this, index);
            },

            onOpen: function() {
              console.log("onOpen", this);
            },
            onClose: function() {
              console.log("onClose", this);
            },
            initIndex:inx
          });      
        pb1.open();
    }

    function init() {
        //赞
        $('.js-up').click(function() {
            var $$ = $(this);
            if ($$.hasClass('on')) {
                return false;
            }

            var id = $$.data('id');
            var num = parseInt($$.find('span').text());

            $$.removeAttr('href');

            $$.ajaxAuto({
                url: '<?php echo $this->url('product/review-up')?>',
                data: {id: id},
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.addClass('on');
                        $$.find('span').html(num + 1);
                    }
                }
            });
            return false;
        });
    }
</script>