<?= $this->render('includes/header')?>

<?= $this->render('includes/nav', array('attrList' => $attrList))?>

  <!-- banner -->
<?php if ($imageList) : ?>
<div class="swiper-container m_banner mt98">
	<div class="swiper-wrapper">
		<?php foreach($imageList as $row) : ?>
			<div class="swiper-slide">
				<?php if ($row['image_href']) : ?>
					<a href="<?php echo $row['image_href']?>">
						<img src="<?php echo $this->uploadUrl($row['image_path'], 'sys')?>" />
					</a>
				<?php else : ?>
					<img src="<?php echo $this->uploadUrl($row['image_path'], 'sys')?>" />
				<?php endif;?>
			</div>
		<?php endforeach;?>
	</div>
	<div class="swiper-pagination"></div>
</div>
<?php endif;?>
<!-- main_list -->
<?php if ($recommendList) : ?>
	<?php foreach($recommendList as $key => $row) : ?>
		<div class="m_list">
			<img class="m_img" src="<?php echo $this->uploadUrl($row['recommend_path'], 'sys')?>">
			<div class="clearfix m_info wrap">
				<div class="photo fl">
					<img src="<?php echo $this->uploadUrl($row['recommend_logo'], 'sys')?>">
				</div>
				<h3 class="lr1"><?php echo $row['recommend_title']?></h3>
				<?php if ($row['product_id']) : ?>
					<a class="m_btn" href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>">
						<?php echo !$key ? '立即领取' : '组团领'?>
					</a>
				<?php endif;?>
			</div>
		</div>
	<?php endforeach;?>
<?php endif;?>

<!-- 搜索按钮 -->
<a class="search_btn pf" href="<?php echo $this->url('default/search')?>"><i class="iconfont">&#xe60a;</i></a>

<script type="text/javascript">
	$(function(){
		$(".m_nav").find('.swiper-slide').on('tap', function() {
			$(this).siblings().removeClass('on');
			$(this).addClass('on');
		});
		$(".m_banner").swiper({
		    loop: true,
		    autoplay: 3000
		});
	})
</script>
