<!-- 搜索框 -->
  <div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form">
      <div class="weui-search-bar__box">
        <i class="weui-icon-search"></i>
        <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入关键字查找商品" required="">
        <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
      </div>
      <label class="weui-search-bar__label" id="searchText">
        <i class="weui-icon-search"></i>
        <span>输入关键字查找商品</span>
      </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
  </div>
  <!-- 搜索历史 -->
  <div class="search_history wrap pr">
    <a href="javascript:;" class="pa delt"><i class="iconfont">&#xe602;</i><span>清空</span></a>
    <h4>搜索历史</h4>
    <p>
      <a href="搜索结果.html">年货大集</a><a href="搜索结果.html">冰糖橙</a><a href="搜索结果.html">鸡蛋</a><a href="搜索结果.html">海鲜</a>
    </p>
  </div>
  
  <!-- 热门推荐 -->
  <div class="search_hot">
    <h4>热门推荐</h4>
    <div class="search_list clearfix pr">
      <div class="img fl">
        <img src="images/pj_02.jpg" >
      </div>
      <h4>江中猴菇早餐米稀营养糊健康有营养江中猴米稀</h4>
      <p>100积分</p>
      <a class="pa" href="#">立即白领</a>
    </div>
  </div>

<script type="text/javascript">
    // 删除
    $(".search_history").children('a').on('click',function(event) {
      $(this).parent().remove()
    });
</script>