<!-- 搜索框 -->
<div class="weui-search-bar" id="searchBar">
    <form class="weui-search-bar__form">
    <div class="weui-search-bar__box">
    <i class="weui-icon-search"></i>
    <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入关键字查找商品" required="">
    <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
    </div>
    <label class="weui-search-bar__label" id="searchText">
    <i class="weui-icon-search"></i>
    <span>输入关键字查找商品</span>
    </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>
<!-- 搜索历史 -->
<?php if ($searchList) : ?>
    <div class="search_history wrap pr">
        <a href="<?php echo $this->url('default/search-clear')?>" class="pa delt"><i class="iconfont">&#xe602;</i><span>清空</span></a>
        <h4>搜索历史</h4>
        <p>
            <?php foreach($searchList as $row) : ?>
                <a href="搜索结果.html"><?php echo $row['log_name']?></a>
            <?php endforeach?>
        </p>
    </div>
<?php endif;?>
  
<!-- 热门推荐 -->
<div class="search_hot">
    <h4>热门推荐</h4>
    <?php if ($productMain) : ?>
        <div class="search_list clearfix pr">
            <div class="img fl">
                <img src="<?php echo $this->uploadUrl($productMain['images']['banner'][0]['image_path'], 'product')?>" >
            </div>
            <h4><?php echo $productMain['product_name']?></h4>
            <p><?php echo $this->funcs->showValue($productMain['product_price'])?>积分</p>
            <a class="pa" href="<?php echo $this->url('product/detail', array('id' => $productMain['product_id']))?>">
                <?php echo $productMain['product_type'] == 1 ? '立即白领' : '组团领'?>
            </a>
        </div>
    <?php endif;?>
    <?php if ($productMinor) : ?>
        <?php foreach($productMinor as $row) : ?>
            <a href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>" style="color: #000; margin: 0.5em;">
                <p><?php echo $row['product_name']?></p>
            </a>
        <?php endforeach;?>
    <?php endif;?>
</div>