<!-- 搜索框 -->
<div class="weui-search-bar <?php echo $this->param('product_name') ? 'weui-search-bar_focusing' : ''?>" id="searchBar">
    <form class="weui-search-bar__form" id="js-submit-ignore">
        <div class="weui-search-bar__box">
            <i class="weui-icon-search"></i>
            <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入关键字查找商品" required="" name="product_name" value="<?php echo $this->param('product_name')?>">
            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
        </div>
        <label class="weui-search-bar__label" id="searchText">
        <i class="weui-icon-search"></i>
        <span>输入关键字查找商品</span>
        </label>
    </form>
    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>

<?php if ($productList) : ?>
    <?php foreach($productList as $row) : ?>
        <div class="js-row" data-href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>">
            <div class="search_hot search_hh">
                <div class="search_list clearfix pr">
                    <div class="img fl">
                        <img src="<?php echo $this->uploadUrl($row['images']['banner'][0]['image_path'], 'product')?>" >
                    </div>
                    <h4><?php echo $row['product_name']?></h4>
                    <p><?php echo $this->funcs->showValue($row['product_price'])?>积分</p>
                    <a class="pa igonre-no" href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>">
                        <?php echo $row['product_type'] == 1 ? '立即白领' : '组团领'?>
                    </a>
                </div>
            </div>
        </div>
    <?php endforeach?>
<?php elseif ($this->param('product_name')) : ?>
    <div class="noproduct">
      <p class="tac">
        暂时没有你要搜索的商品
      </p>
    </div>
<?php endif;?>

<!-- 搜索历史 -->
<?php if ($searchList) : ?>
    <div class="search_history wrap pr" style="padding: 10px;">
        <a href="javascript:;" data-href="<?php echo $this->url('default/search-clear')?>" class="pa delt"><i class="iconfont">&#xe602;</i><span>清空</span></a>
        <h4>搜索历史</h4>
        <p>
            <?php foreach($searchList as $row) : ?>
                <a href="<?php echo $this->url('default/search', array('product_name' => $row['log_name']))?>">
                    <?php echo $row['log_name']?>
                </a>
            <?php endforeach?>
        </p>
    </div>
<?php endif;?>
  
<!-- 热门推荐 -->
<?php if ($productMain || $productMinor) : ?>
    <div class="search_hot">
        <h4>热门推荐</h4>
        <?php if ($productMain) : ?>
            <?php foreach($productMain as $row) : ?>
                <div class="search_list clearfix pr">
                    <?php if (isset($row['images']['banner'][0]['image_path'])) : ?>
                        <div class="img fl">
                            <img src="<?php echo $this->uploadUrl($row['images']['banner'][0]['image_path'], 'product')?>" >
                        </div>
                    <?php endif;?>
                    <h4><?php echo $row['product_name']?></h4>
                    <p><?php echo $this->funcs->showValue($row['product_price'])?>积分</p>
                    <a class="pa igonre-no" href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>">
                        <?php echo $row['product_type'] == 1 ? '立即白领' : '组团领'?>
                    </a>
                </div>
            <?php endforeach;?>
        <?php endif;?>
        <?php if ($productMinor) : ?>
            <?php foreach($productMinor as $row) : ?>
                <a href="<?php echo $this->url('product/detail', array('id' => $row['product_id']))?>" style="color: #000; margin: 0.5em;" class="igonre-no">
                    <p><?php echo $row['product_name']?></p>
                </a>
            <?php endforeach;?>
        <?php endif;?>
    </div>
<?php endif;?>

<?php echo $this->js('ignore-history.js')->wrap();?>
<script type="text/javascript">
    var wh = $(window).height(),ww = $(window).width();
    $(".noproduct").height(wh - 50).width(ww);

    $('#searchClear').click(function() {
        $('#searchInput').val('').focus();
    });
    $('#searchCancel').click(function() {
        $('#searchBar').removeClass('weui-search-bar_focusing');
        $('#searchInput').val('').blur();
    });
    $('#searchInput').blur(function() {
        $('form').trigger('submit');
    });

    $('.js-row').click(function() {
        window.location.href = $(this).data('href');
    });

    $('.delt').click(function() {
        var $$ = $(this);

        $.confirm("确定情空当前搜索记录？", "", function() {
            window.location.href = $$.data('href');
        }, function() {
            return false;
        });
    });

</script>