  	<div class="mydata newaddress">
  		<div class="weui-cells">	  		
			  <div class="weui-cell" >
			  	 <div class="weui-cell__hd"><label class="weui-label">收件人姓名</label></div>
			  		<div class="weui-cell__bd">
				   		 <input type="text" class="importinp" name="" value="" placeholder="请输入姓名"/>
				   </div>
			  </div>
			  <div class="weui-cell" >
			  	 <div class="weui-cell__hd"><label class="weui-label">手机号码</label></div>
			  		<div class="weui-cell__bd">
				   		 <input type="text" class="importinp" name="" value="" placeholder="请输入手机号码"/>
				   </div>
			  </div>
			  <div class="weui-cell weui-cell_access" >
			  	 <div class="weui-cell__hd"><label class="weui-label">省市区</label></div>
			  		<div class="weui-cell__bd">
				   		 <input class="weui-input openmk" id="city-picker" type="text" value="" placeholder="请选择">
				    </div>
				    <div class="weui-cell__ft">
	    			</div>
			  </div>
			  <div class="weui-cell" >
			  	 <div class="weui-cell__hd"><label class="weui-label">详细地址</label></div>
			  		<div class="weui-cell__bd">
				   		 <input type="text" class="importinp" name="" value="" placeholder="请填写详细地址"/>
				   </div>
			  </div>
	  	</div>
  	</div>
		<div class="mask"></div>
	<?php echo $this->js('city-picker.min.js')->wrap();?>
  	<script type="text/javascript">
			
			$(".openmk").click(function(){
				$(".mask").fadeIn()
			})			
			$("#city-picker").cityPicker({
		    title: "请选择收货地址",
		    onClose: function (picker, values, displayValues) {
         	$(".mask").fadeOut()
        }
		  });
		  
		</script>