<div class="my_addr pb50">
    <?php if ($addressList) : ?>
        <?php foreach($addressList as $row) : ?>
          <div class="my_addr_list mb15 bgwhite">
            <?php if ($redirect) : ?>
              <?php $url = $redirect; $url['params']['address_id'] = $row['address_id'];?>
              <a href="<?php echo $this->funcs->urlInit($url);?>">
                <div class="wrap m_info">
                  <h4 style="color: #666;"><?php echo $row['user_name']?><span><?php echo $row['user_tel']?></span></h4>
                  <p><?php echo $row['user_address']?></p>
                </div>
              </a>
            <?php else : ?>
              <div class="wrap m_info">
                <h4><?php echo $row['user_name']?><span><?php echo $row['user_tel']?></span></h4>
                <p><?php echo $row['user_address']?></p>
              </div>
            <?php endif;?>
            <div class="wrap m_edit pr">
              <a class="moren" href="javascript:;" data-id="<?php echo $row['address_id']?>">
                  <i class="<?php echo $info['customer_default_address_id'] == $row['address_id'] ? 'weui-icon-success' : 'weui-icon-circle'?>"></i>设为默认地址
              </a>
              <a class="pa edt" href="<?php echo $this->url('customer/address-edit', array('id' => $row['address_id']))?>">
                  <i class="iconfont">&#xe640;</i>
              </a>
              <a class="pa delete" href="javascript:;" data-id="<?php echo $row['address_id']?>"><i class="iconfont">&#xe602;</i></a>
            </div>
          </div>
      <?php endforeach;?>
    <?php else : ?>
      <script type="text/javascript">
        window.location.href = '<?php echo $this->url('customer/address-edit', array('redirect' => $this->param('redirect'), 'prize_id' => $this->param('prize_id')))?>';
      </script>
    <?php endif;?>
</div>

<!-- 新建收货地址 -->
<div class="new_addr pf bgwhite">
  <a href="<?php echo $this->url('customer/address-edit', array('redirect' => $this->param('redirect'), 'prize_id' => $this->param('prize_id')))?>" class="weui-btn weui-btn_orange">新建收货地址</a>
</div>

<script type="text/javascript">
    var redirect = '<?php echo $this->param('redirect')?>';
    var prizeId = '<?php echo $this->param('prize_id')?>';

    // 点击删除
    $(".my_addr_list").find('.delete').on('click', function(event) {
        var $$ = $(this);
        var id = $$.data('id');

        $.confirm("确定删除地址吗?", "", function() {
            $$.removeAttr('href');
            $$.ajaxAuto({
                url: '<?php echo $this->url('customer/address-del')?>',
                data: {id: id},
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.parents(".my_addr_list").remove();
                    }
                }
            });
        }, function() {
            //取消操作
        });
    });

    //默认地址
    $(".my_addr_list").find('.moren').on('click', function() {
        var $$ = $(this);
        var id = $$.data('id');

        $$.removeAttr('href');
        $$.ajaxAuto({
            url: '<?php echo $this->url('customer/address-default')?>',
            data: {id: id, redirect: redirect, prize_id: prizeId},
            success: function (re) {
                if (re.status == 'ok') {
                    $$.children('i').removeClass('weui-icon-circle').addClass('weui-icon-success');
                    $$.parents('.my_addr_list').siblings('.my_addr_list').find('.moren').children('i').removeClass('weui-icon-success').addClass('weui-icon-circle');
                }
            }
        });
    });
</script>