<form method="post">
	<div class="mydata newaddress">
		<div class="weui-cells">	  		
		  <div class="weui-cell" >
		  	 <div class="weui-cell__hd"><label class="weui-label">收件人姓名</label></div>
		  		<div class="weui-cell__bd">
			   		 <input type="text" class="importinp" name="user_name" value="<?php echo isset($info['user_name']) ? $info['user_name'] : ''?>" placeholder="请输入姓名"/>
			   </div>
		  </div>
		  <div class="weui-cell" >
		  	 <div class="weui-cell__hd"><label class="weui-label">手机号码</label></div>
		  		<div class="weui-cell__bd">
			   		 <input type="number" class="importinp" name="user_tel" value="<?php echo isset($info['user_tel']) ? $info['user_tel'] : ''?>" placeholder="请输入手机号码"/>
			   </div>
		  </div>
		  <div class="weui-cell weui-cell_access" >
		  	 <div class="weui-cell__hd"><label class="weui-label">省市区</label></div>
		  		<div class="weui-cell__bd">
			   		 <input class="weui-input openmk" id="city-picker" type="text" value="<?php echo isset($info['user_address_city']) ? $info['user_address_city'] : ''?>" name="user_address_city" placeholder="请选择">
			    </div>
			    <div class="weui-cell__ft">
				</div>
		  </div>
		  <div class="weui-cell" >
		  	 <div class="weui-cell__hd"><label class="weui-label">详细地址</label></div>
		  		<div class="weui-cell__bd">
			   		 <input type="text" class="importinp" name="user_address_detail" value="<?php echo isset($info['user_address_detail']) ? $info['user_address_detail'] : ''?>" placeholder="请填写详细地址"/>
			   </div>
		  </div>
		</div>

		<button class="feedback_tj" type="submit">提交</button>
	</div>
</form>

<div class="mask"></div>

<?php echo $this->js('city-picker.min.js')->wrap();?>
<script type="text/javascript">
	$(".openmk").click(function(){
		$(".mask").fadeIn();
	});

	$("#city-picker").cityPicker({
	    title: "请选择收货地址",
	    onClose: function (picker, values, displayValues) {
	 		$(".mask").fadeOut();
		}
	});

	$('form').submit(function() {
		var $$ = $(this);

		$.check(!this.user_name.value, '请输入姓名', this.user_name) &&
		$.check(!this.user_tel.value, '请输入手机号码', this.user_tel) &&
		$.check(!this.user_address_city.value, '请选择省市区', this.user_address_city) &&
		$.check(!this.user_address_detail.value, '请填写详细地址', this.user_address_detail) &&
		$$.ajaxAuto();
		return false;
	});
</script>