  <div class="calenbox">
    <div id="calendar"></div>
  </div>
  <div class="qd_ts">
    <p>你已连续签到2天，明天继续签到可获得5个积分</p>
  </div>
  <button class="btn-qiandao" onClick="signIn()">签到</button>
<div class="maskbox"></div>
<div class="qdbox">
  <h5>+3.5积分</h5>
  <p>连续签到2天</p>
</div>

<?php echo $this->js('calendar.js')->wrap();?>
<script type="text/javascript">
  
  $(function(){
    //ajax获取日历json数据
    var signList=[{"signDay":"10"},{"signDay":"11"},{"signDay":"12"},{"signDay":"13"}];
     calUtil.init(signList);
  });
  
  function  signIn(){
    $(".maskbox").fadeIn();
    $(".qdbox").fadeIn();
    $(".maskbox").height($(document).height());
  }
  $(".maskbox").click(function(){
    $(".maskbox").fadeOut();
    $(".qdbox").fadeOut();
  });
</script>