<!--城市索引查询-->
<?php if ($districtList) : ?>
    <div class="letter select_letter">
      <ul>
        <?php foreach(array_keys($districtList) as $value) : ?>
            <li><a href="javascript:;"><?php echo $value?></a></li>
        <?php endforeach;?>
      </ul>
    </div>
    <!--城市列表-->
    <div class="select_city container">
      <div class="city">
        <?php foreach($districtList as $key => $rows) : ?>
            <div class="city-list"><span class="city-letter" id="<?php echo $key . '1'?>"><?php echo $key?></span>
                <?php foreach($rows as $row) : ?>
                    <a href="<?php echo $this->url('customer/change-city', array('id' => $row['district_id']))?>">
                        <p><?php echo $row['district_name']?></p>
                    </a>
                <?php endforeach;?>
            </div>
        <?php endforeach;?>
      </div>
    </div>
<?php endif;?>

<script type="text/javascript">
    /**
     * Created by Administrator on 2017/5/7.
     */
    $(function () {
        //加载城市事件
        $('.container').show();
        //点击索引查询城市
        $('body').on('click', '.letter a', function () {
            var s = $(this).html();
            $(window).scrollTop($('#' + s + '1').offset().top);
            $("#showLetter span").html(s);
            $("#showLetter").show().delay(500).hide(0);
        });
         //中间的标记显示
         $('body').on('onMouse', '.showLetter span', function () {
            $("#showLetter").show().delay(500).hide(0);
        });
    });
</script>