    <div class="my_collect">
      <div class="collect_li clearfix wrap pr">
        <div class="img fl">
          <img src="images/col_01.jpg">
        </div>
        <h4>山东红富士苹果两粒装买一送一</h4>
        <p><span class="orange">100积分</span></p>
        <a href="领取二维码.html" class="btn pa">去领取</a>
      </div>

      <div class="collect_li clearfix wrap pr">
        <div class="img fl">
          <img src="images/col_02.jpg">
        </div>
        <h4>山东红富士苹果两粒装买一送一山东红富士苹果两粒装买一送一</h4>
        <p><span class="orange">100积分</span></p>
        <a href="领取二维码.html" class="btn pa">去领取</a>
      </div>

      <div class="collect_li clearfix wrap pr">
        <div class="img fl">
          <img src="images/col_01.jpg">
        </div>
        <h4>山东红富士苹果两粒装买一送一山东红富士苹果两粒装买一送一</h4>
        <p><span class="orange">100积分</span></p>
        <a href="javascript:;" class="btn pa btn_no">去领取</a>
      </div>
    </div>