<div class="cluster">
  <div class="order_top clearfix">
    <div class="img fl">
      <img src="<?php echo $this->uploadUrl($order['product']['images']['banner'][0]['image_path'], 'product')?>">
    </div>
    <h4><?php echo $order['product']['product_name']?></h4>
  </div>
  <div class="cluster_ul">
    <?php foreach($info['customer_id'] as $key => $row) : ?>
        <?php if (!$key) : ?>
            <div class="cluster_li">
              <div class="cluster_big">
                <em>团长</em>
                <div class="img">
                  <img src="<?php echo $this->uploadUrl($row['customer_headimg'], 'user')?>"/>
                </div>
              </div>        
              <p><?php echo $row['customer_name']?></p>
            </div>
        <?php else :?>
            <div class="cluster_li">
              <div class="img">
                <img src="<?php echo $this->uploadUrl($row['customer_headimg'], 'user')?>"/>
              </div>
              <p><?php echo $row['customer_name']?></p>
            </div>
        <?php endif;?>
    <?php endforeach;?>
    <?php for($i=0; $i<(5 - count($info['customer_id'])); $i++) : ?>
        <div class="cluster_li">
          <div class="img"></div>
          <p></p>
        </div>
    <?php endfor;?>
  </div>
  <div class="cluster_down">
    <p>
        还剩<?php echo $i?>个名额：<span id="time" data-time="<?php echo $info['time']?>"><?php echo $this->funcs->showTime($info['time'])?></span>后结束
    </p>
    <a href="我的邀请码.html" class="feedback_tj weui-btn weui-btn_primary">邀请好友一起组团领</a>
  </div>
</div>

<script type="text/javascript">
    $(".cluster_li .img").height($(".cluster_li .img").width());

    setInterval(function () {
        var $$ = $('#time');
        var time = parseInt($$.data('time'));
        if (time < 0) {
            time = 0;

            window.location.reload();
            return false;
        }

        var init = {
            'year': [31536000, '年'],
            'month': [2592000, '月'],
            'day': [86400, '天'],
            'hour': [3600, '小时'],
            'minute': [60, '分'],
            'second': [1, '秒'],
        };
        var str = '';
        for(key in init) {
            num = Math.floor(time / init[key][0]);
            if (num) {
                str += num + init[key][1];
                time -= num * init[key][0];
            }
        }

        if (!str) {
            str = '0秒';
        }

        $$.data('time', parseInt($$.data('time')) - 1);
        $$.html(str);
    }, 1000);
</script>