<div id="simulator" style="overflow: visible; padding: 0px; width: 375px; height: 667px; left: 661px; top: 25px;" class=" portrait iphone x100"><div class="splash" style="background-color: rgb(255, 255, 255); display: none;"><div class="loading"><div class="spinner"></div></div></div><div id="ui-layers" class="ui-layers "><!-- react-empty: 560 --></div><div id="app" class="screens" style="display: block; touch-action: auto; user-select: none; -webkit-user-drag: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); background-color: rgb(255, 255, 255);"><div id="gs" style="display: block;"><div class="widget status_bar" id="widgetwBE8AA4A1FF1503366067761p" data-cid="wBE8AA4A1FF1503366067761" data-link_cid="" style="color: rgb(255, 255, 255); background-color: transparent; font-weight: normal; font-style: normal; z-index: 3; opacity: 1; pointer-events: auto;">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
</div></div><div id="gh" class="fixed iphone sb" style="height: 65px; top: 0px;"><div class="widget status_bar" id="widgetwBE8AA4A1FF1503366067761pgh" data-cid="wBE8AA4A1FF1503366067761" data-link_cid="" style="color:#ffffff;background-color:#121212;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
</div><div class="widget navigation_bar" id="widgetw2F35DB51EF1503366121772pgh" data-cid="w2F35DB51EF1503366121772" data-link_cid="" style="height:45px;color:#ffffff;background-color:#000000;border-color:#524f52;font-size:18.0px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="text">订单详情</span>
  
</div><div class="widget icon_button clickable" id="widgetw28D3FC45C41503366121797pgh" data-cid="w28D3FC45C41503366121797" data-link_cid="lD63CF58EA91503368439973" style="width:45px;height:45px;left:-6px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon fa fa-angle-left" style="font-size:24px;"></span>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw82A1DE2DFD1503366121805pgh" data-cid="w82A1DE2DFD1503366121805" data-link_cid="lD63CF58EA91503368439973" style="width:29px;height:23px;left:29px;top:33px;color:#ffffff;border-color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>返回</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button" id="widgetw847B967E9B1503366121813pgh" data-cid="w847B967E9B1503366121813" data-link_cid="" style="width:45px;height:45px;left:330px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon md md-more_horiz" style="font-size:24px;">more_horiz</span>
  
</div></div><div id="gf" class="fixed sb" style="height: 0px; bottom: 0px;"></div>
      <div id="pscreens08DE13B61B1503027433502" class="pcanvas portrait sb" data-cid="s08DE13B61B1503027433502" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="f6939075-975c-8f95-c398-df2d502dde35">
        <div class="scontainer" style="height: 1057px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens19B26B3CB91503027433506" class="pcanvas portrait sb" data-cid="s19B26B3CB91503027433506" data-orientation="portrait" style="background-color: rgb(255, 255, 255); display: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="e33cf406-9488-f407-fc10-e07ff36bc97f">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens6DBD9927511503034380535" class="pcanvas portrait" data-cid="s6DBD9927511503034380535" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD95A0C75E61503048379479" class="pcanvas portrait" data-cid="sD95A0C75E61503048379479" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens853A9E102C1503048373957" class="pcanvas portrait sb" data-cid="s853A9E102C1503048373957" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="da263f77-1413-b0f1-e8f8-6641c19d329c">
        <div class="scontainer" style="height: 1568px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens138684F5D91503049356067" class="pcanvas portrait" data-cid="s138684F5D91503049356067" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens912BE6522D1503049921427" class="pcanvas portrait" data-cid="s912BE6522D1503049921427" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens064B7F5AE91503050233321" class="pcanvas portrait" data-cid="s064B7F5AE91503050233321" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens269E0C78491503050546114" class="pcanvas portrait sb" data-cid="s269E0C78491503050546114" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="2104fbdc-00ee-80d3-e5a2-fce322a30ba1">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensDE0C8678CD1503050837247" class="pcanvas portrait sb" data-cid="sDE0C8678CD1503050837247" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default ps-active-y" data-ps-id="0aa2422d-b664-dab7-8664-a63ebac2f451">
        <div class="scontainer" style="height: 984px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; height: 667px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 452px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensF130E53EEB1503050989458" class="pcanvas portrait" data-cid="sF130E53EEB1503050989458" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensA61DD99DE91503051069466" class="pcanvas portrait" data-cid="sA61DD99DE91503051069466" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens82DC0594601503051245690" class="pcanvas portrait sb" data-cid="s82DC0594601503051245690" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="c63fa758-f943-0b98-1795-b21f17448ec4">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5252CCCCF51503051485535" class="pcanvas portrait sb" data-cid="s5252CCCCF51503051485535" data-orientation="portrait" style="display: none; transition: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="3b40bb91-bc1a-1042-e9d9-655e7ec3cb19">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD3715BAF941503051693029" class="pcanvas portrait" data-cid="sD3715BAF941503051693029" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensEE7A420EA61503279906428" class="pcanvas portrait sb" data-cid="sEE7A420EA61503279906428" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="cfb6059b-a2e1-e68e-0dc0-886c1a93b4c5">
        <div class="scontainer" style="height: 1661px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens6E6853CE9F1503281232502" class="pcanvas portrait" data-cid="s6E6853CE9F1503281232502" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensC103EBF1BB1503281290487" class="pcanvas portrait sb" data-cid="sC103EBF1BB1503281290487" data-orientation="portrait" style="display: none; transition: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="ac2a76d2-941e-3eb1-2269-eda92c75a787">
        <div class="scontainer" style="height: 1661px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensB6939004FC1503281355966" class="pcanvas portrait" data-cid="sB6939004FC1503281355966" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensE20262A3371503281446741" class="pcanvas portrait" data-cid="sE20262A3371503281446741" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensDBA81FBB1D1503281647815" class="pcanvas portrait" data-cid="sDBA81FBB1D1503281647815" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens15FA8BEA731503282897377" class="pcanvas portrait sb" data-cid="s15FA8BEA731503282897377" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="c1eeb8fc-71cd-3f69-c670-dede2709ceb0">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens93E7585AE31503282923946" class="pcanvas portrait" data-cid="s93E7585AE31503282923946" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5388D05FD81503283311522" class="pcanvas portrait" data-cid="s5388D05FD81503283311522" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensDF98F95E6A1503283419882" class="pcanvas portrait" data-cid="sDF98F95E6A1503283419882" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens0909F5ECB41503283669672" class="pcanvas portrait" data-cid="s0909F5ECB41503283669672" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens9144D490101503283797210" class="pcanvas portrait sb" data-cid="s9144D490101503283797210" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="b70d4dd9-849f-e820-de4d-47fb745d48cc">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens36CBE1AD161503284008264" class="pcanvas portrait" data-cid="s36CBE1AD161503284008264" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens0BB58359DA1503285271230" class="pcanvas portrait sb" data-cid="s0BB58359DA1503285271230" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="ff352a1c-abee-15bc-7d5d-ec1852064843">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens87C39B7B1C1503285541839" class="pcanvas portrait sb" data-cid="s87C39B7B1C1503285541839" data-orientation="portrait" style="display: none; transition: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="9b338c6e-2bdb-19f3-0129-d46e3188229b">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD01B41AB791503285639132" class="pcanvas portrait sb" data-cid="sD01B41AB791503285639132" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="3f600aed-7b01-047e-8145-d2f31b0b97bb">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD6DA0069F91503286830698" class="pcanvas portrait" data-cid="sD6DA0069F91503286830698" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensB2F2CACDB51503287993851" class="pcanvas portrait" data-cid="sB2F2CACDB51503287993851" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensFF3D7C01181503288271057" class="pcanvas portrait" data-cid="sFF3D7C01181503288271057" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD89FFC068A1503288846474" class="pcanvas portrait" data-cid="sD89FFC068A1503288846474" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD121F8E6401503288938049" class="pcanvas portrait" data-cid="sD121F8E6401503288938049" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensBF0322AC031503288947378" class="pcanvas portrait" data-cid="sBF0322AC031503288947378" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens1C2608701D1503288958760" class="pcanvas portrait" data-cid="s1C2608701D1503288958760" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensFFC88D25FC1503288971472" class="pcanvas portrait" data-cid="sFFC88D25FC1503288971472" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens35B18E34F11503292245602" class="pcanvas portrait" data-cid="s35B18E34F11503292245602" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens469E1274231503293603842" class="pcanvas portrait sb" data-cid="s469E1274231503293603842" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="530087ec-5441-3d94-5dde-2c9ec6d2ebae">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens328A3117121503293721007" class="pcanvas portrait" data-cid="s328A3117121503293721007" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens638677B13C1503294125558" class="pcanvas portrait" data-cid="s638677B13C1503294125558" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensDE91E82C8C1503294573871" class="pcanvas portrait sb" data-cid="sDE91E82C8C1503294573871" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="1c3769c9-77d0-3d2c-5c8e-7e3ad17a98aa">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens6D7AE69EB81503294678972" class="pcanvas portrait" data-cid="s6D7AE69EB81503294678972" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens870A91D2F01503294730195" class="pcanvas portrait" data-cid="s870A91D2F01503294730195" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5B0C2080351503295060404" class="pcanvas portrait sb" data-cid="s5B0C2080351503295060404" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="8b92fff5-3fa0-c711-61d1-8532aa697fc2">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensE8744FC45A1503295167964" class="pcanvas portrait" data-cid="sE8744FC45A1503295167964" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens9D0B98D4501503295297428" class="pcanvas portrait sb" data-cid="s9D0B98D4501503295297428" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="1fdaeea9-ebc9-6fd4-2061-276c1e4aa41f">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens55617CBCAB1503296427279" class="pcanvas portrait" data-cid="s55617CBCAB1503296427279" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens4A3476E37E1503296688198" class="pcanvas portrait" data-cid="s4A3476E37E1503296688198" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensFDA7AF6F981503297489230" class="pcanvas portrait" data-cid="sFDA7AF6F981503297489230" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensFD30A1D9421503297884635" class="pcanvas portrait" data-cid="sFD30A1D9421503297884635" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens0541F220351503297877876" class="pcanvas portrait" data-cid="s0541F220351503297877876" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens39C6FD93F41503298132629" class="pcanvas portrait" data-cid="s39C6FD93F41503298132629" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens22D7B387341503298130950" class="pcanvas portrait" data-cid="s22D7B387341503298130950" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens4A3D4C530F1503298310532" class="pcanvas portrait" data-cid="s4A3D4C530F1503298310532" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensBF05F6ED0A1503298413228" class="pcanvas portrait" data-cid="sBF05F6ED0A1503298413228" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensC681EE640D1503298462453" class="pcanvas portrait" data-cid="sC681EE640D1503298462453" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens7B63D6B0B71503298623467" class="pcanvas portrait" data-cid="s7B63D6B0B71503298623467" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens27E8D2EA3C1503298710979" class="pcanvas portrait" data-cid="s27E8D2EA3C1503298710979" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensA3B090A91E1503298791948" class="pcanvas portrait" data-cid="sA3B090A91E1503298791948" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensEF07D648011503298947767" class="pcanvas portrait" data-cid="sEF07D648011503298947767" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD0F86E9DD11503299171331" class="pcanvas portrait" data-cid="sD0F86E9DD11503299171331" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens788869CEB31503299320039" class="pcanvas portrait" data-cid="s788869CEB31503299320039" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensEF3BB84EDB1503299620551" class="pcanvas portrait sb" data-cid="sEF3BB84EDB1503299620551" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="32bc40e5-0c32-6f3b-c3d8-702fe4c44c2a">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div><div class="widget status_bar" id="widgetw64C26C312E1503299620553p" data-cid="w64C26C312E1503299620553" data-link_cid="" style="color:#ffffff;background-color:#0a010a;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
</div><div class="widget navigation_bar" id="widgetw539BC037B71503299620554p" data-cid="w539BC037B71503299620554" data-link_cid="" style="height:45px;color:#ffffff;background-color:#000000;border-color:#524f52;font-size:18.0px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span class="text">我的订单</span>
  
</div><div class="widget icon_button" id="widgetwA340DEF4271503299620555p" data-cid="wA340DEF4271503299620555" data-link_cid="" style="width:45px;height:45px;left:-6px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span class="icon fa fa-angle-left" style="font-size:24px;"></span>
  
</div><div class="widget label vmiddle" id="widgetw4EE323279B1503299620557p" data-cid="w4EE323279B1503299620557" data-link_cid="" style="width:29px;height:23px;left:29px;top:33px;color:#ffffff;border-color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>返回</p>
  
</div><div class="widget icon_button" id="widgetwB8AE5D7D2B1503299620558p" data-cid="wB8AE5D7D2B1503299620558" data-link_cid="" style="width:45px;height:45px;left:330px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span class="icon md md-more_horiz" style="font-size:24px;">more_horiz</span>
  
</div><div class="widget rounded_rect vmiddle clickable" id="widgetwC85EDC859D1503299627632p" data-cid="wC85EDC859D1503299627632" data-link_cid="lC35E5EBA0F1503368389579" style="width:375px;height:120px;left:0px;top:133px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle" id="widgetw11ED9465751503299627639p" data-cid="w11ED9465751503299627639" data-link_cid="" style="width:65px;height:23px;left:16px;top:142px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>2017-07-21</p>
  
</div><div class="widget label vmiddle" id="widgetwDEA3399CEF1503299627645p" data-cid="wDEA3399CEF1503299627645" data-link_cid="" style="width:92px;height:23px;left:273px;top:142px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>待成团，还差2人</p>
  
</div><div class="widget image_view" id="widgetw876B7D1FBA1503299627652p" data-cid="w876B7D1FBA1503299627652" data-link_cid="" style="width:80px;height:80px;left:15px;top:166px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget text_view vtop" id="widgetwF38643CA471503299627656p" data-cid="wF38643CA471503299627656" data-link_cid="" style="width:210px;height:45px;left:103px;top:173px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:left;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>如果你无法简洁的表达你的想法</p><p>那只说明你还不够了解它</p></div>
  
</div><div class="widget label vmiddle" id="widgetw78C707F39C1503299627659p" data-cid="w78C707F39C1503299627659" data-link_cid="" style="width:32px;height:23px;left:330px;top:188px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>0积分</p>
  
</div><div class="widget hr" id="widgetw5EA8F7E4211503299627662p" data-cid="w5EA8F7E4211503299627662" data-link_cid="" style="width:375px;height:10px;left:0px;top:255px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget label vmiddle" id="widgetwBD715891071503299788963p" data-cid="wBD715891071503299788963" data-link_cid="" style="width:184px;height:23px;left:15px;top:116px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>订单号：2017082115160001</p>
  
</div><div class="widget rounded_rect vmiddle clickable" id="widgetw5CE2F4549C1503299834878p" data-cid="w5CE2F4549C1503299834878" data-link_cid="l6E78BB4E591503368394781" style="width:375px;height:120px;left:0px;top:284px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle" id="widgetwF3BFAE14731503299834884p" data-cid="wF3BFAE14731503299834884" data-link_cid="" style="width:65px;height:23px;left:16px;top:293px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>2017-07-21</p>
  
</div><div class="widget label vmiddle" id="widgetw7D31F166431503299834890p" data-cid="w7D31F166431503299834890" data-link_cid="" style="width:92px;height:23px;left:273px;top:293px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>待成团，还差3人</p>
  
</div><div class="widget image_view" id="widgetw7CDFECDE131503299834894p" data-cid="w7CDFECDE131503299834894" data-link_cid="" style="width:80px;height:80px;left:15px;top:317px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget text_view vtop" id="widgetw42BB0C416C1503299834897p" data-cid="w42BB0C416C1503299834897" data-link_cid="" style="width:210px;height:45px;left:103px;top:324px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:left;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>如果你无法简洁的表达你的想法</p><p>那只说明你还不够了解它</p></div>
  
</div><div class="widget label vmiddle" id="widgetw38B9B535071503299834899p" data-cid="w38B9B535071503299834899" data-link_cid="" style="width:32px;height:23px;left:330px;top:339px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>0积分</p>
  
</div><div class="widget hr" id="widgetw236315E0211503299834902p" data-cid="w236315E0211503299834902" data-link_cid="" style="width:375px;height:10px;left:0px;top:406px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget label vmiddle" id="widgetw7BED7A94771503299834906p" data-cid="w7BED7A94771503299834906" data-link_cid="" style="width:184px;height:23px;left:15px;top:267px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>订单号：2017082115160002</p>
  
</div><div class="widget button vmiddle" id="widgetwEE7F094A5D1503301194015p" data-cid="wEE7F094A5D1503301194015" data-link_cid="" style="width:70px;height:30px;left:295px;top:376px;color:#ff9800;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">组团详情</span>
</p>
  
</div><div class="widget button vmiddle clickable" id="widgetw214B1359841503301209805p" data-cid="w214B1359841503301209805" data-link_cid="l93DEB76C821503368379420" style="width:70px;height:30px;left:295px;top:225px;color:#ff9800;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">组团详情</span>
</p>
  <div class="region gesture "></div>
</div><div class="widget rounded_rect vmiddle" id="widgetw65C346943F1505198752063p" data-cid="w65C346943F1505198752063" data-link_cid="" style="width:375px;height:45px;left:0px;top:65px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:1px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  
</div><div class="widget label vmiddle clickable" id="widgetw9B0C54E2421505198752073p" data-cid="w9B0C54E2421505198752073" data-link_cid="l17845EF4791505198802135" style="width:81px;height:45px;left:1px;top:65px;color:#000000;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>全部</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw3FAE1BAA6F1505198752078p" data-cid="w3FAE1BAA6F1505198752078" data-link_cid="l8720F8282B1505198752047" style="width:75px;height:45px;left:80px;top:65px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>待领取</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw4C5C049D571505198752083p" data-cid="w4C5C049D571505198752083" data-link_cid="l216284E61F1505198752047" style="width:90px;height:45px;left:216px;top:65px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>待评价</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw2F4DFCBA861505198752087p" data-cid="w2F4DFCBA861505198752087" data-link_cid="lBEFB2F86A51505198752047" style="width:84px;height:45px;left:292px;top:65px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>已完成</p>
  <div class="region gesture "></div>
</div><div class="widget hr" id="widgetwA2309BF1751505198752097p" data-cid="wA2309BF1751505198752097" data-link_cid="" style="width:50px;height:13px;left:163px;top:103px;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="border-top-width: 3px;"></span>
  
</div><div class="widget label vmiddle" id="widgetwFF5DF142671505198752103p" data-cid="wFF5DF142671505198752103" data-link_cid="" style="width:75px;height:45px;left:150px;top:65px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>组团中</p>
  
</div><div class="widget rounded_rect vmiddle clickable" id="widgetwD76EE4E5EB1505198917849p" data-cid="wD76EE4E5EB1505198917849" data-link_cid="lB4B6A5AF1B1505198917833" style="width:375px;height:120px;left:0px;top:438px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle" id="widgetwF5801CBA911505198917859p" data-cid="wF5801CBA911505198917859" data-link_cid="" style="width:65px;height:23px;left:17px;top:447px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>2017-07-21</p>
  
</div><div class="widget label vmiddle" id="widgetwF93F4F825B1505198917864p" data-cid="wF93F4F825B1505198917864" data-link_cid="" style="width:49px;height:23px;left:320px;top:447px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>组团失败</p>
  
</div><div class="widget image_view" id="widgetw52744D8F951505198917869p" data-cid="w52744D8F951505198917869" data-link_cid="" style="width:80px;height:80px;left:16px;top:471px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget text_view vtop" id="widgetw414D39142A1505198917874p" data-cid="w414D39142A1505198917874" data-link_cid="" style="width:210px;height:45px;left:104px;top:478px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:left;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>如果你无法简洁的表达你的想法</p><p>那只说明你还不够了解它</p></div>
  
</div><div class="widget label vmiddle" id="widgetw8B6D71DAEB1505198917878p" data-cid="w8B6D71DAEB1505198917878" data-link_cid="" style="width:32px;height:23px;left:331px;top:493px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>0积分</p>
  
</div><div class="widget button vmiddle clickable" id="widgetw09E727CF441505198917883p" data-cid="w09E727CF441505198917883" data-link_cid="l97C3F71DC31505198917833" style="width:70px;height:30px;left:296px;top:526px;color:#ff9800;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">组团详情</span>
</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle" id="widgetwC23489A1091505198917890p" data-cid="wC23489A1091505198917890" data-link_cid="" style="width:184px;height:23px;left:16px;top:421px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>订单号：2017082115160001</p>
  
</div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensAFB6C4BBF61503301747452" class="pcanvas portrait" data-cid="sAFB6C4BBF61503301747452" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensC3D88FFC091503307195540" class="pcanvas portrait" data-cid="sC3D88FFC091503307195540" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens1CDF58D3F81503308122954" class="pcanvas portrait" data-cid="s1CDF58D3F81503308122954" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5114FA50741503309233059" class="pcanvas portrait" data-cid="s5114FA50741503309233059" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensCF443E7DE01503309819317" class="pcanvas portrait" data-cid="sCF443E7DE01503309819317" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5BFB942BBA1503310218547" class="pcanvas portrait" data-cid="s5BFB942BBA1503310218547" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens641F1F9FDE1503366067759" class="pcanvas portrait sb active" data-cid="s641F1F9FDE1503366067759" data-orientation="portrait" style="display: block; background-color: transparent; transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="fce30dc7-5315-f799-28f2-cebb79a7ed0d">
        <div class="scontainer" style="height: 667px;"><div class="sheader" style="height: 65px; background-color: rgb(255, 255, 255);"></div><div class="sfooter" style="height: 0px; background-color: rgb(255, 255, 255);"></div><div class="widget status_bar" id="widgetwBE8AA4A1FF1503366067761p" data-cid="wBE8AA4A1FF1503366067761" data-link_cid="" style="color:#ffffff;background-color:#121212;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
  <!--lonny-->
</div><div class="widget navigation_bar" id="widgetw2F35DB51EF1503366121772p" data-cid="w2F35DB51EF1503366121772" data-link_cid="" style="height:45px;color:#ffffff;background-color:#000000;border-color:#524f52;font-size:18.0px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="text">订单详情</span>
  
</div><div class="widget icon_button clickable" id="widgetw28D3FC45C41503366121797p" data-cid="w28D3FC45C41503366121797" data-link_cid="lD63CF58EA91503368439973" style="width:45px;height:45px;left:-6px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon fa fa-angle-left" style="font-size:24px;"></span>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw82A1DE2DFD1503366121805p" data-cid="w82A1DE2DFD1503366121805" data-link_cid="lD63CF58EA91503368439973" style="width:29px;height:23px;left:29px;top:33px;color:#ffffff;border-color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>返回</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button" id="widgetw847B967E9B1503366121813p" data-cid="w847B967E9B1503366121813" data-link_cid="" style="width:45px;height:45px;left:330px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon md md-more_horiz" style="font-size:24px;">more_horiz</span>
  
</div><div class="widget rounded_rect vmiddle" id="widgetw8CB035AB0B1503366121820p" data-cid="w8CB035AB0B1503366121820" data-link_cid="" style="width:375px;height:36px;left:0px;top:66px;background-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  
</div><div class="widget label vmiddle" id="widgetw2C47D9CCF51503366121831p" data-cid="w2C47D9CCF51503366121831" data-link_cid="" style="width:107px;height:23px;left:10px;top:73px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p><?php echo $info['group_type']['msg']?></p>
  
</div><div class="widget label vmiddle" id="widgetw0AA3B66F2D1503366121837p" data-cid="w0AA3B66F2D1503366121837" data-link_cid="" style="width:186px;height:23px;left:11px;top:120px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>订单号：<?php echo $order['order_number']?></p>
  
</div><div class="widget label vmiddle" id="widgetw5E5822D48D1503366121843p" data-cid="w5E5822D48D1503366121843" data-link_cid="" style="width:127px;height:23px;left:240px;top:120px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p><?php echo date('Y-m-d H:i:s', strtotime($order['order_time']))?></p>
  
</div><div class="widget image_view" id="widgetw871F93E1751503366121850p" data-cid="w871F93E1751503366121850" data-link_cid="" style="width:80px;height:80px;left:16px;top:159px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img src="<?php echo $this->uploadUrl($order['product']['images']['banner'][0]['image_path'], 'product');?>"></div>
  
</div><div class="widget text_view vtop" id="widgetwBEF354F4711503366121856p" data-cid="wBEF354F4711503366121856" data-link_cid="" style="width:210px;height:45px;left:104px;top:176px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;text-align:left;line-height:20px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p><?php echo $order['product']['product_name']?></p></div>
  
</div><div class="widget label vmiddle" id="widgetw601339EB4F1503366121865p" data-cid="w601339EB4F1503366121865" data-link_cid="" style="width:46px;height:23px;left:323px;top:186px;color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:17px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p><?php echo sprintf('%d积分', $order['product']['product_price'])?></p>
  
</div><div class="widget label vmiddle" id="widgetwF2DD004BEE1503366157918p" data-cid="wF2DD004BEE1503366157918" data-link_cid="" style="width:195px;height:23px;left:168px;top:73px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <?php if ($info['time'] < 0) : ?>
      <p>组团已过期</p>
  <?php else : ?>
    <p>剩余拼团时间：<span id="time" data-time="<?php echo $info['time']?>"><?php echo $this->funcs->showTime($info['time'])?></span></p>
    <script type="text/javascript">
      setInterval(function () {
          var $$ = $('#time');
          var time = parseInt($$.data('time'));
          if (time < 0) {
              time = 0;

              window.location.reload();
              return false;
          }

          var init = {
              'year': [31536000, '年'],
              'month': [2592000, '月'],
              'day': [86400, '天'],
              'hour': [3600, '小时'],
              'minute': [60, '分'],
              'second': [1, '秒'],
          };
          var str = '';
          for(key in init) {
              num = Math.floor(time / init[key][0]);
              if (num) {
                  str += num + init[key][1];
                  time -= num * init[key][0];
              }
          }

          if (!str) {
              str = '0秒';
          }

          $$.data('time', parseInt($$.data('time')) - 1);
          $$.html(str);
      }, 1000);
    </script>
  <?php endif;?>

  
</div><div class="widget label vmiddle" id="widgetw78D1FB9FEB1503366263130p" data-cid="w78D1FB9FEB1503366263130" data-link_cid="" style="width:57px;height:23px;left:16px;top:257px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>取货方式</p>
  
</div><div class="widget label vmiddle" id="widgetw4EF18E0E801503366263147p" data-cid="w4EF18E0E801503366263147" data-link_cid="" style="width:29px;height:23px;left:334px;top:257px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>自提</p>
  
</div><div class="widget hr" id="widgetw158C038EEB1503366263154p" data-cid="w158C038EEB1503366263154" data-link_cid="" style="width:375px;height:10px;left:0px;top:280px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget label vmiddle" id="widgetw78E6E5C8E41503366286643p" data-cid="w78E6E5C8E41503366286643" data-link_cid="" style="width:177px;height:26px;left:99px;top:317px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:16.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:23px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>取货码在组团成功后展示</p>
  
</div><div class="widget hr" id="widgetwA17B4448C41503366325886p" data-cid="wA17B4448C41503366325886" data-link_cid="" style="width:375px;height:10px;left:0px;top:367px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget button vmiddle clickable" id="widgetwE4D27BC9761503366346283p" data-cid="wE4D27BC9761503366346283" data-link_cid="l793EC90BAA1503368414797" style="width:70px;height:30px;left:298px;top:386px;color:#ff9800;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">邀请好友</span>
</p>
  <div class="region gesture "></div>
</div><div class="widget button vmiddle clickable" id="widgetw9788B99FAC1503366377609p" data-cid="w9788B99FAC1503366377609" data-link_cid="l6150BC08AE1503368410822" style="width:82px;height:30px;left:214px;top:386px;color:#ff9800;border-color:#FF7B00;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:12.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">组团详情</span>
</p>
  <div class="region gesture "></div>
</div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens0144D19BC51503366458296" class="pcanvas portrait sb" data-cid="s0144D19BC51503366458296" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="9eea7555-6801-8731-8538-6c0a0d9b103c">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensF4E70F40381503366504090" class="pcanvas portrait sb" data-cid="sF4E70F40381503366504090" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="73d8bb74-4d2f-0f1b-508c-a08259a13309">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div><div class="widget status_bar" id="widgetw0E369C9DFD1503366504092p" data-cid="w0E369C9DFD1503366504092" data-link_cid="" style="color:#ffffff;background-color:#121212;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
</div><div class="widget navigation_bar" id="widgetwEB65E38AFE1503366543180p" data-cid="wEB65E38AFE1503366543180" data-link_cid="" style="height:45px;color:#ffffff;background-color:#000000;border-color:#524f52;font-size:18.0px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="text">组团详情</span>
  
</div><div class="widget icon_button clickable" id="widgetwB2C5B2FE1D1503366543191p" data-cid="wB2C5B2FE1D1503366543191" data-link_cid="lB93023866F1503368517344" style="width:45px;height:45px;left:-6px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon fa fa-angle-left" style="font-size:24px;"></span>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw256400AF6F1503366543199p" data-cid="w256400AF6F1503366543199" data-link_cid="lB93023866F1503368517344" style="width:29px;height:23px;left:29px;top:33px;color:#ffffff;border-color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>返回</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button" id="widgetwDFBE1E21C41503366543208p" data-cid="wDFBE1E21C41503366543208" data-link_cid="" style="width:45px;height:45px;left:330px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon md md-more_horiz" style="font-size:24px;">more_horiz</span>
  
</div><div class="widget image_view" id="widgetw89783372281503366601733p" data-cid="w89783372281503366601733" data-link_cid="" style="width:80px;height:80px;left:29px;top:80px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw3CE96C29A81503366628816p" data-cid="w3CE96C29A81503366628816" data-link_cid="" style="width:241px;height:23px;left:126px;top:107px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:16.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:23px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>江中猴菇早餐米稀江中猴菇早餐米</p>
  
</div><div class="widget hr" id="widgetwC65C2E28341503366723336p" data-cid="wC65C2E28341503366723336" data-link_cid="" style="width:375px;height:10px;left:0px;top:169px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget image_view" id="widgetw730CE0175D1503366746137p" data-cid="w730CE0175D1503366746137" data-link_cid="" style="width:50px;height:50px;left:30px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetwACE60B42281503366799310p" data-cid="wACE60B42281503366799310" data-link_cid="" style="width:40px;height:23px;left:33px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>一只喵</p>
  
</div><div class="widget image_view" id="widgetwDBBFE000FD1503366828668p" data-cid="wDBBFE000FD1503366828668" data-link_cid="" style="width:50px;height:50px;left:95px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw305A2CF14B1503366828678p" data-cid="w305A2CF14B1503366828678" data-link_cid="" style="width:53px;height:23px;left:95.5px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>隔壁老王</p>
  
</div><div class="widget image_view" id="widgetwBF0C30BA491503366835539p" data-cid="wBF0C30BA491503366835539" data-link_cid="" style="width:50px;height:50px;left:165px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw1743C885EB1503366835548p" data-cid="w1743C885EB1503366835548" data-link_cid="" style="width:27px;height:23px;left:179px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>透露</p>
  
</div><div class="widget image_view" id="widgetwB47527EE411503366852075p" data-cid="wB47527EE411503366852075" data-link_cid="" style="width:50px;height:50px;left:229px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw64F84A42651503366852100p" data-cid="w64F84A42651503366852100" data-link_cid="" style="width:27px;height:23px;left:242px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>天真</p>
  
</div><div class="widget image_view" id="widgetw8D722FFB061503366863845p" data-cid="w8D722FFB061503366863845" data-link_cid="" style="width:50px;height:50px;left:292px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget rounded_rect vmiddle" id="widgetw12544735D41503367003017p" data-cid="w12544735D41503367003017" data-link_cid="" style="width:40px;height:18px;left:55px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:10.0px;padding:0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;line-height:15px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;margin-top: -8.5px;"><p>团长</p></div>
  
</div><div class="widget label vmiddle" id="widgetwB0602019C41503367107023p" data-cid="wB0602019C41503367107023" data-link_cid="" style="width:20px;height:26px;left:307px;top:202px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:18.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:26px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>？</p>
  
</div><div class="widget label vmiddle" id="widgetwDB4E1517B11503367158712p" data-cid="wDB4E1517B11503367158712" data-link_cid="" style="width:191px;height:23px;left:92px;top:290px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>还剩1个名额，23:55:12后结束</p>
  
</div><div class="widget button vmiddle clickable" id="widgetwFA02A21BB61503367242418p" data-cid="wFA02A21BB61503367242418" data-link_cid="lCADD66D43B1503368455718" style="width:300px;height:32px;left:36px;top:350px;color:#ffffff;background-color:#ff9800;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">邀请好友一起组团领</span>
</p>
  <div class="region gesture "></div>
</div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5B7D84FAFD1503367374107" class="pcanvas portrait sb" data-cid="s5B7D84FAFD1503367374107" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="180b4d0c-9578-4e63-6ea2-27d0b8e22631">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div><div class="widget status_bar" id="widgetw82BFD7E6501503367374113p" data-cid="w82BFD7E6501503367374113" data-link_cid="" style="color:#ffffff;background-color:#121212;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="signal">
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
  <div class="ball" style="background-color:#ffffff;"></div>
</div>
<div class="carrier">
  <span class="text">中国移动</span>
</div>
<div class="time">
  12:00<span class="meridian"> AM</span>
</div>
<div class="battery">
  <div class="body" style="border-color:#ffffff;">
    <div class="inner" style="background-color:#ffffff;"></div>
  </div>
  <div class="head" style="background-color:#ffffff;"></div>
</div>
<div class="border"></div>
  
</div><div class="widget navigation_bar" id="widgetw93E39D90F61503367399000p" data-cid="w93E39D90F61503367399000" data-link_cid="" style="height:45px;color:#ffffff;background-color:#000000;border-color:#524f52;font-size:18.0px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="text">组团详情</span>
  
</div><div class="widget icon_button clickable" id="widgetwA4AB03B2671503367399022p" data-cid="wA4AB03B2671503367399022" data-link_cid="lDC3010F1821503368682322" style="width:45px;height:45px;left:-6px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon fa fa-angle-left" style="font-size:24px;"></span>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw75E158D7C41503367399029p" data-cid="w75E158D7C41503367399029" data-link_cid="lDC3010F1821503368682322" style="width:29px;height:23px;left:29px;top:33px;color:#ffffff;border-color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>返回</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button" id="widgetwF2E0CEC6C51503367399037p" data-cid="wF2E0CEC6C51503367399037" data-link_cid="" style="width:45px;height:45px;left:330px;top:20px;color:#ffffff;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span class="icon md md-more_horiz" style="font-size:24px;">more_horiz</span>
  
</div><div class="widget image_view" id="widgetw532A9593811503367399043p" data-cid="w532A9593811503367399043" data-link_cid="" style="width:80px;height:80px;left:29px;top:80px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw6B4B31D1641503367399052p" data-cid="w6B4B31D1641503367399052" data-link_cid="" style="width:241px;height:23px;left:126px;top:107px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:16.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:23px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>江中猴菇早餐米稀江中猴菇早餐米</p>
  
</div><div class="widget hr" id="widgetwD197BEE9B91503367399060p" data-cid="wD197BEE9B91503367399060" data-link_cid="" style="width:375px;height:10px;left:0px;top:169px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="border-top-width: 1px;"></span>
  
</div><div class="widget image_view" id="widgetwB13236E7151503367399066p" data-cid="wB13236E7151503367399066" data-link_cid="" style="width:50px;height:50px;left:30px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetwC29FFD41661503367399072p" data-cid="wC29FFD41661503367399072" data-link_cid="" style="width:40px;height:23px;left:33px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>一只喵</p>
  
</div><div class="widget image_view" id="widgetwAF0C37F7F51503367399079p" data-cid="wAF0C37F7F51503367399079" data-link_cid="" style="width:50px;height:50px;left:95px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetwF279CCAE331503367399088p" data-cid="wF279CCAE331503367399088" data-link_cid="" style="width:53px;height:23px;left:95.5px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>隔壁老王</p>
  
</div><div class="widget image_view" id="widgetwD5FB28BDD81503367399094p" data-cid="wD5FB28BDD81503367399094" data-link_cid="" style="width:50px;height:50px;left:165px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetw3D948C57291503367399101p" data-cid="w3D948C57291503367399101" data-link_cid="" style="width:27px;height:23px;left:179px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>透露</p>
  
</div><div class="widget image_view" id="widgetw31D758C0B01503367399107p" data-cid="w31D758C0B01503367399107" data-link_cid="" style="width:50px;height:50px;left:229px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget label vmiddle" id="widgetwCAAAAA0EB91503367399114p" data-cid="wCAAAAA0EB91503367399114" data-link_cid="" style="width:27px;height:23px;left:242px;top:241px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:13.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:19px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>天真</p>
  
</div><div class="widget image_view" id="widgetw72C63482F21503367399120p" data-cid="w72C63482F21503367399120" data-link_cid="" style="width:50px;height:50px;left:292px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:100px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <span style="background-color:;display:flex;"><i class="icon-widget-img"></i></span>
<div class="wrapper"><img draggable="false" style="height:auto;display:none;"></div>
  
</div><div class="widget rounded_rect vmiddle" id="widgetw674B250BF71503367399131p" data-cid="w674B250BF71503367399131" data-link_cid="" style="width:40px;height:18px;left:55px;top:190px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:10.0px;padding:0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;line-height:15px;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;margin-top: -8.5px;"><p>团长</p></div>
  
</div><div class="widget label vmiddle" id="widgetw4A173A42701503367399148p" data-cid="w4A173A42701503367399148" data-link_cid="" style="width:20px;height:26px;left:307px;top:202px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:18.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:26px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>？</p>
  
</div><div class="widget label vmiddle" id="widgetwD2827BE02B1503367399156p" data-cid="wD2827BE02B1503367399156" data-link_cid="" style="width:191px;height:23px;left:92px;top:290px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:3;opacity:1;pointer-events:auto">
  <p>还剩1个名额，23:55:12后结束</p>
  
</div><div class="widget button vmiddle" id="widgetw59A72F7EA31503367399164p" data-cid="w59A72F7EA31503367399164" data-link_cid="" style="width:300px;height:32px;left:36px;top:350px;color:#ffffff;background-color:#ff9800;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:3;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">邀请好友一起组团领</span>
</p>
  
</div><div class="widget rounded_rect vmiddle" id="widgetw5B60F55FFA1503367459658p" data-cid="w5B60F55FFA1503367459658" data-link_cid="" style="width:375px;height:446px;left:0px;top:65px;background-color:#121212;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:1px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:0.45;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  
</div><div class="widget rounded_rect vmiddle clickable" id="widgetwAA61CA18391503367513071p" data-cid="wAA61CA18391503367513071" data-link_cid="l9F7DDF7FD01503383372396" style="width:375px;height:157px;left:0px;top:510px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:1px;border-style:solid;text-align:center;line-height:20px;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <div class="text" style="padding: 0px;"><p>&nbsp;</p></div>
  <div class="region gesture "></div>
</div><div class="widget button vmiddle clickable" id="widgetwD40F1F12191503367667945p" data-cid="wD40F1F12191503367667945" data-link_cid="l9F7DDF7FD01503383372396" style="width:375px;height:37px;left:0px;top:630px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;border-radius:4px;border-width:1px;border-style:solid;text-align:center;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <p>
  
  <span class="text">取消</span>
</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button clickable" id="widgetw7BC554A3BB1503367864208p" data-cid="w7BC554A3BB1503367864208" data-link_cid="l9F7DDF7FD01503383372396" style="width:45px;height:45px;left:33px;top:550px;color:#121212;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span class="icon mb icon-wechat-moment" style="font-size:24px;"></span>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw0EC9D6CD2E1503367905495p" data-cid="w0EC9D6CD2E1503367905495" data-link_cid="l9F7DDF7FD01503383372396" style="width:375px;height:40px;left:0px;top:510px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:18.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:26px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>分享</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw248EFF09DF1503367958770p" data-cid="w248EFF09DF1503367958770" data-link_cid="l9F7DDF7FD01503383372396" style="width:43px;height:23px;left:34px;top:590px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>朋友圈</p>
  <div class="region gesture "></div>
</div><div class="widget label vmiddle clickable" id="widgetw8DAA428F241503367979607p" data-cid="w8DAA428F241503367979607" data-link_cid="l9F7DDF7FD01503383372396" style="width:57px;height:23px;left:109px;top:590px;transform: rotate(0deg);-webkit-transform: rotate(0deg);font-size:14.0px;padding:0px;border-radius:0px;border-width:0px;border-style:solid;line-height:20px;font-weight:normal;font-style:normal;justify-content: center;align-items: center;z-index:5;opacity:1;pointer-events:auto">
  <p>微信好友</p>
  <div class="region gesture "></div>
</div><div class="widget icon_button clickable" id="widgetw25076752D21503368009591p" data-cid="w25076752D21503368009591" data-link_cid="l9F7DDF7FD01503383372396" style="width:45px;height:45px;left:116px;top:550px;transform: rotate(0deg);-webkit-transform: rotate(0deg);border-radius:0px;border-width:0px;border-style:solid;font-weight:normal;font-style:normal;z-index:5;opacity:1;pointer-events:auto">
  <span class="icon mb icon-wechat" style="font-size:28px;"></span>
  <div class="region gesture "></div>
</div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensE938D3340E1503367586368" class="pcanvas portrait" data-cid="sE938D3340E1503367586368" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensB77B0CDF061503367879023" class="pcanvas portrait" data-cid="sB77B0CDF061503367879023" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens714DBB61C51503368491335" class="pcanvas portrait" data-cid="s714DBB61C51503368491335" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens33E16DE4FB1503369957783" class="pcanvas portrait sb" data-cid="s33E16DE4FB1503369957783" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="e8623587-ef01-7e3b-1fca-24f3de7070b3">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens84DBFA00281503370082931" class="pcanvas portrait sb" data-cid="s84DBFA00281503370082931" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="61e8c901-5d97-626a-d3b3-e2338b645e8d">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens69CDF1B0711503373223749" class="pcanvas portrait" data-cid="s69CDF1B0711503373223749" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens4444D0897E1503374394565" class="pcanvas portrait" data-cid="s4444D0897E1503374394565" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensE626661C861503378761218" class="pcanvas portrait sb" data-cid="sE626661C861503378761218" data-orientation="portrait" style="display: none; transition: all 10ms ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="9ed091bf-6449-ba6a-1c21-9e0f0fa460a3">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensA2DEBDD4311503381786979" class="pcanvas portrait sb" data-cid="sA2DEBDD4311503381786979" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: none;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="c9cc5338-49d0-b3aa-6712-584d843a3d18">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensA67F1631CB1503383175937" class="pcanvas portrait" data-cid="sA67F1631CB1503383175937" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensD44CBC13421503383294200" class="pcanvas portrait" data-cid="sD44CBC13421503383294200" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensCF7BD8E7B41503383389624" class="pcanvas portrait sb" data-cid="sCF7BD8E7B41503383389624" data-orientation="portrait" style="display: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px); transition: all 0.2s ease-in-out;">
      <div class="widgets ps-container ps-theme-default" data-ps-id="7864315e-2a0e-afaa-2ee8-546186ff2b9f">
        <div class="scontainer" style="height: 667px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens32A58742561503385144911" class="pcanvas portrait" data-cid="s32A58742561503385144911" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens5130852B331503385277790" class="pcanvas portrait sb" data-cid="s5130852B331503385277790" data-orientation="portrait" style="display: none; transition: none; background-color: rgb(255, 255, 255); transform: translate(0px, 0px);">
      <div class="widgets ps-container ps-theme-default" data-ps-id="4a45b4be-4c5c-f4fb-2705-fb3c08303b72">
        <div class="scontainer" style="height: 984px;"><div class="sheader"></div><div class="sfooter"></div></div>
      <div class="ps-scrollbar-x-rail" style="left: 0px; bottom: 3px;"><div class="ps-scrollbar-x" tabindex="0" style="left: 0px; width: 0px;"></div></div><div class="ps-scrollbar-y-rail" style="top: 0px; right: 3px;"><div class="ps-scrollbar-y" tabindex="0" style="top: 0px; height: 0px;"></div></div></div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens6ECE16F6581503385454435" class="pcanvas portrait" data-cid="s6ECE16F6581503385454435" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreensC96148FD9C1503550927804" class="pcanvas portrait" data-cid="sC96148FD9C1503550927804" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    
      <div id="pscreens9358056B491505308984811" class="pcanvas portrait" data-cid="s9358056B491505308984811" data-orientation="portrait" style="display: none;">
      <div class="widgets">
        <div class="scontainer"><div class="sheader"></div><div class="sfooter"></div></div>
      </div>
      <div class="stickies"></div>
    </div>
    </div><div id="sticky-container" style="top: 0px; left: 0px; margin-top: 0px;"><div id="stickies"></div><div id="ui-comment-marker-panel"><!-- react-empty: 568 --></div></div></div>