<div class="hy_top">
  <div class="hy_header">
    <div class="margin_auto">
      <div class="posite">
        <div class="img">
          <a href="<?php echo $this->url('customer/info')?>">
              <img src="<?php echo $this->uploadUrl($this->locator->get('Profile')['customer_headimg'], 'user')?>" alt="" />
          </a>
        </div>
      </div>
      
      <div class="hy_top_tit">
        <h4><?php echo $this->locator->get('Profile')['username']?> <label style="color: <?php echo $levelColor[$this->locator->get('Profile')['level_id']]?>"><span><?php echo $this->locator->get('Profile')['level_name']?></span>
          <i class="iconfont">&#xe6db;</i></label></h4>
        <h5><span><i class="iconfont">&#xe6ce;</i>积分:<?php echo $this->locator->get('Profile')['customer_score']?></span></h5>
      </div>
    </div>
  </div>
  <a href="<?php echo $this->url('customer/check-in')?>">
      <div class="sign_in">
        <i class="iconfont">&#xe622;</i>
        <p><span>签到</span></p>
      </div>
  </a>  

  <a href="<?php echo $this->url('customer/info')?>">
      <div class="complete">
        <p>完善信息即可获得积分</p>
      </div>
  </a>
</div>
<div class="hy_dd weui-cells">
    <a class="weui-cell weui-cell_access" href="<?php echo $this->url('order/index')?>">
      <div class="weui-cell__bd">
        <p><i class="iconfont">&#xe604;</i>全部订单</p>
      </div>
      <div class="weui-cell__ft">
      </div>
    </a>
</div>
<div class="hy_nav weui-flex">
   <a class="weui-flex__item" href="<?php echo $this->url('order/index', array('status' => 'picke'))?>">
    <i class="iconfont" data-num="<?php echo $receiveNum?>">&#xe622;</i>
    <p>待领取</p>
   </a>
   <a class="weui-flex__item" href="<?php echo $this->url('order/index', array('status' => 'group'))?>">
    <i class="iconfont" data-num="<?php echo $groupNum?>">&#xe603;</i>
    <p>组团中</p>
   </a>
   <a class="weui-flex__item" href="<?php echo $this->url('order/index', array('status' => 'review'))?>">
    <i class="iconfont" data-num="<?php echo $reviewNum?>">&#xe61a;</i>
    <p>待评价</p>
   </a>
</div>
<div class="hs_border"></div>
<div class="hy_dd hy_ul weui-cells">
  <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/score')?>">
    <div class="weui-cell__bd">
      <p><i class="iconfont">&#xe634;</i>我的积分</p>
    </div>
    <div class="weui-cell__ft">
    </div>
  </a>
  <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/address')?>">
    <div class="weui-cell__bd">
      <p><i class="iconfont">&#xe616;</i>我的地址</p>
    </div>
    <div class="weui-cell__ft">
    </div>
  </a>
  <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/collection')?>">
    <div class="weui-cell__bd">
      <p><i class="iconfont">&#xe645;</i>我的收藏</p>
    </div>
    <div class="weui-cell__ft">
    </div>
  </a>
  <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/qrcode')?>">
    <div class="weui-cell__bd">
      <p><i class="iconfont">&#xe66e;</i>我的邀请码</p>
    </div>
    <div class="weui-cell__ft">
    </div>
  </a>
  <a class="weui-cell weui-cell_access" href="<?php echo $this->url('help/index')?>">
    <div class="weui-cell__bd">
      <p><i class="iconfont">&#xe607;</i>帮助中心</p>
    </div>
    <div class="weui-cell__ft">
    </div>
  </a>
</div>

<script type="text/javascript">
    $(function(){
        var color=["#50cab7","#977cdc","#ff8007","#5cbeec","#42bebc","#e54837"];
        $(".hy_ul .weui-cell").each(function(index){
            console.log(index)
            $(this).find(".iconfont").css("color",color[index])
        })

    })
</script>