<form method="post" enctype="multipart/form-data">
    <div class="mydata">
      <div class="weui-cells">
        <div class="weui-cell" >
            <div class="weui-cell__bd">
              <p>头像</p>
            </div>
            <div class="weui-cell__ft img openmk">
              <img id="sfzZ" src="<?php echo $this->uploadUrl($this->locator->get('Profile')['customer_headimg'], 'user')?>"/>
            </div>
            <div class="none">
                <input type="file" name="file" id="file"/>
            </div>
        </div>
        <div class="weui-cell weui-cell_access" >
           <div class="weui-cell__hd"><label class="weui-label">性别</label></div>
            <div class="weui-cell__bd">
               <input class="weui-input openmk" id="inline" type="text" value="<?php echo $info['customer_gender'] ?: ''?>" name="customer_gender" placeholder="未选择" style="color: #000;">
            </div>
            <div class="weui-cell__ft">
            </div>
            <div class="bg_wen <?php echo $info['customer_gender'] ? 'none' : ''?>">填写送10积分</div>
        </div>
        <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/city')?>">
           <div class="weui-cell__hd"><label class="weui-label">常驻地</label></div>
            <div class="weui-cell__bd">
                <?php if ($info['district_name']) : ?>
                    <h5 style="color: #000;"><?php echo $info['district_name']?></h5>
                <?php else : ?>
                    <h5>未选择</h5>
                <?php endif;?>
            </div>
            <div class="weui-cell__ft">
            </div>
            <div class="bg_wen <?php echo $info['district_name'] ? 'none' : ''?>">填写送10积分</div>
        </a>
        <div class="weui-cell weui-cell_access" >
           <div class="weui-cell__hd"><label class="weui-label">选择年龄段</label></div>
            <div class="weui-cell__bd">
               <input class="weui-input openmk" id="inline1" type="text" value="<?php echo $info['customer_age'] ?: ''?>" name="customer_age" placeholder="未选择" style="color: #000;">
            </div>
            <div class="weui-cell__ft">
            </div>
            <div class="bg_wen <?php echo $info['customer_age'] ? 'none' : ''?>">填写送10积分</div>
        </div>
        <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/phone')?>">
           <div class="weui-cell__hd"><label class="weui-label">绑定手机号</label></div>
            <div class="weui-cell__bd">
                <?php if ($info['customer_tel']) : ?>
                    <h5 style="color: #000;"><?php echo $info['customer_tel']?></h5>
                <?php else : ?>
                    <h5>未绑定</h5>
                <?php endif;?>
            </div>
            <div class="weui-cell__ft">
            </div>
            <div class="bg_wen <?php echo $info['customer_tel'] ? 'none' : ''?>">填写送10积分</div>
        </a>
      </div>

      <button class="feedback_tj" style="display: none;" type="submit">提交</button>
    </div>
</form>

<div class="mask"></div> 

<?php echo $this->js('ignore-history.js')->wrap();?>
<?php echo $this->js('LocalResizeIMG.js')->wrap();?>
<script type="text/javascript">
  
  $('.mydata .img.openmk').click(function() {
      $('#file').trigger('click');
  });

  $("input:file").unbind('change').on('change', function() {
      $('form').trigger('submit');
  });

  $("#inline").picker({
        title: "选择性别",
        cols: [
          {
            textAlign: 'center',
            values: ['男', '女',]
          }
        ],
        onChange: function(p, v, dv) {
            $(".mask").fadeIn();
        },
        onClose: function(p, v, d) {
          $(".mask").fadeOut();

          $('input[name="customer_gender"]').val(p.value[0]);
          $('form').trigger('submit');
        }
     });

  $("#inline1").picker({
        title: "选择年龄段",
        cols: [
          {
            textAlign: 'center',
            values: ['20岁以下', '20-35','35-50', '50岁以上']
          }
        ],
        onChange: function(p, v, dv) {
            $(".mask").fadeIn();
        },
        onClose: function(p, v, d) {
          $(".mask").fadeOut();
          $('input[name="customer_age"]').val(p.value[0]);
          $('form').trigger('submit');
        }
     });

  $('form').submit(function() {
      $(this).ajaxAuto({
        success: function (re) {
            if (re.status == 'ok') {
                setTimeout(function () {
                    window.location.reload();
                }, 1000);
            }
        }
      });
      return false;
  });
</script>