<div class="inv_code">  
  <div class="inv_code_t">
    <div class="code_mack"></div>
    <div class="inv_code_pro">
      <img id="js-qrcode" src="<?php echo $this->url('common/qrcode', array('key' => $this->funcs->encrypt($key, 'E', QRCODE_KEY)))?>"/>
      <p id="update-qrcode">刷新二维码</p>
    </div>
  </div>
  <div class="inv_code_d">
    <div class="code_tit">
      <span></span><b>活动说明</b><span></span>
    </div>
    <p><span></span>常按图片分享给好友</p>
    <p><span></span>成功邀请一名好友通过扫描你的专属二维码并完成白领或拼团，即可获得50积分</p>
    <p><span></span>邀请成功后积分直接发送到您的账户中</p>
    <p><span></span>该活动可重复参加，无次数上限</p>
    <h5>注意事项</h5>
    <p><span></span>邀请好友按人数统计，同一好友无论下单几次都只记录1次</p>
    <p><span></span>被邀请好友需为初次使用的新用户，老用户不算在内</p>
  </div>
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    wx.config(<?php echo $js->config(array('onMenuShareAppMessage'), false) ?>);
    wx.ready(function() {
        wx.onMenuShareAppMessage({
            title: '白领', // 分享标题
            desc: '', // 分享描述
            link: '<?php echo $key?>', // 分享链接，该链接域名或路径必须与当前页面对应的公众号JS安全域名一致
            imgUrl: '<?php echo $this->url('common/qrcode', array('key' => $this->funcs->encrypt($key, 'E', QRCODE_KEY)), '', true)?>', // 分享图标
            type: 'link', // 分享类型,music、video或link，不填默认为link
        });
    });

    $(function(){
    //  邀请码
      $(".inv_code_pro").height($(".inv_code_pro").width());
      $(".inv_code_pro").css("line-height",$(".inv_code_pro").width()+"px")
    });

    $('#update-qrcode').click(function() {
      $(this).ajaxAuto({
        success: function (re) {
          if (re.status == 'ok') {
            $('#js-qrcode').attr('src', re.data.src);
          }
        }
      });
    });
</script>