<!DOCTYPE html>
<html>
  <head>
    <title>我的积分</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">

    <meta name="description" content="Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
    ">

    <link rel="stylesheet" href="../weui.min.css">
    <link rel="stylesheet" href="../jquery-weui.css">
    <link rel="stylesheet" type="text/css" href="../common.css"/>
    <link rel="stylesheet" href="css/index.css">

  </head>

  <body ontouchstart>
  	<div class="current_t clearfix">
  		<div class="fl">
  			当前积分<b class="orange">500</b>
  		</div>
  		<a href="积分说明.html" class="fr"><i class="iconfont orange">&#xe68c;</i></a>
  	</div>
	<div class="jifen_tlt">
		<div class="clearfix title">
			<a href="我的积分.html" class="fl tlt_l on">
				积分获取记录
			</a>
			<a href="消耗积分.html" class="fr tlt_l">
				积分消费记录
			</a>
		</div>
	</div>
	<div class="jifen_m wrap">
		<div class="clearfix jifen_li">
			<div class="fl name">
				兑换抽奖机会
			</div>
			<div class="fl time">
				2017-08-22  02:22
			</div>
			<div class="fr tar num">
				-5000
			</div>
		</div>
		<div class="clearfix jifen_li">
			<div class="fl name">
				兑换商品
			</div>
			<div class="fl time">
				2017-08-22  02:22
			</div>
			<div class="fr tar num">
				-500
			</div>
		</div>
		<div class="clearfix jifen_li">
			<div class="fl name">
				兑换商品
			</div>
			<div class="fl time">
				2017-08-22  02:22
			</div>
			<div class="fr tar num">
				-500
			</div>
		</div>
		<div class="clearfix jifen_li">
			<div class="fl name">
				兑换商品
			</div>
			<div class="fl time">
				2017-08-22  02:22
			</div>
			<div class="fr tar num">
				-500
			</div>
		</div>
	</div>	


    <script src="../jquery-2.1.4.js"></script>
    <script src="../fastclick.js"></script>
    <script>
      $(function() {
        FastClick.attach(document.body);
      });
    </script>
    <script src="../jquery-weui.js"></script>
		<script src="js/index.js" type="text/javascript" charset="utf-8"></script>
  </body>

</html>
