	<div class="current_t clearfix">
		<div class="fl">
			当前积分<b class="orange"><?php echo $this->locator->get('Profile')['customer_score']?></b>
		</div>
		<a href="<?php echo $this->url('help/protocol', array('status' => 'jfsm'))?>" class="fr igonre-no"><i class="iconfont orange">&#xe68c;</i></a>
	</div>
<div class="jifen_tlt">
	<div class="clearfix title">
		<a href="<?php echo $this->url('customer/score', array('status' => 'have'))?>" class="fl tlt_l <?php echo $this->param('status') == 'have' ? 'on' : ''?>">
			积分获取记录
		</a>
		<a href="<?php echo $this->url('customer/score', array('status' => 'buy'))?>" class="fr tlt_l <?php echo $this->param('status') == 'buy' ? 'on' : ''?>">
			积分消费记录
		</a>
	</div>
</div>
<div class="jifen_m wrap" id="m_pro">
	<?php if ($scoreList) : ?>
		<?php foreach($scoreList as $row) : ?>
			<div class="clearfix jifen_li">
				<div class="fl name">
					<?php echo $row['score_des']?>
				</div>
				<div class="fl time">
					<?php echo $row['log_time']?>
				</div>
				<div class="fr tar num">
					<?php echo $row['score_type'] == 'buy' ? (0 - $row['score_quantity']) : $row['score_quantity']?>
				</div>
			</div>
		<?php endforeach;?>
	<?php else : ?>
		<div class="noproduct">
		  <p class="tac">
		    当前暂无<?php echo $this->param('status') == 'have' ? '获取' : '消费'?>记录噢
		  </p>
		</div>
	<?php endif;?>
</div>

<div class="mask"></div>

<div class="weui-loadmore none">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
</div>

<?php echo $this->js('ignore-history.js')->wrap();?>
<script type="text/javascript">
	var wh=$(window).height();
	var ww=$(window).width();
	$(".noproduct").height(wh-100);
	$(".noproduct").width(ww);

	var pageSize = 1;
	var loading = false;  //状态标记
	$(document.body).infinite().on("infinite", function() {
	    if (loading) {
	        return false;
	    } else {
	        $('.weui-loadmore').fadeIn();
	        loading = true;
	    }
	    
	    $(this).ajaxAuto({
	        data: {type: 'page', pageSize: pageSize},
	        success: function (re) {
	            var ali="";
	            if (re.status == 'ok') {
	                pageSize++;

	                $(re.data).each(function (key, row) {
	                    ali +='<div class="clearfix jifen_li"><div class="fl name">' + row.score_des + '</div><div class="fl time">' + row.log_time + '</div><div class="fr tar num">' + row.score_quantity + '</div></div>';
	                });
	            }

	            $("#m_pro").append(ali);
	            
	            $('.weui-loadmore').fadeOut();
	            loading = false;
	        }
	    });
	});
</script>