<div class="bread">
    <strong>
        <a href="<?php echo $this->url('shop/list')?>">商家列表</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-24">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label>商家名称<sup>*</sup></label>
                <input class="form-control" type="text" name="shop_name" value="<?= isset($info['shop_name']) ? $info['shop_name'] : '';?>">
            </div>
            <div class="form-group">
                <label>缩略图<sup>*</sup></label>
                <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF ) 70 * 70</p>
                <div style="display: <?php echo !isset($info['shop_headimg']) ? 'none' : ''?>; text-align: center;">
                    <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 70px; height: 70px;" src="<?php echo isset($info['shop_headimg']) && $info['shop_headimg'] ? $this->uploadUrl($info['shop_headimg'], 'shop') : ''?>">
                </div>
                
                <input class="form-control" type="file" name="file" value="">
            </div>
            <?php if (!$this->param('id')) : ?>
                <div class="form-group">
                    <label>后台登录用户名<sup>*</sup></label>
                    <input class="form-control" type="text" name="suser_name" value="">
                </div>
                <div class="form-group">
                    <label>后台登录密码<sup>*</sup></label>
                    <input class="form-control" type="text" name="suser_password" value="">
                </div>
            <?php endif;?>
            <div class="form-group">
                <label>所在城市<sup>*</sup></label>
                <select class="form-control" name="district_id" title="如没有要选的城市，请先开通该城市。">
                    <option value="">请选择</option>
                    <?php foreach($districtList as $key => $rows) : ?>
                        <optgroup label="<?php echo strtoupper($key)?>">
                            <?php foreach($rows as $row) : ?>
                                <option value="<?php echo $row['district_id']?>" <?php echo isset($info['district_id']) && $info['district_id'] == $row['district_id'] ? 'selected' : ''?>><?php echo $row['district_name']?></option>
                            <?php endforeach;?>
                        </optgroup>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>联系电话<sup>*</sup></label>
                <input class="form-control" type="text" name="shop_tel" value="<?= isset($info['shop_tel']) ? $info['shop_tel'] : '';?>">
            </div>
            <div class="form-group">
                <label>地址<sup>*</sup></label>
                <input class="form-control" type="text" name="shop_address" value="<?= isset($info['shop_address']) ? $info['shop_address'] : '';?>">
            </div>
            <div class="form-group">
                <label>经度<sup>*</sup></label><span style="display: inline-block; margin-left: 10px; color: #007DC6; cursor: pointer; text-decoration: underline;" id="js-map">地图选点</span>
                <input class="form-control" type="text" name="shop_lng" value="<?= isset($info['shop_lng']) ? sprintf("%.7f", $info['shop_lng']) : '';?>">
            </div>
            <div class="form-group">
                <label>纬度<sup>*</sup></label>
                <input class="form-control" type="text" name="shop_lat" value="<?= isset($info['shop_lat']) ? sprintf("%.7f", $info['shop_lat']) : '';?>">
            </div>
            <div class="form-group">
                <label>状态<sup>*</sup></label>
                <select class="form-control" name="shop_status">
                    <option value="1" <?= (isset($info['shop_status']) && $info['shop_status'] == 1) ? 'selected' : '' ?>>上线</option>
                    <option value="0" <?= (isset($info['shop_status']) && $info['shop_status'] == 0) ? 'selected' : '' ?>>下线</option>
                </select>
            </div>
            <div class="form-group">
                <label>特殊说明<sup></sup></label>
                <textarea class="form-control" placeholder="如无特殊说明可以为空。" name="shop_dec"><?= isset($info['shop_dec']) ? $info['shop_dec'] : '';?></textarea>
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>

<div id="js-upload-map">
    <div id="container" style="min-width:600px; min-height:400px;"></div>
</div>

<script charset="utf-8" src="http://map.qq.com/api/js?v=2.exp"></script>
<script type="text/javascript">
    $("form").submit(function(){
        $.check(!this.shop_name.value, '请输入商家名称', this.shop_name) &&
        $.check(!this.district_id.value, '请选择商家所在城市', this.district_id) &&
        $.check(!this.shop_tel.value, '请输入联系电话', this.shop_tel) &&
        $.check(!this.shop_address.value, '请输入地址', this.shop_address) &&
        $.check(!this.shop_lng.value, '请输入经度', this.shop_lng) &&
        $.check(!this.shop_lat.value, '请输入纬度', this.shop_lat) &&
        $(this).ajaxAuto();
        return false;
    });

    $("input:file").unbind('change').on('change', function() {
        var imageHolder = $(this).parents('.form-group').find('.js-image');
        if (typeof (FileReader) != "undefined") {
            var reader = new FileReader();
            reader.onload = function (e) {
               var result = e.target.result;
               imageHolder.attr('src', result);
           }
           var upFile = $(this)[0].files[0];
           reader.readAsDataURL(upFile);

           imageHolder.parent().show();
        }
    });

    $('#js-map').click(function(event) {
        var address = $('input[name="shop_address"]').val();
        $.check(!address, '请填写地址', $('input[name="shop_address"]')) &&
        $.popup(
            "#js-upload-map", 
            {overlay:{opacity: 0.4},title: '地图', dragable: true},
            function() { //onshow
                //定义map变量 调用 qq.maps.Map() 构造函数   获取地图显示容器
                 var map = new qq.maps.Map(document.getElementById("container"), {
                    zoom:13                                           
                });
                
                //调用地址解析类
                geocoder = new qq.maps.Geocoder();

                //通过getLocation();方法获取位置信息值
                geocoder.getLocation(address);

                //设置服务请求成功的回调函数
                geocoder.setComplete(function(result) {
                    map.panTo(result.detail.location);

                    var marker = new qq.maps.Marker({
                        position: result.detail.location,
                        draggable: true,
                        map: map
                    });

                    $('input[name="shop_lat"]').val(result.detail.location.lat);
                    $('input[name="shop_lng"]').val(result.detail.location.lng);

                    qq.maps.event.addListener(marker, 'mouseup', function(event) {
                        var latLng = event.latLng,
                            lat = latLng.getLat().toFixed(5),
                            lng = latLng.getLng().toFixed(5);
                        $('input[name="shop_lat"]').val(lat);
                        $('input[name="shop_lng"]').val(lng);
                    });
                });
            },
            function() { //onclose
            }
        );
    });
</script>




