<?php if ($prizeList) : ?>
	<div class="integral_task myprize">
		<div class="weui-cells" id="m_pro">
			<?php echo $this->render('task/chance-list-ajax', array('prizeList' => $prizeList))?> 
		</div>
	</div>
<?php else : ?>
	<div class="noproduct">
	  <p class="tac">
	    你还没有奖品噢，赶紧去抽奖吧
	  </p>
	</div>
<?php endif;?>

<div class="mask"></div>

<div class="weui-loadmore none">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
</div>

<script type="text/javascript">
	var wh=$(window).height();
	var ww=$(window).width();
	$(".noproduct").height(wh-50);
	$(".noproduct").width(ww);
	
	init();

	var pageSize = 1;
	var loading = false;  //状态标记
	$(document.body).infinite().on("infinite", function() {
	    if (loading) {
	        return false;
	    } else {
	        $('.weui-loadmore').fadeIn();
	        loading = true;
	    }
	    
	    $(this).ajaxAuto({
	        data: {type: 'page', pageSize: pageSize},
	        success: function (re) {
	            var ali="";
	            if (re.status == 'ok') {
	                pageSize++;

	                ali+= re.data.list;
	            }

	            $("#m_pro").append(ali);
	            init();
	            
	            $('.weui-loadmore').fadeOut();
	            loading = false;
	        }
	    });
	});

	function init() {
	    $('.js-address').click(function () {
	    	window.location.href = $(this).data('href');
	    });
	}
</script>