  	<div class="integral_task myprize">
  		<div class="weui-cells">
			  <a class="weui-cell weui-cell_access pr" href="">
			    <div class="weui-cell__hd img"><img src="images/integral_img.jpg"></div>
			    <div class="weui-cell__bd">
			      <h5 class="lr2">山东红富士苹果（两粒装）买一送一</h5>
			      <h6 class="mydate"><span>2017/10/21</span><span>16:54:34</span></h6>
			    </div>
			    <div class="mail_zt pa">
				  	<p class="on">预计7个工作日送达</p>
				</div>
			  </a>
			  
			  <a class="weui-cell weui-cell_access pr" href="../my/新建地址.html">
			    <div class="weui-cell__hd img"><img src="images/integral_img.jpg"></div>
			    <div class="weui-cell__bd">
			      <h5 class="lr2">山东红富士苹果（两粒装）买一送一</h5>
			      <h6 class="mydate"><span>2017/10/21</span><span>16:54:34</span></h6>
			    </div>
			    <div class="mail_zt pa">
				  	<p class="on">填写收货地址</p>
				</div>
			  </a>
			  
			  <a class="weui-cell weui-cell_access pr" href="">
			    <div class="weui-cell__hd img"><img src="images/integral_img.jpg"></div>
			    <div class="weui-cell__bd">
			      <h5 class="lr2">山东红富士苹果（两粒装）买一送一</h5>
			      <h6 class="mydate"><span>2017/10/21</span><span>16:54:34</span></h6>
			    </div>
			    <div class="mail_zt pa">
				  	<p>已入账</p>
				</div>
			  </a>
			  
			</div>
  		</div>
		<div class="myprize_ts">
			<p>地址填写成功，请等待配送</p>
		</div>