<div class="answer_xq">
	<div class="answer_wt">
		<?php echo $info['task_desc']?>
	</div>
	<div class="weui-cells answer_xz">
		<?php if ($info['data']) : ?>
			<?php foreach($info['data'] as $key => $row) : ?>
			  <div class="weui-cell js-row" data-type="<?php echo $row['question_type']?>" data-id="<?php echo $row['question_id']?>">
			    <div class="weui-cell__bd">
			      <h5><?php echo sprintf("%d.%s", $key + 1, $row['question_title'])?></h5>
					<p>
						<?php foreach($row['question'] as $ke => $value) : ?>
							<span data-key="<?php echo $ke;?>"><?php echo $value?></span>
						<?php endforeach;?>
					</p>
			    </div>
			  </div>
			<?php endforeach;?>
		<?php endif;?>
	</div>
</div>

<?php if ($questionCount >= $info['task_num']) : ?>
	<a class="twtj_btn answer_btn on" href="javascript:;">已参加</a>
<?php else : ?>
	<a class="twtj_btn answer_btn" id="js-submit" href="javascript:;">提交获积分</a>
<?php endif;?>

<div class="dialog">
	<h4>恭喜您，获得</h4>
	<h5><i class="iconfont">&#xe634;</i><?php echo $info['task_score']?>积分</h5>
	<p>积分已发送到您的账户中，请查收</p>
	<div class="weui-flex">
	  <div class="weui-flex__item dl_btn cancel">好的</div>
	  <div class="weui-flex__item dl_btn fxbtn">点击屏幕右上角分享</div>
	</div>
</div>
<div class="mask"></div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	wx.config(<?php echo $js->config(array('onMenuShareAppMessage'), false) ?>);
	wx.ready(function() {
	  wx.onMenuShareAppMessage(<?php echo json_encode($shareInfo)?>);
	});
	
	$(this).ready(function () {
		$('.answer_xq>p').each(function() {
			if ($(this).find('img') == undefind) {
				$('.answer_xq p').addClass('p');
			} else {
				$('.answer_xq p').addClass('img');
			}
		});
	});

	$(".answer_xz p span").click(function(){
		var type = $(this).parents('.js-row').data('type');
		if (type == 1) {
			$(this).addClass("on").siblings().removeClass("on");
		} else {
			$(this).toggleClass('on');
		}
	});

	var dltop=$(".dialog").height()/2;
	$(".dialog").css("margin-top",-dltop);

	$('#js-submit').click(function() {
		var $$ = $(this);
		var data = [];

		$('.js-row').each(function(key, value) {
			var row = [];
			var id = $(this).data('id');
			$(this).find('p span').each(function() {
				if ($(this).hasClass('on')) {
					row.push($(this).data('key'));
				}
			});
			data.push({id: id, data: row});
		});

		$$.removeAttr('href');

		$$.ajaxAuto({
			type: 'post',
			data: {data},
			success: function (re) {
				if (re.status == 'ok') {
					$(".dialog").fadeIn();
					$(".mask").fadeIn();
					$("body").css("overflow-y","hidden");
				}
			}
		});
	});

	$(".cancel, .fxbtn").click(function(){
		$(".dialog").fadeOut();
		$(".mask").fadeOut();
		$("body").css("overflow-y","auto");

		window.location.reload();
	})
</script>