<div class="answer_xq">
	<?php echo $info['task_desc']?>
	<div class="weui-cells answer_xz">
		<?php if ($info['data']) : ?>
			<?php foreach($info['data'] as $key => $row) : ?>
			  <div class="weui-cell">
			    <div class="weui-cell__bd">
			      <h5><?php echo sprintf("%d.%s", $key + 1, $row['question_title'])?></h5>
					<p>
						<?php foreach($row['question'] as $value) : ?>
							<span><?php echo $value?></span>
						<?php endforeach;?>
					</p>
			    </div>
			  </div>
			<?php endforeach;?>
		<?php endif;?>
	</div>
</div>
<a class="twtj_btn answer_btn" href="javascript:;">提交获积分</a>
<div class="dialog">
	<h4>恭喜您，获得</h4>
	<h5><i class="iconfont">&#xe634;</i>100积分</h5>
	<p>奖品已发送到您的账户中，请查收</p>
	<div class="weui-flex">
	  <div class="weui-flex__item dl_btn cancel">好的</div>
	  <div class="weui-flex__item dl_btn fxbtn">分享</div>
	</div>
</div>
<div class="mask"></div>

<script type="text/javascript">
	$(".answer_xz p span").click(function(){
		$(this).addClass("on").siblings().removeClass("on")
	})
	var dltop=$(".dialog").height()/2
	$(".dialog").css("margin-top",-dltop)
	$(".answer_btn").click(function(){
		$(".dialog").fadeIn()
		$(".mask").fadeIn()
		$("body").css("overflow-y","hidden")
	})
	$(".cancel").click(function(){
		$(".dialog").fadeOut()
		$(".mask").fadeOut()
		$("body").css("overflow-y","auto")
	})
</script>