<div class="read_xq">
	<?php echo $info['read_text']?>		
</div>

<?php if ($readCount >= $info['read_num']) : ?>
	<a class="twtj_btn read_btn on" href="javascript:;">已参加</a>
<?php else : ?>
	<a class="twtj_btn read_btn on" id="js-submit" href="javascript:;">提交换积分（<span id="time">5</span>）</a>
<?php endif;?>

<div class="dialog">
	<h4>恭喜您，获得</h4>
	<h5><i class="iconfont">&#xe634;</i><?php echo $info['read_score']?>积分</h5>
	<p>积分已发送到您的账户中，请查收</p>
	<div class="weui-flex">
	  <div class="weui-flex__item dl_btn cancel">好的</div>
	  <div class="weui-flex__item dl_btn fxbtn">点击屏幕右上角分享</div>
	</div>
</div>
<div class="mask"></div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	wx.config(<?php echo $js->config(array('onMenuShareAppMessage'), false) ?>);
	wx.ready(function() {
	  wx.onMenuShareAppMessage(<?php echo json_encode($shareInfo)?>);
	});
	
  $(this).ready(function () {
  	$('.read_xq p img').each(function () {
  		$(this).parent().addClass('img');
  	});
  });

  var dltop=$(".dialog").height()/2;
  $(".dialog").css("margin-top",-dltop);

  $('#js-submit').click(function() {
  	var $$ = $(this);

  	$$.removeAttr('href');

  	$$.ajaxAuto({
  		success: function (re) {
  			if (re.status == 'ok') {
  				$(".dialog").fadeIn();
  				$(".mask").fadeIn();
  				$("body").css("overflow-y","hidden");
  			}
  		}
  	});
  });

  $(".cancel, .fxbtn").click(function(){
  	$(".dialog").fadeOut();
  	$(".mask").fadeOut();
  	$("body").css("overflow-y","auto");

  	window.location.reload();
  });

  settime($('#time'));
  var countdown = 5; 
  function settime(val) {
    if (countdown == 0) { 
      $('#js-submit').html("提交换积分");
      val.removeClass('on');
      countdown = 5; 
    } else {
      val.html(countdown);
      val.addClass('on');
      countdown--;

      setTimeout(function() { 
        settime(val);
      }, 1000);
    }
  }
</script>