<div class="integral_task">
    <?php if ($list) : ?>
      <div class="weui-cells">
        <?php foreach($list as $row) : ?>
            <?php if ($row['type'] == 'read') : ?>
                <a class="weui-cell weui-cell_access" href="<?php echo $this->url('task/read', array('id' => $row['read_id']))?>">
                  <div class="weui-cell__hd img"><img src="<?php echo $this->uploadUrl($row['read_banner'], 'sys')?>"></div>
                  <div class="weui-cell__bd">
                    <h5 class="lr2"><?php echo $row['read_title']?></h5>
                    <p>+<?php echo $row['read_score']?>积分</p>
                  </div>
                  <div class="weui-cell__ft">
                  </div>
                </a>
            <?php else :?>
                <a class="weui-cell weui-cell_access" href="<?php echo $this->url('task/question', array('id' => $row['task_id']))?>">
                  <div class="weui-cell__hd img"><img src="<?php echo $this->uploadUrl($row['task_banner'], 'sys')?>"></div>
                  <div class="weui-cell__bd">
                    <h5 class="lr2"><?php echo $row['task_title']?></h5>
                    <p>+<?php echo $row['task_score']?>积分</p>
                  </div>
                  <div class="weui-cell__ft">
                  </div>
                </a>
            <?php endif;?>
        <?php endforeach;?>
      </div>
    <?php endif;?>
</div>