    <div class="integral_task">
      <div class="weui-cells">
        <a class="weui-cell weui-cell_access" href="阅读详情.html">
          <div class="weui-cell__hd img"><img src="images/integral_img.jpg"></div>
          <div class="weui-cell__bd">
            <h5 class="lr2">山东红富士苹果（两粒装）买一送一</h5>
            <p>+50积分</p>
          </div>
          <div class="weui-cell__ft">
          </div>
        </a>
        <a class="weui-cell weui-cell_access" href="答题详情.html">
          <div class="weui-cell__hd img"><img src="images/integral_img.jpg"></div>
          <div class="weui-cell__bd">
            <h5 class="lr2">山东红富士苹果（两粒装）买一送一</h5>
            <p>+50积分</p>
          </div>
          <div class="weui-cell__ft">
          </div>
        </a>
      </div>
    </div>