<div>还有<span id="chance-num"><?php echo (int) $config['chance_num']?></span>次抽奖机会</div>

<a id="js-chance" href="<?php echo $this->url('task/chance', array('turntable_use_score' => $config['turntable_use_score']))?>">
	<?php echo sprintf('使用%d积分兑换一次抽奖机会', $config['turntable_use_score'])?>
</a>

<div id="start">			
	<img src="<?php echo $this->image('turntable.png')?>">
</div>

<div><?php echo sprintf('当前您等级为%s，每天有%d次免费抽奖机会', $this->locator->get('Profile')['level_name'], $config['turntable_num'])?></div>

<?php echo $this->js('jquery.easing.min.js')->wrap();?>
<?php echo $this->js('jquery.rotate.js')->wrap();?>
<script type="text/javascript">
	$('#js-chance').click(function() {
		$(this).ajaxAuto();
		return false;
	});

	var effect = [
		$.easing.easeInOutBounce, $.easing.linear, $.easing.swing, $.easing.jswing, $.easing.easeInQuad, $.easing.easeOutQuad, 
		$.easing.easeInOutQuad, $.easing.easeInCubic, $.easing.easeOutCubic, $.easing.easeInOutCubic, $.easing.easeInQuart, 
		$.easing.easeOutQuart, $.easing.easeInOutQuint, $.easing.easeInSine, $.easing.easeOutSine, $.easing.easeInOutSine, 
		$.easing.easeInExpo, $.easing.easeOutExpo, $.easing.easeInOutExpo, $.easing.easeInCirc, $.easing.easeOutCirc, 
		$.easing.easeInOutCirc, $.easing.easeInElastic, $.easing.easeOutElastic, $.easing.easeInOutElastic, $.easing.easeInBack, 
		$.easing.easeOutBack, $.easing.easeInOutBack, $.easing.easeInBounce, $.easing.easeOutBounce
	];

	// console.log();

	$("#start").click(function() {
		var $$ = $(this);

		$$.rotate({
			bind:{
				click: function(){//绑定点击事件
					$$.unbind('click');

					$$.ajaxAuto({
						success: function (re) {
							if (re.status == 'ok') {
								var value = re.data;
								$$.rotate({
									duration: value.duration,//多少毫秒内完成转动
									angle: 0,//起始角度
									animateTo: value.n * 360 + value.angle,//一共转动多少角度
									easing: eval(effect[Math.floor(Math.random() * effect.length)]),//转动动画扩展
									callback: function() {//结束时的回调函数
										$('#chance-num').html($('#chance-num').text() - 1);
										$$.bind('click');

										console.log(value.message);
									}
								})
							}
						}
					});
				}
			}
		})
	});
</script>