<div class="dial">
	<div class="dial_top">
		<h4>
			<a href="<?php echo $this->url('task/chance-list')?>">我的奖品</a>
			<a href="<?php echo $this->url('help/protocol', array('status' => 'yxgz'))?>">游戏规则</a>
		</h4>
		<h5 style="display: block; margin-top: 60px;">机会已用完，去获取更多机会吧.</h5>
		<p>还有<span class="playnum" id="chance-num"><?php echo (int) $config['chance_num']?></span>次抽奖机会</p>
	</div>
	<div class="dial_ma">
		<div class="dial_zp">
			<img class="ljcj none start" src="<?php echo $this->image('dial_cj.png')?>" id="start"/>
			<canvas class="dial_zp_img" id="canvas" width="" height=""></canvas>
		</div>
	</div>
	<div class="dial_fo">
		<h5>
			<button class="jfdhcj">积分兑换抽奖机会</button>
			<button>分享增加抽奖机会</button>
		</h5>
		<p style="color: #ffffff;">
			<?php echo sprintf('当前您等级为%s，每天有%d次免费抽奖机会', $this->locator->get('Profile')['level_name'], $config['turntable_num'])?>
		</p>
	</div>
</div>

<div class="dialog">
	<div class="dialog_li dialog_zj jfjiang">
		<h4>恭喜您，获得</h4>
		<h5><i class="iconfont">&#xe634;</i>100积分</h5>
		<p>奖品已发送到您的账户中，请查收</p>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">好的</div>
		  <div class="weui-flex__item dl_btn">分享</div>
		</div>
	</div>
	<div class="dialog_li dialog_zj mdjiang">
		<h4>恭喜您，获得</h4>
		<h5>脉动一箱</h5>
		<p>预计7个工作日送达，请填写收货地址</p>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">稍后</div>
		  <a class="weui-flex__item dl_btn" href="../my/新建地址.html">立即填写</a>
		</div>
	</div>
	<div class="dialog_li dialog_dh nojiang">
		<h5>谢谢参与</h5>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">好的</div>
		  <div class="weui-flex__item dl_btn">再来一次</div>
		</div>
	</div>
	<div class="dialog_li dialog_dh dialog_ok">
		<h5>兑换成功，获得一次抽奖机会</h5>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn js-reload">好的</div>
		  <div class="weui-flex__item dl_btn" id="js-now">立即使用</div>
		</div>
	</div>
	<div class="dialog_li dialog_dh dialog_no">
		<h5>兑换失败，积分不够哦</h5>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">取消</div>
		  <div class="weui-flex__item dl_btn">
		  	<a href="<?php echo $this->url('task/score')?>" style="color: #ff7c00;">
		  		去赚取积分
		  	</a>
		  </div>
		</div>
	</div>
	<div class="dialog_li dialog_dh dialog_jf">
		<h5><?php echo sprintf('确定使用%d积分兑换一次抽奖机会', $config['turntable_use_score'])?></h5>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn qdjfdh" data-href="<?php echo $this->url('task/chance', array('turntable_use_score' => $config['turntable_use_score']))?>" id="js-chance">确定</div>
		  <div class="weui-flex__item dl_btn cancel">取消</div>
		</div>
	</div>
</div>

<div class="mask"></div>

<?php echo $this->js('jquery.easing.min.js')->wrap();?>
<?php echo $this->js('jquery.rotate.js')->wrap();?>
<script type="text/javascript">
	// //抽奖
	// $(function(){
	// 	var windowH=$(window).height();
		
	// 	$(".dial").height(windowH);
	// 	var ww=$(".ljcj").width()-13
	// 	var hh=$(".ljcj").height()-5
	// 	$(".ljcj").css("margin-left",-ww/2)
	// 	$(".ljcj").css("margin-top",-hh/2)
	// 	$(".ljcj").removeClass('none');

	// 	$(".jfdhcj").click(function(){
	// 		$(".dialog_jf").show().siblings().hide()
	// 		$(".dialog").fadeIn()
	// 		$(".mask").fadeIn()
	// 	})
	// 	$(".qdjfdh").click(function(){
			
	// 		var jfnum=1;
	// 		if(jfnum==1){
	// 			$(".dialog_ok").show().siblings().hide()
				
	// 		}else{
	// 			$(".dialog_no").show().siblings().hide()
	// 		}
	// 		 $(".dialog").fadeIn()
	// 		$(".mask").fadeIn()
	// 	})
	// 	$(".dial_top").height($(".dial_top").height())

	// var rotateFunc = function(awards,angle,text){  //awards:奖项，angle:奖项对应的角度
	//         $('.dial_zp_img').stopRotate();
	//         $(".dial_zp_img").rotate({
	//             angle:0, 
	//             duration: 5000, 
	//             animateTo: angle+1440, //angle是图片上各奖项对应的角度，1440是我要让指针旋转4圈。所以最后的结束的角度就是这样子^^
	//             callback:function(){
	// 				if(awards==3){
	// 					$(".jfjiang").show().siblings().hide()					
	// 				}
	// 				if(awards==2){
	// 					$(".mdjiang").show().siblings().hide()
	// 				}
	// 				if(awards==1){
	// 					$(".pgjiang").show().siblings().hide()
	// 				}
	// 				if(awards==0){
	// 					$(".nojiang").show().siblings().hide()
	// 				}
	//                 $(".dialog").fadeIn()
	// 				$(".mask").fadeIn()
	//             }
	//         }); 
	//     };
	// 	$(".ljcj").rotate({
	// 		bind:{
	// 			click:function(){
	// 				 var num = $(".playnum").html();
	// 	                if(num>0){
	// 	                	num--;
		                	
	// 	                    var data = [1,2,3,0]; //返回的数组
	// 	                        data = data[Math.floor(Math.random()*data.length)];
	// 	                    if(data==1){
	// 	                        rotateFunc(1,157,'苹果')
	// 	                    }
	// 	                    if(data==2){
	// 	                        rotateFunc(2,292,'脉动')
	// 	                    }
	// 	                    if(data==3){	                        
	// 	                        var angle = [22,112,202,337];
	// 	                            angle = angle[Math.floor(Math.random()*angle.length)]
	// 	                        	rotateFunc(3,angle,'100积分')
	// 	                    }
	// 	                    if(data==0){
	// 	                        var angle = [247,67];
	// 	                            angle = angle[Math.floor(Math.random()*angle.length)]
	// 	                        rotateFunc(0,angle,'谢谢参与')
	// 	                    }
	// 	                    $(".playnum").html(num)
	// 	                    if(num==0){	                    	 
	// 		                    $(".dial_top h5").fadeIn();
	// 	        				$(".dial_top p").fadeOut();
	// 	                    }	                   
	// 	                }
	// 			}
	// 		}
	// 	});

	// });
</script>

<script type="text/javascript">
	$(this).ready(function () {
		//初始化
		$(".dial_top").height($(".dial_top").height());
		<?php if ($config['chance_num']) : ?>
			$(".dial_top h5").fadeOut();
			$(".dial_top p").fadeIn();
		<?php else : ?>
			$(".dial_top h5").fadeIn();
			$(".dial_top p").fadeOut();
		<?php endif;?>

		var windowH = $(window).height();
		
		$(".dial").height(windowH);
		var ww = $(".ljcj").width() - 13;
		var hh = $(".ljcj").height() - 5;
		$(".ljcj").css({marginLeft: - ww / 2 + 'px', marginTop: - hh / 2 + 'px'}).removeClass('none');
		$(".dialog").css("margin-top", - windowH / 5);

		//积分兑换抽奖机会
		$(".jfdhcj").click(function(){
			$(".dialog_jf").show().siblings().hide();
			$(".dialog, .mask").fadeIn();
		});
		$('#js-chance').click(function() {
			$(this).ajaxAuto({
				success: function (re) {
					if (re.status == 'ok') {
						$(".dialog_ok").show().siblings().hide();
					} else {
						$(".dialog_no").find('h5').html(re.data.msg);
						$(".dialog_no").show().siblings().hide();
					}
				}
			});
			
			return false;
		});

		$('.cancel, .mask').click(function() {
			$(".dialog, .mask").fadeOut();
		});
		$('.js-reload').click(function() {
			window.location.reload();
		});
		
		//设置转盘
		var data = <?php echo json_encode($list)?>;
		var ctx = $('#canvas')[0].getContext('2d');
		var W = $('#canvas').width();

		$('#canvas').attr({width: W, height: W});

		var R = W / 2;
		
		ctx.beginPath(); 
		ctx.arc(R, R, R, 0, Math.PI * 2, true); 
		ctx.fillStyle = "#c54617"; 
		ctx.closePath(); 
		ctx.fill();

		ctx.beginPath(); 
		ctx.arc(R, R, R * 0.98, 0, Math.PI * 2, true); 
		ctx.fillStyle = "#8b2b21"; 
		ctx.closePath(); 
		ctx.fill();

		for(i=0; i<360/30; i++) {
			ctx.beginPath(); 
			ctx.arc((R + R * 0.9 * Math.cos(i * Math.PI / 6)), (R - R * 0.9 * Math.sin(i * Math.PI / 6)), R * 0.05, 0, Math.PI * 2, true); 
			ctx.fillStyle = "#FFFFFF"; 
			ctx.closePath(); 
			ctx.fill();
		}

		var grd = ctx.createLinearGradient(0, 0, R * 2, R * 2);
		ctx.beginPath(); 
		ctx.arc(R, R, R * 0.8, 0, Math.PI * 2, true);
		grd.addColorStop(0,"#aa4125");
		grd.addColorStop(1,"#f4d723");
		ctx.fillStyle = grd; 
		ctx.closePath(); 
		ctx.fill();

		ctx.beginPath(); 
		ctx.arc(R, R, R * 0.75, 0, Math.PI * 2, true); 
		ctx.fillStyle = "#ffffff"; 
		ctx.closePath(); 
		ctx.fill();

		var n = data.length;
		for(i=0; i < n; i++) {
			ctx.beginPath();
			if (!i) {
				ctx.translate(R, R); //水平的和垂直的偏移
			}
			
			ctx.moveTo(0, 0);
			ctx.arc(0, 0, R * 0.75, Math.PI * 2 / n * i, Math.PI * 2 / n * (i + 1), false);

			if (i % 2 == 0) {
				ctx.fillStyle = "#aa4125"; 
			} else {
				ctx.fillStyle = "#f4d723"; 
			}

			ctx.closePath(); 
			ctx.fill();

			//添加文字
			ctx.save();  
			ctx.beginPath();
			ctx.rotate(Math.PI * 2 / n / 2 + Math.PI * 2 / n * i);
			ctx.fillStyle = "#ffffff";  
			ctx.font = "14px 微软雅黑";  
			ctx.fillText(data[i].turntablep_title, R * 0.36 , 0);  
			ctx.restore();
		}

		//抽奖
		var effect = [
			$.easing.easeInOutBounce, $.easing.linear, $.easing.swing, $.easing.jswing, $.easing.easeInQuad, $.easing.easeOutQuad, 
			$.easing.easeInOutQuad, $.easing.easeInCubic, $.easing.easeOutCubic, $.easing.easeInOutCubic, $.easing.easeInQuart, 
			$.easing.easeOutQuart, $.easing.easeInOutQuint, $.easing.easeInSine, $.easing.easeOutSine, $.easing.easeInOutSine, 
			$.easing.easeInExpo, $.easing.easeOutExpo, $.easing.easeInOutExpo, $.easing.easeInCirc, $.easing.easeOutCirc, 
			$.easing.easeInOutCirc, $.easing.easeInElastic, $.easing.easeOutElastic, $.easing.easeInOutElastic, $.easing.easeInBack, 
			$.easing.easeOutBack, $.easing.easeInOutBack, $.easing.easeInBounce, $.easing.easeOutBounce
		];

		var $$ = $("#start");
		$$.rotate({
			bind:{
				click: function(){//绑定点击事件
					if (!$$.hasClass('start')) {
						return false;
					}

					$$.removeClass('start');

					$$.ajaxAuto({
						success: function (re) {
							if (re.status == 'ok') {
								var value = re.data;
								$$.rotate({
									duration: value.duration,//多少毫秒内完成转动
									angle: 0,//起始角度
									animateTo: value.n * 360 + value.angle,//一共转动多少角度
									easing: eval(effect[Math.floor(Math.random() * effect.length)]),//转动动画扩展
									callback: function() {//结束时的回调函数
										var num = $('#chance-num').text() - 1;
										$('#chance-num').html(num);
										if (!num) {
											$(".dial_top h5").fadeIn();
											$(".dial_top p").fadeOut();
										}
										
										$$.addClass('start');

										console.log(value);
									}
								})
							}
						}
					});
				}
			}
		});
	});
</script>