<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/district-list')?>">城市列表</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-12">
        <form method="post">
            <div class="form-group">
                <label>首字母<sup>*</sup></label>
                <input class="form-control" type="text" name="district_initial" value="<?= isset($districtInfo['district_initial']) ? $districtInfo['district_initial'] : '';?>">
            </div>
            <div class="form-group">
                <label>城市名<sup>*</sup></label>
                <input class="form-control" type="text" name="district_name" value="<?= isset($districtInfo['district_name']) ? $districtInfo['district_name'] : '';?>">
            </div>
            <div class="form-group">
                <label>开通状态<sup>*</sup></label>
                <select class="form-control" name="district_status">
                    <option value="1" <?= (isset($districtInfo['district_status']) && $districtInfo['district_status'] == 1) ? 'selected' : '' ?>>开通</option>
                    <option value="0" <?= (isset($districtInfo['district_status']) && $districtInfo['district_status'] == 0) ? 'selected' : '' ?>>关闭</option>
                </select>
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>
<script>
    $("form").submit(function() {
        $.check(!this.district_initial.value, '请输入首字母', this.district_initial) &&
        $.check(!this.district_name.value, '请输入城市名', this.district_name) &&
        $(this).ajaxAuto();
        return false;
    });
</script>


