<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/district-list')?>">基本信息设置</a> / 城市列表
    </strong>
</div>

<div id="search">
    <form>
        <div class="row">
            <div class="col-8">
                <div class="form-group">
                    <label>城市名</label>
                    <input class="form-control" type="text" name="district_name" size="20" value="<?= $this->param('district_name')?>">
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label>城市状态</label>
                    <select class="form-control" name="district_status">
                        <option value="">全部</option>
                        <option value="1" <?php echo $this->param('district_status') === '1' ? 'selected' : ''?>>开通</option>
                        <option value="0" <?php echo $this->param('district_status') === '0' ? 'selected' : ''?>>未开通</option>
                    </select>
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label class="hide"></label>
                    <div>
                        <button type="submit">搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="table-tool">
    <span id="fields-wrapper">
        <a class="btn" href="<?= $this->url('basic/district-edit')?>">
            <i class="fa fa-plus"></i> 添加新城市
        </a>
    </span>
</div>
<div class="table-responsive">
    <table class="table" id="data-list">
        <thead>
            <tr>
                <th class="text-center">首字母</th>
                <th class="text-center">城市名</th>
                <th class="text-center">城市状态</th>
                <th class="text-center">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($districtList) : ?>
                <?php foreach ($districtList as $key => $row) :?>
                    <tr class="<?php if (($key + 1) % 2 == 1) : ?>odd-narmal<?php endif;?>">
                        <td class="text-center"><?= strtoupper($row['district_initial'])?></td>
                        <td class="text-center"><?= $row['district_name']?></td>
                        <td class="text-center"><?= $row['district_status'] ? '已开通' : '未开通';?></td>
                        <td class="text-center action">
                            <a class="btn btn-xs edit" href="<?= $this->url('basic/district-edit', array('id' => $row['district_id']))?>" title="编辑">
                                <i class="fa fa-edit"></i>
                            </a>
                            <span class="btn btn-xs del" data-href="<?= $this->url('basic/district-del', array('id' => $row['district_id']))?>" title="删除">
                                <i class="fa fa-trash"></i>
                            </span>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<div id="paginator" class="row">
    <?= $this->render("includes/paginator"); ?>
</div>

<?php echo $this->js('jquery.autocomplete.js')->wrap();?>
<script>
    $('.action .del').click(function() {
        var $$ = $(this);

        $.confirm('请确认是否要删除？', function() {
            $$.ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.parents('tr').remove();
                    }
                }
            });
            return false;
        }, {
            title: '信息确认'
        });
    });

    var searchIpt = $("#search input[name='district_name']");
    searchIpt.autoComplete({
        minChars: 1,
        source: function(term, response){
            $.getJSON('<?php echo $this->url('basic/district-search');?>', { q: term }, function(data){
                if (typeof data.data != 'undefined') {
                    response(data.data);
                }
            });
        },
        onSelect: function(term, key){
            $('input[name="manager_id"]').val(key);
        }
    });
</script>