<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/image')?>">图片素材</a> / 列表
    </strong>
</div>

<div class="row top-tool">
    <div class="col-48">
        <span  class="btn" id="js-add-button">
                <i class="fa fa-plus"></i> 上传图片
        </span>
    </div>
</div>
<div class="row">
    <?php if ($imageList) : ?>
        <?php foreach($imageList as $key => $row):?>
        	<div class="col-8 col-x-12 col-xs-16 col-m-48 js-image">
                <div class="album-list">
                    <div class="pic-wrap">
                        <img src="<?php echo $this->uploadUrl($row['image_path'], 'sys');?>">
                    </div>
                    <div class="action">
                        <span class="time"><?php echo date('Y-m-d',strtotime($row['image_time']))?></span>
                        <span data-href="<?php echo $this->url('basic/del-image', array('id' => $row['image_id']))?>" class="delete js-ajax"><i class="fa fa-trash"></i></span>
                    </div>
                    <div>
                        <input type="text" value="<?php echo $row['image_src']?>" style="width: 100%;">
                    </div>
                </div>
        	</div>
        <?php endforeach;?>
    <?php endif;?>
</div>

<div id="js-upload-pic" class="none">
    <form id="upload-form" enctype="multipart/form-data" method="post" action="<?php echo $this->url('basic/image-update')?>">
        <input type="hidden" name="album_id" value="<?php echo $this->param('id')?>">
        <div class="album-pic-load">
            <input type="file" multiple="multiple" name="file[]" class="multi with-preview choose-flie" accept="gif|jpg|jpeg|png" value="" />
            <button><i class="icon-camera"></i> 选择图片</button>
            <p class="tip">( 图片类型: GIF, JPG, JPEG, PNG )</p>
        </div>
        <div class="clearfix">
        	<button class="pull-right" type="submit">提交</button>
        </div>
    </form>
</div>

<script type="text/javascript">
    $("#js-add-button").click(function(){
        $.popup(
            "#js-upload-pic", 
            {overlay:{opacity: 0.4},title: '上传图片', dragable: true}, 
            function () {},
            function () {
                $('#MultiFile1_list .MultiFile-remove').each(function(){
                    $(this).trigger('click');
                })
            }
        ); 
    });

    $('.js-ajax').click(function(){
         $$ = $(this);
         if ($$.hasClass('delete')) {
             $.confirm('请确认是否要删除？', function() {
                 $$.ajaxAuto({
                    success: function (re) {
                        if (re.status == 'ok') {
                            $$.parents('.js-image').remove();
                        }
                    }
                 });
             });
         } else {
             $$.ajaxAuto();
         }
    });

    $('.js-image input').focus(function() {
        $(this).select();
    });
</script>
