<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/home-recommend')?>">首页推荐</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-24">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label>标题<sup>*</sup></label>
                <input class="form-control" type="text" name="recommend_title" value="<?= isset($info['recommend_title']) ? $info['recommend_title'] : '';?>">
            </div>
            <div class="form-group">
                <label>图片<sup>*</sup></label>
                <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF )</p>
                <div style="display: <?php echo !isset($info['recommend_path']) ? 'none' : ''?>; text-align: center;">
                    <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 400px;" src="<?php echo isset($info['recommend_path']) && $info['recommend_path'] ? $this->uploadUrl($info['recommend_path'], 'sys') : ''?>">
                </div>
                
                <input class="form-control" type="file" name="recommend_path" value="">
            </div>
            <div class="form-group">
                <label>品牌Logo</label>
                <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF )</p>
                <div style="display: <?php echo !isset($info['recommend_logo']) ? 'none' : ''?>; text-align: center;">
                    <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 400px;" src="<?php echo isset($info['recommend_logo']) && $info['recommend_logo'] ? $this->uploadUrl($info['recommend_logo'], 'sys') : ''?>">
                </div>
                
                <input class="form-control" type="file" name="recommend_logo" value="">
            </div>
            <div class="form-group">
                <label>城市<sup>*</sup></label>
                <select class="form-control" name="district_id">
                    <?php foreach($districtList as $key => $value) : ?>
                        <option value="<?php echo $key?>" <?php echo isset($info['district_id']) && $info['district_id'] == $key ? 'selected' : ($this->param('district_id') == $key ? 'selected' : '')?>><?php echo $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>商品CODE</label>
                <input class="form-control" type="text" name="product_code" value="<?= isset($info['product_code']) ? $info['product_code'] : '';?>">
            </div>
            <div class="form-group">
                <label>排序</label>
                <input class="form-control" type="number" name="recommend_sort" value="<?= isset($info['recommend_sort']) ? $info['recommend_sort'] : '';?>">
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("form").submit(function() {
        $.check(!this.recommend_title.value, '请输入标题', this.recommend_title) &&
        $.check(!this.district_id.value, '请选择城市', this.district_id) &&
        $(this).ajaxAuto();
        return false;
    });

    $("input:file").unbind('change').on('change', function() {
        var imageHolder = $(this).parents('.form-group').find('.js-image');
        if (typeof (FileReader) != "undefined") {
            var reader = new FileReader();
            reader.onload = function (e) {
               var result = e.target.result;
               imageHolder.attr('src', result);
           }
           var upFile = $(this)[0].files[0];
           reader.readAsDataURL(upFile);

           imageHolder.parent().show();
        }
    });
</script>


