<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/district-list')?>">基本信息设置</a> / 首页推荐
    </strong>
</div>

<div id="search">
    <form>
        <div class="row">
            <div class="col-8">
                <div class="form-group">
                    <label>城市</label>
                    <select class="form-control" name="district_id">
                        <?php foreach($districtList as $key => $value) : ?>
                            <option value="<?php echo $key?>" <?php echo $this->param('district_id') == $key ? 'selected' : ''?>><?php echo $value?></option>
                        <?php endforeach;?>
                    </select>
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label class="hide"></label>
                    <div>
                        <button type="submit">搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<div class="row top-tool">
    <div class="col-48" style="text-align: right;">
        <a class="btn" href="<?php echo $this->url('basic/home-recommend-edit', array('district_id' => $this->param('district_id')))?>">
            <i class="fa fa-plus"></i> 添加
        </a>
    </div>
</div>
<div class="row">
    <?php if ($imageList) : ?>
        <ul class="sortable">
            <?php foreach($imageList as $key => $row):?>
                <li class="col-8 col-x-12 col-xs-16 col-m-48 js-image" data-id="<?php echo $row['recommend_id']?>", data-sort="<?php echo $row['image_sort']?>">
                    <div class="album-list">
                        <div class="pic-wrap">
                            <img src="<?php echo $this->uploadUrl($row['recommend_path'], 'sys');?>">
                        </div>
                        <div class="action">
                            <span class="time"><?php echo date('Y-m-d',strtotime($row['recommend_time']))?></span>
                            <a class="edit" href="<?php echo $this->url('basic/home-recommend-edit', array('id' => $row['recommend_id']))?>">
                                <i class="fa fa-edit"></i>
                            </a>
                            <span data-href="<?php echo $this->url('basic/del-recommend', array('id' => $row['recommend_id']))?>" class="delete js-ajax"><i class="fa fa-trash"></i></span>
                        </div>
                        <div style="text-align: center;">
                            <?php echo $row['recommend_title']?>
                        </div>
                    </div>
                </li>
            <?php endforeach;?>
        </ul>
    <?php endif;?>
</div>

<?= $this->js('jquery-ui.js')->wrap();?>
<?= $this->js('sortable.js')->wrap();?>
<script type="text/javascript">
    $('.sortable').each(function () {
        $(this).sortImg({
            axis: false,
            url: '<?= $this->url('basic/set-recommend-sort')?>',
        });
    });

    $('.js-ajax').click(function(){
         $$ = $(this);
         if ($$.hasClass('delete')) {
             $.confirm('请确认是否要删除？', function() {
                 $$.ajaxAuto({
                    success: function (re) {
                        if (re.status == 'ok') {
                            $$.parents('.js-image').remove();
                        }
                    }
                 });
             });
         } else {
             $$.ajaxAuto();
         }
    });
</script>
