<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/home-image')?>">首页焦点图</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-24">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label>标题</label>
                <input class="form-control" type="text" name="image_title" value="<?= isset($info['image_title']) ? $info['image_title'] : '';?>">
            </div>
            <div class="form-group">
                <label>图片<sup>*</sup></label>
                <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF ) 750 * 540</p>
                <div style="display: <?php echo !isset($info['image_path']) ? 'none' : ''?>; text-align: center;">
                    <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 150px; height: 108px;" src="<?php echo isset($info['image_path']) && $info['image_path'] ? $this->uploadUrl($info['image_path'], 'sys') : ''?>">
                </div>
                
                <input class="form-control" type="file" name="file" value="">
            </div>
            <div class="form-group">
                <label>城市<sup>*</sup></label>
                <select class="form-control" name="district_id">
                    <?php foreach($districtList as $key => $rows) : ?>
                        <optgroup label="<?php echo strtoupper($key)?>">
                            <?php foreach($rows as $row) : ?>
                                <option value="<?php echo $row['district_id']?>" <?php echo $this->param('district_id') == $row['district_id'] ? 'selected' : ''?>><?php echo $row['district_name']?></option>
                            <?php endforeach;?>
                        </optgroup>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>图片链接或商品CODE</label>
                <input class="form-control" type="text" name="image_href" value="<?= isset($info['image_href']) ? $info['image_href'] : '';?>">
            </div>
            <div class="form-group">
                <label>排序</label>
                <input class="form-control" type="number" name="image_sort" value="<?= isset($info['image_sort']) ? $info['image_sort'] : '';?>">
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("form").submit(function() {
        $.check(!this.district_id.value, '请选择城市', this.district_id) &&
        $(this).ajaxAuto();
        return false;
    });

    $("input:file").unbind('change').on('change', function() {
        var imageHolder = $(this).parents('.form-group').find('.js-image');
        if (typeof (FileReader) != "undefined") {
            var reader = new FileReader();
            reader.onload = function (e) {
               var result = e.target.result;
               imageHolder.attr('src', result);
           }
           var upFile = $(this)[0].files[0];
           reader.readAsDataURL(upFile);

           imageHolder.parent().show();
        }
    });
</script>


