<div class="bread">
    <strong>
        <a href="<?php echo $this->url('basic/home-recommend')?>">首页推荐</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-12">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label>标题<sup>*</sup></label>
                <input class="form-control" type="text" name="recommend_title" value="<?= isset($info['recommend_title']) ? $info['recommend_title'] : '';?>">
            </div>
            <div class="form-group">
                <label>城市<sup>*</sup></label>
                <select class="form-control" name="district_id">
                    <?php foreach($districtList as $key => $rows) : ?>
                        <optgroup label="<?php echo strtoupper($key)?>">
                            <?php foreach($rows as $row) : ?>
                                <option value="<?php echo $row['district_id']?>" <?php echo $this->param('district_id') == $row['district_id'] ? 'selected' : ''?>><?php echo $row['district_name']?></option>
                            <?php endforeach;?>
                        </optgroup>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>商品CODE<sup>*</sup></label>
                <input class="form-control" type="text" name="product_code" value="<?= isset($info['product_code']) ? $info['product_code'] : '';?>">
            </div>
            <div class="form-group">
                <label>排序</label>
                <input class="form-control" type="number" name="recommend_sort" value="<?= isset($info['recommend_sort']) ? $info['recommend_sort'] : '';?>">
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>

<script type="text/javascript">
    $("form").submit(function() {
        $.check(!this.recommend_title.value, '请输入标题', this.recommend_title) &&
        $.check(!this.district_id.value, '请选择城市', this.district_id) &&
        $.check(!this.product_code.value, '请输入商品CODE', this.product_code) &&
        $(this).ajaxAuto();
        return false;
    });
</script>


