<div class="weui-search-bar" id="searchBar">
  <form class="weui-search-bar__form">
    <div class="weui-search-bar__box">
      <i class="weui-icon-search"></i>
      <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入地址匹配周边的取货点" required="" name="address_name">
      <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
    </div>
    <label class="weui-search-bar__label" id="searchText">
      <i class="weui-icon-search"></i>
      <span>输入地址匹配周边的取货点</span>
    </label>
  </form>
  <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>
<div class="qhd_top">
    <h5>当前位置</h5>
    <p id="js-address"><?php echo $formattedAddress?></p>
    <div class="qhd_gx">
        <i class="iconfont">&#xe612;</i>
    </div>
</div>
<div class="qhd_down">
    <h6>附近取货点</h6>
    <?php if ($shopList) : ?>
        <?php foreach($shopList as $row) : ?>
            <div class="qhd_item js-row" data-href="<?php echo $this->url('order/self-address', array('order_id' => $this->param('order_id'), 'quantity_id' => $row['quantity_id']))?>">
                <div class="qhd_item_l">
                    <h5><?php echo $row['shop_name']?></h5>
                    <p><?php echo $row['shop_address']?></p>
                </div>
                <div class="qhd_item_r">
                    <i class="iconfont">&#xe636;</i>
                    <p><?php echo $this->funcs->setLength($row['distance'])?></p>
                    <p>库存:<?php echo $row['quantity_num']?></p>
                </div>
            </div>
        <?php endforeach;?>
    <?php endif;?>
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    wx.config(<?php echo $js->config(array('getLocation'), true) ?>);
    wx.ready(function() {
        $('.qhd_gx').click(function() {
            wx.getLocation({
                type: 'wgs84', // 默认为wgs84的gps坐标，如果要返回直接给openLocation用的火星坐标，可传入'gcj02'
                success: function (res) {
                    $(this).ajaxAuto({
                        data: {lat: res.latitude, lng: res.longitude},
                        success: function (re) {
                            if (re.status == 'ok') {
                                $('#js-address').html(re.data.address);
                            }
                        }
                    });
                },
            });
        });
    });

    $('.js-row').click(function() {
        $(this).ajaxAuto();
    });

    $('input[type="search"]').blur(function() {
        if ($(this).val()) {
            window.location.href = '<?php echo $this->url('shop/search', array('order_id' => $this->param('order_id')))?>&address_name=' + $(this).val();
        }
    });
</script>     