<div class="weui-search-bar" id="searchBar">
  <form class="weui-search-bar__form">
    <div class="weui-search-bar__box">
      <i class="weui-icon-search"></i>
      <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入地址匹配周边的取货点" required="">
      <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
    </div>
    <label class="weui-search-bar__label" id="searchText">
      <i class="weui-icon-search"></i>
      <span>输入地址匹配周边的取货点</span>
    </label>
  </form>
  <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>  
<div class="qhd_top">
    <h5>当前位置</h5>
    <p>上海市宝山区沪太路3100号</p>
    <div class="qhd_gx">
        <i class="iconfont">&#xe612;</i>
    </div>
</div>
<div class="qhd_down">
    <h6>附近取货点</h6>
    <div class="qhd_item">
        <div class="qhd_item_l">
            <h5>呼玛小区服务点</h5>
            <p>上海市宝山区呼兰路725号</p>
        </div>
        <div class="qhd_item_r">
            <i class="iconfont">&#xe636;</i>
            <p>0.56km</p>
            <p>库存:30</p>
        </div>
    </div>
    <div class="qhd_item">
        <div class="qhd_item_l">
            <h5>呼玛小区服务点</h5>
            <p>上海市宝山区呼兰路725号</p>
        </div>
        <div class="qhd_item_r">
            <i class="iconfont">&#xe636;</i>
            <p>0.56km</p>
            <p>库存:30</p>
        </div>
    </div>
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
    wx.config(<?php echo $js->config(array('getLocation'), false) ?>);
    wx.ready(function() {
        wx.getLocation({
            type: 'wgs84', // 默认为wgs84的gps坐标，如果要返回直接给openLocation用的火星坐标，可传入'gcj02'
            success: function (res) {
                console.log(res);
            }
        });
    });
</script>             