<form method="post">
	<input type="text" name="suser_name" value="" placeholder="用户名" />
	<input type="password" name="suser_password" value="" placeholder="密码" />

	<input type="hidden" name="redirect" value="<?php echo $this->param('redirect')?>" />
	<button type="submit">登录</button>
</form>

<script type="text/javascript">
	$('form').submit(function() {
		var $$ = $(this);

		$.check(!this.suser_name.value, '请输入用户名') &&
		$.check(!this.suser_password.value, '请输入密码') &&
		$$.ajaxAuto();
		return false;
	});
</script>