<div id="container"></div>
<script charset="utf-8" src="http://map.qq.com/api/js?v=2.exp"></script>
<script type="text/javascript">
	var data = <?php echo json_encode($data)?>;
	$('#container').css({width: window.screen.availWidth + 'px', height: window.screen.availHeight + 'px'});

	//定义map变量 调用 qq.maps.Map() 构造函数   获取地图显示容器
	var map = new qq.maps.Map(document.getElementById('container'), {
		zoomLevel:13
	});
	drivingService = new qq.maps.DrivingService({
		map : map
	});

	drivingService.search(new qq.maps.LatLng(data.from.lat, data.from.lng), new qq.maps.LatLng(data.to.lat, data.to.lng));
</script>