<div class="weui-search-bar" id="searchBar">
  <form class="weui-search-bar__form">
    <div class="weui-search-bar__box">
      <i class="weui-icon-search"></i>
      <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="输入地址匹配周边的取货点" required="" name="address_name" value="<?php echo $this->param('address_name')?>">
      <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>
    </div>
    <label class="weui-search-bar__label" id="searchText">
      <i class="weui-icon-search"></i>
      <span>输入地址匹配周边的取货点</span>
    </label>

    <input type="hidden" name="order_id" value="<?php echo $this->param('order_id')?>">
    <input type="hidden" name="shop_lat" value="">
    <input type="hidden" name="shop_lng" value="">
  </form>
  <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>
</div>  
<div class="qhd_down qhd_radio">
    <?php if ($shopList) : ?>
        <?php foreach($shopList as $row) : ?>
            <div class="qhd_item js-row" data-href="<?php echo $this->url('order/self-address', array('order_id' => $this->param('order_id'), 'quantity_id' => $row['quantity_id']))?>" data-lat="<?php echo $row['shop_lat']?>" data-lng="<?php echo $row['shop_lng']?>">
                <div class="qhd_ico">
                    <i class="iconfont">&#xe608;</i>
                    <i class="iconfont">&#xe60c;</i>
                </div>
                <div class="qhd_item_l">
                    <h5><?php echo $row['shop_name']?></h5>
                    <p><?php echo $row['shop_address']?></p>
                </div>
                <div class="qhd_item_r">
                    <i class="iconfont">&#xe636;</i>
                    <p><?php echo $this->funcs->setLength($row['distance'])?></p>
                    <p>库存:<?php echo $row['quantity_num']?></p>
                </div>
            </div>
        <?php endforeach;?>
    <?php endif;?>
</div>

<div class="none" id="js-form" data-lat="<?php echo $form['lat']?>" data-lng="<?php echo $form['lng']?>"></div>

<?php if (!$shopList) : ?>
    <div class="noproduct">
      <p class="tac">
        附近暂无取货点
      </p>
    </div>
<?php endif;?>

<script charset="utf-8" src="http://map.qq.com/api/js?v=2.exp"></script>
<script type="text/javascript">
    var wh=$(window).height();
    var ww=$(window).width();
    $(".noproduct").height(wh-150);
    $(".noproduct").width(ww);

    <?php if ($this->param('address_name')) : ?>
        var address = "<?php echo $this->param('address_name')?>";
        //调用地址解析类
        geocoder = new qq.maps.Geocoder();

        //通过getLocation();方法获取位置信息值
        geocoder.getLocation(address);

        //设置服务请求成功的回调函数
        geocoder.setComplete(function(result) {
            $('input[name="shop_lat"]').val(result.detail.location.lat);
            $('input[name="shop_lng"]').val(result.detail.location.lng);

            $('#searchText').trigger('click');
            $('input[type="search"]').trigger('blur');
        });
    <?php endif;?>
    $('input[type="search"]').change(function() {
        if ($(this).val()) {
            //调用地址解析类
            geocoder = new qq.maps.Geocoder();

            //通过getLocation();方法获取位置信息值
            geocoder.getLocation($(this).val());

            //设置服务请求成功的回调函数
            geocoder.setComplete(function(result) {
                $('input[name="shop_lat"]').val(result.detail.location.lat);
                $('input[name="shop_lng"]').val(result.detail.location.lng);
                $('form').trigger('submit');
            });
        } else {
            $('form').trigger('submit');
        } 
    });
    $('input[type="search"]').blur(function() {
        if ($(this).val()) {
            //调用地址解析类
            geocoder = new qq.maps.Geocoder();

            //通过getLocation();方法获取位置信息值
            geocoder.getLocation($(this).val());

            //设置服务请求成功的回调函数
            geocoder.setComplete(function(result) {
                $('input[name="shop_lat"]').val(result.detail.location.lat);
                $('input[name="shop_lng"]').val(result.detail.location.lng);
                $('form').trigger('submit');
            });
        } else {
            window.location.href = '<?php echo $this->url('shop/index', array('order_id' => $this->param('order_id')))?>';
        }
    });

    $('.qhd_ico').click(function() {
        $('.qhd_ico').removeClass('on');
        $(this).addClass('on');
    });

    var map = '<?php echo $this->url('shop/map')?>';
    $('.js-row').click(function() {
        var formLat = $('#js-form').data('lat'),
            formLng = $('#js-form').data('lng'),
            toLat = $(this).data('lat'),
            toLng = $(this).data('lng');
        window.location.href = map + '?form-lat=' + formLat + '&form-lng=' + formLng + '&to-lat=' + toLat + '&to-lng=' + toLng;
        // $(this).ajaxAuto();
    });
</script>