<div class="shoper_t">
	<h3>商家主页</h3>
	<a class="sz" href="<?php echo $this->url('shop-admin/set-up')?>"><i class="iconfont">&#xe61c;</i></a>
	<a class="sm" href="javascript:void(0);"><i class="iconfont">&#xe637;</i></a>
</div>

<div class="shop_tlt clearfix">
	<div class="fl sj_l">
	  <div class="info tac">
	    <i class="iconfont">&#xe658;</i>
	    <p>商家名称</p>
	  </div>
	</div>
	<div class="fl sj_m">
	  <div class="info">
	    <p class="lr1"><?php echo $shopInfo['shop_name']?></p>
	    <p class="lr2">地址：<?php echo $shopInfo['shop_address']?></p>
	  </div>
	</div>
	<div class="fr sj_l">
		<a href="<?php echo $this->url('shop-admin/product-list')?>">
			<div class="info tac">
			  <i class="iconfont">&#xe995;</i>
			  <p>商品管理</p>
			</div>
		</a>
	</div>
</div>

<div class="gray_bg"></div>

<div class="sh_jlt clearfix">
	<div class="fl inl tac">
	  <p>近30天派送</p>
	  <h4><?php echo $count_30?></h4>
	</div>
	<div class="fl inl inm tac">
	  <p>近7天派送</p>
	  <h4><?php echo $count_7?></h4>
	</div>
	<div class="fr inl tac">
	  <p>昨日派送</p>
	  <h4><?php echo $count_1?></h4>
	</div>
</div>

<div class="weui-cells lqjl">
	<a href="<?php echo $this->url('shop-admin/list')?>" class="weui-cell">
	  <div class="weui-cell__bd">
	    <p>领用记录</p>
	  </div>
	  <div class="weui-cell__ft">更多数据>></div>
	</a>
</div>
<div class="lq_main">
	<div class="weui-flex wrap ltt_ul border_bt">
	  <div class="weui-flex__item lqw_30 tac">
	    <p>商品名称</p>
	  </div>
	  <div class="weui-flex__item lqw_30 tac">
	    <p>领取会员名称</p>
	  </div>
	  <div class="weui-flex__item tac">
	    <p>领取时间</p>
	  </div>
	</div>

	<?php if ($list) : ?>
		<?php foreach($list as $row) : ?>
			<div class="weui-flex wrap ltt_li border_bt">
			  <div class="weui-flex__item tac">
			    <p><?php echo $row['product_name']?></p>
			  </div>
			  <div class="weui-flex__item tac">
			    <p><?php echo $row['customer_name']?></p>
			  </div>
			  <div class="weui-flex__item tac">
			    <p><?php echo date("Y.m.d H:i:s", strtotime($row['order_time']))?></p>
			  </div>
			</div>
		<?php endforeach;?>
	<?php endif;?>
</div>

<div class="leave_lq">
	<a href="<?php echo $this->url('shop-admin/logout')?>" class="weui-btn weui-btn_primary">退出登录</a>
</div>

<div class="mask"></div>

<div class="dialog">
	<div class="dialog_li item01">
		<h4></h4>
		<div class="hint_ma">
			<div class="img">
				<img src=""/>
			</div>
		</div>			
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">取消</div>
		  <div class="weui-flex__item dl_btn fxbtn" id="js-ship" data-href="">确认派送</div>
		</div>
	</div>
	<div class="dialog_li item02">
		<h4>系统提示</h4>
		<div class="hint_ma">
			<p>您已经领取过该商品无法派送</p>
		</div>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">确认</div>
		</div>
	</div>
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	var ww = $(window).width();
	$(".shop_tlt .sj_m").width(ww - 182);

	wx.config(<?php echo $js->config(array('scanQRCode'), false) ?>);
	wx.ready(function() {
		$('.sm').click(function() {
			wx.scanQRCode({
			    needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
			    scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
			    success: function (res) {
			    	$(this).ajaxAuto({
			    		url: '<?php echo $this->url('shop-admin/self')?>',
			    		type: 'post',
			    		data: {key: res.resultStr},
			    		success: function (re) {
			    			if (re.status == 'ok') {
			    				$('.item01 .img img').attr({src: re.data.src});
			    				$('.item01 h4').html(re.data.name);
			    				$('#js-ship').data('href', re.data.href);

			    				$(".item01").show().siblings().hide();
			    				$(".dialog").fadeIn();
			    				$(".mask").fadeIn();
			    			} else {
			    				$('.item02 .hint_ma p').html(re.data.msg);
			    				$(".item02").show().siblings().hide();
			    				$(".dialog").fadeIn();
			    				$(".mask").fadeIn();
			    				return false;
			    			}
			    		}
			    	});
				}
			});
		});
	});

	$('.cancel').click(function() {
		self.location = document.referrer;
	});

	//发货
	$('#js-ship').click(function() {
		var $$ = $(this);

		$$.ajaxAuto();
		return false;
	});
</script>