<form method="post">
	<input type="password" name="suser_password_old" value="" placeholder="输入原始密码" />
	<input type="password" name="suser_password" value="" placeholder="输入新密码" />
	<input type="password" name="suser_password_r" value="" placeholder="确认新密码" />

	<button type="submit">确认</button>
</form>

<script type="text/javascript">
	$('form').submit(function() {
		var $$ = $(this);

		$.check(!this.suser_password_old.value, '输入原始密码') &&
		$.check(!this.suser_password.value, '输入新密码') &&
		$.check(!this.suser_password_r.value, '确认新密码') &&
		$.check(this.suser_password.value != this.suser_password_r.value, '两次密码不一样') &&
		$$.ajaxAuto();
		return false;
	});
</script>