<form method="post">
	<div class="setpass">
		<div class="weui-cells">
		  <div class="weui-cell">
		    <div class="weui-cell__hd"><i class="iconfont">&#xe6a7;</i></div>
		    <div class="weui-cell__bd">
		      <input type="password" name="suser_password_old" value="" placeholder="输入原始密码"/>
		    </div>
		  </div>
		  <div class="weui-cell">
		    <div class="weui-cell__hd"><i class="iconfont">&#xe6a7;</i></div>
		    <div class="weui-cell__bd">
		      <input type="password" name="suser_password" value="" placeholder="输入新密码"/>
		    </div>
		  </div>
		  <div class="weui-cell">
		    <div class="weui-cell__hd"><i class="iconfont">&#xe6a7;</i></div>
		    <div class="weui-cell__bd">
		      <input type="password" name="suser_password_r" value="" placeholder="确认新密码"/>
		    </div>
		  </div>
		</div>
	</div>
	<a class="twtj_btn" id="js-submit" href="javascript:;">确认</a>
</form>

<script type="text/javascript">
	$('#js-submit').click(function() {
		$('form').trigger('submit');
	});

	$('form').submit(function() {
		var $$ = $(this);

		$.check(!this.suser_password_old.value, '输入原始密码') &&
		$.check(!this.suser_password.value, '输入新密码') &&
		$.check(!this.suser_password_r.value, '确认新密码') &&
		$.check(this.suser_password.value != this.suser_password_r.value, '两次密码不一样') &&
		$$.ajaxAuto();
		return false;
	});
</script>