<div id="js-qrcode">扫一扫</div>

<div id="text"></div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	wx.config(<?php echo $js->config(array('scanQRCode'), false) ?>);
	wx.ready(function() {
		$('#js-qrcode').click(function() {
			 {
				wx.scanQRCode({
				    needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
				    scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
				    success: function (res) {
				    	var result = res.resultStr; // 当needResult 为 1 时，扫码返回的结果

				    	$('#text').html(result);
					}
				});
			}
		});
	});
</script>