<div id="text" class="none">
	<span></span>
	<img src="">
	<button id="js-ship" data-href="">确认派送</button>
</div>

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	wx.config(<?php echo $js->config(array('scanQRCode'), false) ?>);
	wx.ready(function() {
		wx.scanQRCode({
		    needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
		    scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
		    success: function (res) {
		    	$(this).ajaxAuto({
		    		url: '<?php echo $this->url('shop-admin/self')?>',
		    		type: 'post',
		    		data: {key: res.resultStr},
		    		success: function (re) {
		    			if (re.status == 'ok') {
		    				$('#text span').html(re.data.product_name);
		    				$('#text img').attr({src: re.data.src});
		    				$('#js-ship').data('href', re.data.href);

		    				$('#text').fadeIn();
		    			}
		    		}
		    	});
			}
		});
	});

	//发货
	$('#js-ship').click(function() {
		var $$ = $(this);

		$.toast($$.data('href'));
		
		$$.ajaxAuto();
		return false;
	});
</script>