<div class="dialog">
	<div class="dialog_li item01">
		<h4></h4>
		<div class="hint_ma">
			<div class="img">
				<img src=""/>
			</div>
		</div>			
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">取消</div>
		  <div class="weui-flex__item dl_btn fxbtn" id="js-ship" data-href="">确认派送</div>
		</div>
	</div>
	<div class="dialog_li item02">
		<h4>系统提示</h4>
		<div class="hint_ma">
			<p>您已经领取过该商品无法派送</p>
		</div>
		<div class="weui-flex">
		  <div class="weui-flex__item dl_btn cancel">确认</div>
		</div>
	</div>
</div>

<div class="mask"></div>	

<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">
	wx.config(<?php echo $js->config(array('scanQRCode'), false) ?>);
	wx.ready(function() {
		wx.scanQRCode({
		    needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
		    scanType: ["qrCode","barCode"], // 可以指定扫二维码还是一维码，默认二者都有
		    success: function (res) {
		    	$(this).ajaxAuto({
		    		url: '<?php echo $this->url('shop-admin/self')?>',
		    		type: 'post',
		    		data: {key: res.resultStr},
		    		success: function (re) {
		    			if (re.status == 'ok') {
		    				$('.item01 .img img').attr({src: re.data.src});
		    				$('.item01 h4').html(re.data.name);
		    				$('#js-ship').data('href', re.data.href);

		    				$(".item01").show().siblings().hide();
		    				$(".dialog").fadeIn();
		    				$(".mask").fadeIn();
		    			} else {
		    				$('.item02 .hint_ma p').html(re.data.msg);
		    				$(".item02").show().siblings().hide();
		    				$(".dialog").fadeIn();
		    				$(".mask").fadeIn();
		    				return false;
		    			}
		    		}
		    	});
			}
		});
	});

	$('.cancel').click(function() {
		self.location = document.referrer;
	});

	//发货
	$('#js-ship').click(function() {
		var $$ = $(this);

		$$.ajaxAuto();
		return false;
	});

	// $(function () {
	//     if (window.history && window.history.pushState) {
	//         $(window).on('popstate', function () {
	//             console.log('123');
	//         });
	//         window.history.pushState('forward', null, '<?php //echo $this->url('shop-admin/index')?>');
	//     }
	// });
</script>