<div class="bread">
    <strong>
        <a href="<?php echo $this->url('order/list')?>">订单</a> / 列表
    </strong>
</div>

<div class="table-responsive">
    <table class="table" id="data-list">
        <thead>
            <tr>
                <th class="text-center">商品名称</th>
                <th class="text-center">组团成员</th>
                <th class="text-center">组团时间</th>
                <th class="text-center">组团状态</th>
                <?php if ($this->perm->has(PERM_DELETE)) : ?>
                    <th class="text-center">操作</th>
                <?php endif;?>
            </tr>
        </thead>
        <tbody>
            <?php if ($groupList) : ?>
                <?php foreach ($groupList as $key => $row) :?>
                    <tr class="<?php if (($key + 1) % 2 == 1) : ?>odd-narmal<?php endif;?>">
                        <td class="text-center"><?= $row['product_name']?></td>
                        <td class="text-center">
                            <?php $i = 0;?>
                            <?php foreach($row['customer_id'] as $ke => $value) : ?>
                                <span><?php echo $i ? '成员' : '团长'?>：</span><?php echo $value?>
                                <?php $i++;?>
                            <?php endforeach;?>
                        </td>
                        <td class="text-center"><?= $row['group_time']?></td>
                        <td class="text-center"><?php echo $row['group_type']['msg']?></td>
                        <?php if ($this->perm->has(PERM_DELETE)) : ?>
                            <td class="text-center action">
                                <span class="btn btn-xs del" data-href="<?= $this->url('order/group-del', array('id' => $row['group_id']))?>" title="删除">
                                    <i class="fa fa-trash"></i>
                                </span>
                            </td>
                        <?php endif;?>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>

<div id="paginator" class="row">
    <?= $this->render("includes/paginator"); ?>
</div>

<?php echo $this->js('jquery.autocomplete.js')->wrap();?>
<script>
    $('.action .del').click(function() {
        var $$ = $(this);

        $.confirm('请确认是否要删除？', function() {
            $$.ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.parents('tr').remove();
                    }
                }
            });
            return false;
        }, {
            title: '信息确认'
        });
    });
</script>