<div class="bread">
    <strong>
        <a href="<?php echo $this->url('task/read-list')?>">任务中心</a> / 会员奖品
    </strong>
</div>

<div id="search">
    <form>
        <div class="row">
            <div class="col-8">
                <div class="form-group">
                    <label>用户名</label>
                    <input class="form-control" type="text" name="customer_name" value="<?= $this->param('customer_name')?>">
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label class="hide"></label>
                    <div>
                        <button type="submit">搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="table-responsive">
    <table class="table" id="data-list">
        <thead>
            <tr>
                <th class="text-center">用户名</th>
                <th class="text-center">奖品名称</th>
                <th class="text-center">奖品类型</th>
                <th class="text-center">获奖时间</th>
                <th class="text-center">状态</th>
                <?php if ($this->perm->has(PERM_EDIT) || $this->perm->has(PERM_DELETE)) : ?>
                    <th class="text-center">操作</th>
                <?php endif;?>
            </tr>
        </thead>
        <tbody>
            <?php if ($prizeList) : ?>
                <?php foreach ($prizeList as $key => $row) :?>
                    <tr class="<?php if (($key + 1) % 2 == 1) : ?>odd-narmal<?php endif;?>">
                        <td class="text-center"><?= $row['customer_name']?></td>
                        <td class="text-center"><?= $row['turntablep_title']?></td>
                        <td class="text-center"><?= $filed['turntablep_attr'][$row['turntablep_attr']]?></td>
                        <td class="text-center"><?= $row['prize_time']?></td>
                        <td class="text-center"><?= $filed['prize_attr'][$row['prize_attr']]?></td>
                        <?php if ($this->perm->has(PERM_EDIT) || $this->perm->has(PERM_DELETE)) : ?>
                            <td class="text-center action">
                                <?php if ($this->perm->has(PERM_EDIT)) : ?>
                                    <a class="btn btn-xs edit" href="<?= $this->url('task/prize-detail', array('id' => $row['prize_id']))?>" title="详情">
                                        <i class="fa fa fa-eye"></i>
                                    </a>
                                <?php endif;?>
                                <?php if ($this->perm->has(PERM_DELETE)) : ?>
                                    <span class="btn btn-xs del" data-href="<?= $this->url('task/prize-del', array('id' => $row['prize_id']))?>" title="删除">
                                        <i class="fa fa-trash"></i>
                                    </span>
                                <?php endif;?>
                            </td>
                        <?php endif;?>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>

<div id="paginator" class="row">
    <?= $this->render("includes/paginator"); ?>
</div>

<script type="text/javascript">
    $('.action .del').click(function() {
        var $$ = $(this);

        $.confirm('请确认是否要删除？', function() {
            $$.ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.parents('tr').remove();
                    }
                }
            });
            return false;
        }, {
            title: '信息确认'
        });
    });
</script>