<div class="bread">
    <strong>
        <a href="<?php echo $this->url('task/question-list')?>">答题任务列表</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<form method="post" enctype="multipart/form-data">
    <div class="widget-header">
        <h2 class="title-theme-2">问卷</h2>
    </div>
    <div>
        <div class="row">
            <div class="form-group col-24">
                <label>缩略图<sup>*</sup></label>
                <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF ) 140 * 140</p>
                <div style="display: <?php echo !isset($info['task_banner']) ? 'none' : ''?>; text-align: center;">
                    <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 200px;" src="<?php echo isset($info['task_banner']) && $info['task_banner'] ? $this->uploadUrl($info['task_banner'], 'sys') : ''?>">
                </div>
                
                <input class="form-control" type="file" name="file" value="">
            </div>
        </div>
        <div class="row">
            <div class="form-group col-24">
                <label>问题描述<sup>*</sup></label>
                <script type="text/plain" id="myEditor" style="width:100%;height:100%;" name="task_desc">
                    <?= isset($info['task_desc']) ? $info['task_desc'] : '';?>
                </script>
            </div>
        </div>
        <div class="row">
            <div class="form-group col-12">
                <label>标题<sup>*</sup></label>
                <input class="form-control" type="text" name="task_title" value="<?= isset($info['task_title']) ? $info['task_title'] : '';?>" placeholder="">
            </div>
            <div class="form-group col-12">
                <label>奖励积分<sup>*</sup></label>
                <input class="form-control" type="number" name="task_score" value="<?= isset($info['task_score']) ? $info['task_score'] : '';?>">
            </div>
            <div class="form-group col-12">
                <label>状态<sup>*</sup></label>
                <select class="form-control" name="task_status">
                    <option value="1" <?= (isset($info['task_status']) && $info['task_status'] == 1) ? 'selected' : '' ?>>上线</option>
                    <option value="0" <?= (isset($info['task_status']) && $info['task_status'] == 0) ? 'selected' : '' ?>>下线</option>
                </select>
            </div>
        </div>
    </div>

    <div class="widget-header">
        <h2 class="title-theme-2">题库</h2>
        <button type="button" id="jq-contract-add"><i class="fa fa-plus"></i> 添加</button>
    </div>
    <div id="jq-contract-box">
        <?php if (isset($info['data'])) : ?>
            <?php foreach($info['data'] as $row) : ?>
                <div class="row jq-item">
                    <div class="col-12">
                        <div class="form-group">
                            <label>问题<sup>*</sup></label>
                            <input class="form-control" type="text" name="question_title[]" value="<?= $row['question_title'];?>" placeholder="你的性别是？">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项A<sup>*</sup></label>
                            <input class="form-control" type="text" name="question_a[]" value="<?= $row['question_a'];?>">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项B<sup>*</sup></label>
                            <input class="form-control" type="text" name="question_b[]" value="<?= $row['question_b'];?>">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项C</label>
                            <input class="form-control" type="text" name="question_c[]" value="<?= $row['question_c'];?>">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项D</label>
                            <input class="form-control" type="text" name="question_d[]" value="<?= $row['question_d'];?>">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项E</label>
                            <input class="form-control" type="text" name="question_e[]" value="<?= $row['question_e'];?>">
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label>选项F</label>
                            <input class="form-control" type="text" name="question_f[]" value="<?= $row['question_f'];?>">
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>正确答案<sup>*</sup></label>
                            <div class="form-control">
                                <span class="radio-check border-right"><input class="radio" type="checkbox" value="a" <?= in_array('a', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> A</span>
                                <span class="radio-check border-right"><input class="radio" type="checkbox" value="b" <?= in_array('b', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> B</span>
                                <span class="radio-check border-right"><input class="radio" type="checkbox" value="c" <?= in_array('c', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> C</span>
                                <span class="radio-check border-right"><input class="radio" type="checkbox" value="d" <?= in_array('d', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> D</span>
                                <span class="radio-check border-right"><input class="radio" type="checkbox" value="e" <?= in_array('e', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> E</span>
                                <span class="radio-check"><input class="radio" type="checkbox" value="f" <?= in_array('f', explode(",", $row['question_answer'])) ? 'checked' : '' ?>/> F</span>
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="form-group">
                            <label>问题类型<sup>*</sup></label>
                            <select class="form-control" name="question_type[]">
                                <option value="1" <?php echo $this->param('question_type') === '1' ? 'selected' : ''?>>单选</option>
                                <option value="2" <?php echo $this->param('question_type') === '2' ? 'selected' : ''?>>多选</option>
                            </select>
                        </div>
                    </div>
                    <input type="hidden" name="question_answer[]" value="<?php echo $row['question_answer']?>">
                    <input type="hidden" name="question_id[]" value="<?php echo $row['question_id']?>">
                    <div class="col-12">
                        <div class="form-group">
                            <label>操作 </label>
                            <div>
                                <button type="button" class="js-button"><i class="fa fa-times"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
            <?php endforeach;?>
        <?php endif;?>
    </div>

    <div class="employee-detail-submit">
        <button type="submit" id="jq-submit" class="btn">保存</button>
        <a href="javascript:history.back();" class="btn">返回 »</a>
    </div>
</form>

<div id="jq-contract-template" class="none">
    <div class="row jq-item">
        <div class="col-12">
            <div class="form-group">
                <label>问题<sup>*</sup></label>
                <input class="form-control" type="text" name="question_title[]" value="" placeholder="你的性别是？">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项A<sup>*</sup></label>
                <input class="form-control" type="text" name="question_a[]" value="">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项B<sup>*</sup></label>
                <input class="form-control" type="text" name="question_b[]" value="">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项C</label>
                <input class="form-control" type="text" name="question_c[]" value="">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项D</label>
                <input class="form-control" type="text" name="question_d[]" value="">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项E</label>
                <input class="form-control" type="text" name="question_e[]" value="">
            </div>
        </div>
        <div class="col-6">
            <div class="form-group">
                <label>选项F</label>
                <input class="form-control" type="text" name="question_f[]" value="">
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label>正确答案<sup>*</sup></label>
                <div class="form-control">
                    <span class="radio-check border-right"><input class="radio" type="checkbox" value="a"/> A</span>
                    <span class="radio-check border-right"><input class="radio" type="checkbox" value="b"/> B</span>
                    <span class="radio-check border-right"><input class="radio" type="checkbox" value="c"/> C</span>
                    <span class="radio-check border-right"><input class="radio" type="checkbox" value="d"/> D</span>
                    <span class="radio-check border-right"><input class="radio" type="checkbox" value="e"/> E</span>
                    <span class="radio-check"><input class="radio" type="checkbox" value="f"/> F</span>
                </div>
            </div>
        </div>
        <div class="col-12">
            <div class="form-group">
                <label>问题类型<sup>*</sup></label>
                <select class="form-control" name="question_type[]">
                    <option value="1">单选</option>
                    <option value="2">多选</option>
                </select>
            </div>
        </div>
        <input type="hidden" name="question_answer[]" value="">
        <input type="hidden" name="question_id[]" value="">
        <div class="col-12">
            <div class="form-group">
                <label>操作 </label>
                <div>
                    <button type="button" class="js-button"><i class="fa fa-times"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    //实例化编辑器
    UM.getEditor('myEditor');
    
    $("#jq-contract-add").on('click', function() {
        $("#jq-contract-box").append($("#jq-contract-template").clone().html());
        datepicker();
        removeAction();
    });

    var removeAction = function() {
        $("#jq-contract-box").find(".js-button").on('click', function() {
            var row = $(this).parents('.row');
            var id = row.find('input[name="question_id[]"]').val();

            if (id) {
                $(this).ajaxAuto({
                    url: '<?php echo $this->url('task/question-del')?>',
                    data: {id: id},
                    success: function (re) {
                        if (re.status == 'ok') {
                            row.remove();
                        }
                    }
                });
            } else {
                row.remove();
            }
        });
    };

    removeAction();

    $("form").submit(function() {
        var $$ = $(this);
        $$.find('.jq-item').each(function() {
            var question_answer = '';
            $(this).find('input[type="checkbox"]').each(function() {
                if ($(this).is(':checked')) {
                    if (question_answer) {
                        question_answer += ',' + $(this).val();
                    } else {
                        question_answer += $(this).val();
                    }  
                }
            });

            $(this).find('input[name="question_answer[]"]').val(question_answer);
        });

        $.check(!this.task_title.value, '请输入标题', this.task_title) &&
        $.check(!this.task_desc.value, '请输入问题描述', this.task_desc) &&
        $.check(!this.task_score.value, '请输入答题奖励积分', this.task_score) &&
        $(this).ajaxAuto();
        return false;
    });

    $("input:file").unbind('change').on('change', function() {
        var imageHolder = $(this).parents('.form-group').find('.js-image');
        if (typeof (FileReader) != "undefined") {
            var reader = new FileReader();
            reader.onload = function (e) {
               var result = e.target.result;
               imageHolder.attr('src', result);
           }
           var upFile = $(this)[0].files[0];
           reader.readAsDataURL(upFile);

           imageHolder.parent().show();
        }
    });
</script>


