<div class="bread">
    <strong>
        <a href="<?php echo $this->url('task/turntable-list')?>">转盘列表</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="form-group col-12">
            <label>奖品名称<sup>*</sup></label>
            <input class="form-control" type="text" name="turntablep_title" value="<?= isset($info['turntablep_title']) ? $info['turntablep_title'] : '';?>">
        </div>
        <div class="form-group col-12">
            <label>奖品类型<sup>*</sup></label>
            <select class="form-control" name="turntablep_attr">
                <option value="">选择类型</option>
                <?php foreach($filed['turntablep_attr'] as $key => $value) : ?>
                    <option value="<?php echo $key?>" <?php echo isset($info['turntablep_attr']) && $info['turntablep_attr'] == $key ? 'selected' : ''?>>
                        <?php echo $value?>
                    </option>
                <?php endforeach;?>
            </select>
        </div>
        <div class="form-group col-12 <?php echo isset($info['turntablep_attr']) && $info['turntablep_attr'] == 'score' ? '' : 'none'?>" id="js-score">
            <label>积分数量<sup>*</sup></label>
            <input class="form-control" type="number" name="turntablep_score" value="<?= isset($info['turntablep_score']) ? $info['turntablep_score'] : '';?>">
        </div>
    </div>
    <div class="row <?php echo isset($info['turntablep_attr']) && $info['turntablep_attr'] == 'product' ? '' : 'none'?>" id="js-product">
        <div class="form-group col-24">
            <label>缩略图<sup>*</sup></label>
            <p class="format-tip">( 图片类型: JPG, JPEG, PNG, GIF )</p>
            <div style="display: <?php echo !isset($info['turntablep_image']) ? 'none' : ''?>; text-align: center;">
                <img class="js-image" style="border: 1px solid #ddd; padding: 2px; width: 400px;" src="<?php echo isset($info['turntablep_image']) && $info['turntablep_image'] ? $this->uploadUrl($info['turntablep_image'], 'sys') : ''?>">
            </div>
            
            <input class="form-control" type="file" name="file" value="">
        </div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <label>概率%<sup>*</sup></label>
            <input class="form-control" type="number" name="turntablep_probability" value="<?= isset($info['turntablep_probability']) ? $info['turntablep_probability'] : '';?>">
        </div>
        <div class="form-group col-12">
            <label>排序</label>
            <input class="form-control" type="number" name="turntablep_sort" value="<?= isset($info['turntablep_sort']) ? $info['turntablep_sort'] : '';?>">
        </div>
        <div class="form-group col-12">
            <label>状态<sup>*</sup></label>
            <select class="form-control" name="turntablep_status">
                <option value="1" <?= (isset($info['turntablep_status']) && $info['turntablep_status'] == 1) ? 'selected' : '' ?>>上线</option>
                <option value="0" <?= (isset($info['turntablep_status']) && $info['turntablep_status'] == 0) ? 'selected' : '' ?>>下线</option>
            </select>
        </div>
    </div>
    <div class="row">
        <div class="form-group col-12">
            <button type="submit">提交</button>
            <a href="javascript:history.back();" class="btn">返回 »</a>
        </div>
    </div>
</form>

<script type="text/javascript">
    $('select[name="turntablep_attr"]').change(function() {
        if ($(this).val() == 'product') {
            $('#js-product').removeClass('none');
        } else {
            $('#js-product').addClass('none');
        }
        if ($(this).val() == 'score') {
            $('#js-score').removeClass('none');
        } else {
            $('#js-score').addClass('none');
        }
    });

    $("form").submit(function() {
        $.check(!this.turntablep_title.value, '请输入奖品名称', this.turntablep_title) &&
        $.check(!this.turntablep_attr.value, '请输入奖品类型', this.turntablep_attr) &&
        $.check(!this.turntablep_probability.value, '请输入概率', this.turntablep_probability) &&
        $(this).ajaxAuto();
        return false;
    });

    $("input:file").unbind('change').on('change', function() {
        var imageHolder = $(this).parents('.form-group').find('.js-image');
        if (typeof (FileReader) != "undefined") {
            var reader = new FileReader();
            reader.onload = function (e) {
               var result = e.target.result;
               imageHolder.attr('src', result);
           }
           var upFile = $(this)[0].files[0];
           reader.readAsDataURL(upFile);

           imageHolder.parent().show();
        }
    });
</script>


