<form method="post">
    <div class="widget-header">
        <h2 class="title-theme-2">每日次数</h2>
    </div>
    <div>
        <?php if ($scoreLeave) : ?>
            <div class="row">
                <?php foreach($scoreLeave as $key => $value) : ?>
                    <div class="form-group col-12">
                        <label><?php echo $value?><sup>*</sup></label>
                        <input class="form-control" type="num" name="turntable_num[<?php echo $key?>]" value="<?= isset($config['turntable_num'][$key]) ? $config['turntable_num'][$key] : '';?>">
                    </div>
                <?php endforeach;?>
            </div>
        <?php endif;?>
    </div>

    <div class="widget-header">
        <h2 class="title-theme-2">兑换一次</h2>
    </div>
    <div>
        <div class="row">
            <div class="form-group col-12">
                <label>消耗积分<sup>*</sup></label>
                <input class="form-control" type="number" name="turntable_use_score" value="<?= isset($config['turntable_use_score']) ? $config['turntable_use_score'] : '';?>">
            </div>
        </div>
        <input type="hidden" name="turntable_id" value="<?= isset($config['turntable_id']) ? $config['turntable_id'] : '';?>">
    </div>

    <div class="employee-detail-submit">
        <button type="submit" id="jq-submit" class="btn">保存</button>
    </div>
</form>
<div class="widget-header">
    <h2 class="title-theme-2">转盘奖品</h2>
    <div style="text-align: right;">
        <a href="<?php echo $this->url('task/turntable-edit')?>">
            <button type="button"><i class="fa fa-plus"></i> 添加</button>
        </a>
    </div>
</div>

<div class="table-responsive" style="margin-top: 10px;">
    <table class="table">
        <thead>
            <tr>
                <th class="text-center">奖品名称</th>
                <th class="text-center">类型</th>
                <th class="text-center">内容</th>
                <th class="text-center">概率</th>
                <th class="text-center">排序</th>
                <th class="text-center">状态</th>
                <th class="text-center">操作</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($list) : ?>
                <?php foreach ($list as $key => $row) :?>
                    <tr class="<?php if (($key + 1) % 2 == 0) : ?>odd<?php endif;?>">
                        <td class="text-center"><?= $row['turntablep_title']?></td>
                        <td class="text-center"><?= $filed['turntablep_attr'][$row['turntablep_attr']]?></td>
                        <td class="text-center">
                            <?php if ($row['turntablep_attr'] == 'product') : ?>
                            <img src="<?php echo $this->uploadUrl($row['turntablep_image'], 'sys')?>" style="border: 1px solid #ddd; padding: 2px; width: 200px;">
                            <?php elseif ($row['turntablep_attr'] == 'score') : ?>
                                <?php echo sprintf("%d积分", $row['turntablep_score'])?>
                            <?php else : ?>
                            <?php endif;?>
                        </td>
                        <td class="text-center"><?= sprintf("%d%%", $row['turntablep_probability'])?></td>
                        <td class="text-center"><?= $row['turntablep_sort']?></td>
                        <td class="text-center"><?= $row['turntablep_status'] ? '上线' : '下线'?></td>
                        <td class="text-center action">
                            <a class="btn btn-xs edit" href="<?= $this->url('task/turntable-edit', array('id' => $row['turntablep_id']))?>" title="编辑">
                                <i class="fa fa-edit"></i>
                            </a>
                            <span class="btn btn-xs del" data-href="<?= $this->url('task/turntable-del', array('id' => $row['turntablep_id']))?>" title="删除">
                                <i class="fa fa-trash"></i>
                            </span>
                        </td>
                    </tr>
                <?php endforeach;?>
            <?php endif;?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    // submit
    $("form").submit(function() {
        $(this).ajaxAuto();
        return false;
    });

    $('.action .del').click(function() {
        var $$ = $(this);

        $.confirm('请确认是否要删除？', function() {
            $$.ajaxAuto({
                success: function (re) {
                    if (re.status == 'ok') {
                        $$.parents('tr').remove();
                    }
                }
            });
            return false;
        }, {
            title: '信息确认'
        });
    });
</script>
