<div class="bread">
    <strong>
        <a href="<?php echo $this->url('admin/member-list')?>">人员列表</a> / <?php echo $this->param('id') ? '编辑' : '添加'?>
    </strong>
</div>

<div class="row">
    <div class="col-12">
        <form method="post">
            <div class="form-group">
                <label>用户名<sup>*</sup></label>
                <input class="form-control" type="text" name="member_name" value="<?= isset($memberInfo['member_name']) ? $memberInfo['member_name'] : '';?>" <?php echo $this->param('id') ? 'disabled' : ''?> >
            </div>
            <div class="form-group">
                <label>密码<sup>*</sup></label>
                <input class="form-control" type="password" name="member_password" value="<?= isset($memberInfo['member_password']) ? $memberInfo['member_password'] : '';?>" <?php echo $this->param('id') ? 'disabled' : ''?>>
            </div>
            <div class="form-group">
                <label>权限<sup>*</sup></label>
                <select class="form-control" name="member_perms[]" multiple="" style="height: 100px;">
                    <option value="">选择</option>
                    <?php foreach($perms as $key => $value) : ?>
                        <option value="<?php echo $key?>" <?php echo isset($memberInfo['member_perms']) && in_array($key, explode(",", $memberInfo['member_perms'])) ? 'selected' : ''?>><?php echo $value?></option>
                    <?php endforeach;?>
                </select>
            </div>
            <div class="form-group">
                <label>用户状态<sup>*</sup></label>
                <select class="form-control" name="member_status">
                    <option value="1" <?= (isset($memberInfo['member_status']) && $memberInfo['member_status'] == 1) ? 'selected' : '' ?>>有效</option>
                    <option value="0" <?= (isset($memberInfo['member_status']) && $memberInfo['member_status'] == 0) ? 'selected' : '' ?>>禁用</option>
                </select>
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $("form").submit(function() {
        $.check(!this.member_name.value, '请输入用户名', this.member_name) &&
        $.check(!this.member_password.value, '请输入密码', this.member_password) &&
        $(this).ajaxAuto();
        return false;
    });
</script>


