<div class="bread">
    <strong>
        <a href="<?php echo $this->url('admin/member-list')?>">后台管理</a> / 修改密码
    </strong>
</div>

<div class="row">
    <div class="col-12">
        <form method="post">
            <div class="form-group">
                <label>用户名<sup>*</sup></label>
                <input class="form-control" type="text" name="member_name" value="">
            </div>
            <div class="form-group">
                <label>新密码<sup>*</sup></label>
                <input class="form-control" type="password" name="member_password" value="">
            </div>
            <div class="form-group">
                <label>确认新密码<sup>*</sup></label>
                <input class="form-control" type="password" name="r_member_password" value="">
            </div>
            <div>
                <button type="submit">提交</button>
                <a href="javascript:history.back();" class="btn">返回 »</a>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $("form").submit(function(){
        var $$ = $(this);

        $.check(!this.member_name.value, '请输入用户名', this.member_name) &&
        $.check(!this.member_password.value, '请输入新密码', this.member_password) &&
        $.check(this.r_member_password.value != this.member_password.value, '两次密码不一样', this.r_member_password) &&
        $.confirm('确认要修改密码？', function() {
            $$.ajaxAuto();
            return false;
        }, {
            title: '信息确认'
        });

        return false;
    });
</script>


