<div class="order_top clearfix">
    <?php if (isset($info['images']['banner'][0]['image_path'])) : ?>
        <div class="img fl">
            <img src="<?php echo $this->uploadUrl($info['images']['banner'][0]['image_path'], 'product')?>">
        </div>
    <?php endif;?>
    <h4><?php echo $info['product_name']?></h4>
</div>
<!-- 取货方式选择 -->
<div class="weui-cells order_qh">
        <a class="weui-cell weui-cell_access open-popup" href="javascript:;" data-target="<?php echo $info['product_shaping_status'] ? '#half' : ''?>">
                <div class="weui-cell__bd">
                        <p>选择收货方式</p>
                </div>
                <div class="weui-cell__ft qh_ch">自取</div>
        </a>

        <a class="weui-cell weui-cell_access" href="<?php echo $this->url('customer/address', array('redirect' => $this->selfUrl()))?>" id="js-address" style="display: none;">
                <div class="weui-cell__bd">
                        <p>收货地址</p>
                </div>
                <div class="weui-cell__ft"><?php echo $addressInfo ? '' : '填写'?></div>
        </a>
        <?php if ($addressInfo) : ?>
                <!-- 选择收货地址-s -->
                <div class="addr_choose wrap" id="js-address-detail" style="display: none;">
                    <h4><?php echo $addressInfo['user_name']?><span><?php echo $addressInfo['user_tel']?></span></h4>
                    <p><i class="iconfont">&#xe636;</i><?php echo $addressInfo['user_address']?></p>
                </div>  
                <!-- 选择收货地址-e -->
        <?php endif;?>

        <div class="weui-cell">
                <div class="weui-cell__bd">
                        <p>商品总额</p>
                </div>
                <div class="weui-cell__ft"><?php echo $this->funcs->showValue($info['product_price'])?>积分</div>
        </div>
</div>

<!-- 取货方式弹出 -->
<div id="half" class='weui-popup__container popup-bottom'>
    <div class="weui-popup__overlay"></div>
    <div class="weui-popup__modal qh_modal">
        
        <div class="modal-content">
            <div class="weui-grids">
                <a href="javascript:;" class="weui-grid qh_xz js_grid close-popup" data-id="dialog">
                    <div class="weui-cells">
                    <div class="weui-cell">
                        <div><i class="weui-icon-success"></i></div>
                        <div class="weui-cell__bd">
                            <p data-type="self">自提</p>
                        </div>
                        <div class="weui-cell__ft">通过取货码到取货点领取</div>
                    </div>
                </div>
                </a>

                <a href="javascript:;" class="weui-grid qh_xz js_grid close-popup" data-id="dialog">
                    <div class="weui-cells">
                        <div class="weui-cell">
                            <div><i class="weui-icon-circle"></i></div>
                            <div class="weui-cell__bd">
                                <p data-type="logistics">配送</p>
                            </div>
                            <div class="weui-cell__ft">平台7个工作日内配送</div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

 <!-- footer -->
<div class="pf pro_foot yes_foot clearfix">
    <a href="javascript:void(0);" class="sc fl">
            <span><i class="orange">合计：</i><?php echo $this->funcs->showValue($info['product_price'])?>积分</span>
    </a>
    <a href="<?php echo $this->url('order/create', array('id' => $info['product_id']))?>" id="js-submit" class="fr lq" data-type="self">确定</a>
</div>

<script type="text/javascript">
    // 选择取货方式弹出
    $('.qh_xz').on('click',function(event) {
            $(this).find('i').removeClass('weui-icon-circle');
            $(this).find('i').addClass('weui-icon-success');
            $(this).siblings('.qh_xz').find('i').addClass('weui-icon-circle');
            $(this).siblings('.qh_xz').find('i').removeClass('weui-icon-success');
            
            var qhl=$(this).find('p').text();
            var type = $(this).find('p').data('type');
            
            if (type == 'logistics') { //配送
                    $('#js-address, #js-address-detail').fadeIn();
            } else { //自提
                    $('#js-address, #js-address-detail').fadeOut();
            }

            $('#js-submit').data('type', type);
            $("#half").children('.weui-cell__ft').text(qhl)
            $(".order_qh").find('.qh_ch').html(qhl);
    });

    <?php if ($this->param('address')) : ?>
        $('.qh_xz p[data-type="logistics"]').parents('.qh_xz').trigger('click');
    <?php endif;?>

    var groupId = '<?php echo $this->param('group_id')?>';
    var addressId = '<?php echo $this->param('address_id')?>';
    $('#js-submit').click(function() {
        var $$ = $(this);
        var type = $$.data('type');
        
        var href = '<?php echo $this->url('order/create', array('id' => $info['product_id']))?>';

        if (type != 'self') {
                if (!$('#js-address-detail').length) {
                        window.location.href =  $('#js-address').attr('href');
                } 
        }

        $$.removeAttr('href');

        $$.ajaxAuto({
            url: href + '&type=' + type + '&group_id=' + groupId + '&address_id=' + addressId
        });
        
        return false;
    });
</script>