<!-- 导航切换 -->
<div class="swiper-container z999 pf m_nav">
	<div class="swiper-wrapper">
		<div class="swiper-slide <?php echo $this->param('attr') ? '' : 'on'?>"><a href="/">首页</a></div>
		<?php if ($attrList) : ?>
			<?php foreach($attrList as $key => $value) : ?>
				<div class="swiper-slide <?php echo $this->param('attr') == $key ? 'on' : ''?>"><a href="<?php echo $this->url('product/list', array('attr' => $key))?>"><?php echo $value?></a></div>
			<?php endforeach;?>
		<?php endif;?>
	</div>
</div>