 <!-- 导航切换 -->
<div class="swiper-container z999 pf m_order_nav">
    <div class="swiper-wrapper">
        <div class="swiper-slide <?php echo !$this->param('status') ? 'on' : ''?>"><a href="<?php echo $this->url('order/index')?>">全部</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'picke' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'picke'))?>">待领取</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'group' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'group'))?>">组团中</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'review' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'review'))?>">待评价</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'over' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'over'))?>">已完成</a></div>
    </div>
</div>

<div class="my_collect my_order" id="m_pro">
    <?php echo $this->render('order/row', array('orderList' => $orderList))?>
</div>

<div class="mask"></div>

<div class="weui-loadmore none">
    <i class="weui-loading"></i>
    <span class="weui-loadmore__tips">正在加载</span>
</div>

<script type="text/javascript">
    var swiper6 = new Swiper('.m_order_nav', {
        pagination: '.swiper-pagination',
        slidesPerView: 5,
        paginationClickable: true,
    });

    init();

    var pageSize = 1;
    var loading = false;  //状态标记
    $(document.body).infinite().on("infinite", function() {
        if (loading) {
            return false;
        } else {
            $('.weui-loadmore').fadeIn();
            loading = true;
        }
        
        $(this).ajaxAuto({
            data: {type: 'page', pageSize: pageSize},
            success: function (re) {
                var ali="";
                if (re.status == 'ok') {
                    pageSize++;

                    ali += re.data.list;
                }

                $("#m_pro").append(ali);

                init();
                
                $('.weui-loadmore').fadeOut();
                loading = false;
            }
        });
    });

    function init() {
        $('.js-receipt').click(function() {
            var $$ = $(this);

            $$.removeAttr('href');

            $$.ajaxAuto({
                data: {id: $$.data('id')}
            });

            return false;
        });
    }
</script>