 <!-- 导航切换 -->
<div class="swiper-container z999 pf m_order_nav">
    <div class="swiper-wrapper">
        <div class="swiper-slide <?php echo !$this->param('status') ? 'on' : ''?>"><a href="<?php echo $this->url('order/index')?>">全部</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'picke' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'picke'))?>">待领取</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'group' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'group'))?>">组团中</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'review' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'review'))?>">待评价</a></div>
        <div class="swiper-slide <?php echo $this->param('status') == 'over' ? 'on' : ''?>"><a href="<?php echo $this->url('order/index', array('status' => 'over'))?>">已完成</a></div>
    </div>
</div>

<div class="my_collect my_order">

    <?php foreach($orderList as $row) : ?>
        <div class="collect_li">
            <div class="weui-cells">
              <div class="weui-cell">
                <div class="weui-cell__bd">
                  <p>订单号：<?php echo $row['order_number']?></p>
                </div>
                <div class="weui-cell__ft orange"><?php echo $row['status']?></div>
              </div>
            </div>
            <div class="clearfix wrap inf pr">
              <div class="img fl">
                <img src="<?php echo $this->uploadUrl($row['product']['images']['banner'][0]['image_path'], 'product')?>">
              </div>
              <h4 class="lr2"><?php echo $row['product']['product_name']?></h4>
              <p><span class="gray"><?php echo $row['product']['product_weight']?></span></p>
              <div class="pa jif"><?php echo $this->funcs->showValue($row['product']['product_price'])?>积分</div>
              <div class="pa time"><?php echo date("Y-m-d", strtotime($row['order_time']))?></div>
            </div>
            
            <div class="ck_dt clearfix">
                <?php if ($row['order_type'] == 'pending') : ?>
                    <?php if ($row['shinging_type'] == 'self') : ?>
                        <a href="领取二维码.html" class="btn btn_01">领取码</a>
                        <a href="搜索取货点.html" class="btn btn_02">取货点</a>
                    <?php endif;?>
                <?php elseif ($row['order_type'] == 'shipped') : ?>
                    <a href="订单确认.html" class="btn btn_01">确认收货</a>
                <?php elseif ($row['order_type'] == 'group') : ?>
                    <a href="组团详情-失败.html" class="btn btn_01">组团详情</a>
                <?php elseif ($row['order_type'] == 'received') : ?>
                    <a href="添加评价.html" class="btn btn_01">去评价</a>
                <?php else : ?>
                    <a href="待评价订单详情.html" class="btn btn_01">查看详情</a>
                <?php endif;?>
            </div>
            
        </div>
    <?php endforeach;?>
</div>

<script>
    var swiper6 = new Swiper('.m_order_nav', {
        pagination: '.swiper-pagination',
        slidesPerView: 5,
        paginationClickable: true,
    });
</script>