<div class="lqewm">
	<div class="lqewm_m">
		<div class="lqewm_img">
			<div class="lqewm_mack"></div>
			<p id="js-title">领取码</p>
			<img src="<?php echo $this->url('common/qrcode', array('key' => $this->funcs->encrypt($key, 'E', QRCODE_KEY)))?>"/>
			<?php if ($time > 0) : ?>
				<p style="font-size: 12px; margin-bottom: 0px;">
					剩余时间：
					<label id="time" data-time="<?php echo $time?>">
					    <?php echo $this->funcs->showTime($time)?>
					</label>
				</p>
			<?php endif;?>
		</div>		
	</div>
</div>	

<script type="text/javascript">
	$(function(){
        $(".lqewm").height($(window).height());
        <?php if ($time <= 0) : ?>
            $("#js-title").html("已失效");
            $(".lqewm_mack").show();
        <?php endif;?>
	});

	setInterval(function () {
	    var $$ = $('#time');
	    var time = parseInt($$.data('time'));
	    if (time < 0) {
	            time = 0;

	            window.location.reload();
	            return false;
	    }

	    var init = {
	            'year': [31536000, '年'],
	            'month': [2592000, '月'],
	            'day': [86400, '天'],
	            'hour': [3600, '小时'],
	            'minute': [60, '分'],
	            'second': [1, '秒'],
	    };
	    var str = '';
	    for(key in init) {
	        num = Math.floor(time / init[key][0]);
	        if ($.inArray(key, ['year', 'month', 'day']) != -1) {
	            if (num) {
	                num = num.toString();
	                if (num.length == 1) {
	                    num = '0' + num;
	                }

	                str += num + init[key][1];
	                time -= num * init[key][0];
	            }
	        } else {
	            num = num.toString();
	            if (num.length == 1) {
	                num = '0' + num;
	            }

	            str += num + init[key][1];
	            time -= num * init[key][0];
	        }
	    }

	    if (!str) {
	        str = '00秒';
	    }

	    $$.data('time', parseInt($$.data('time')) - 1);
	    $$.html(str);
	}, 1000);
</script>