<div class="bread">
    <strong>
        <a href="<?php echo $this->url('review/list')?>">商品评价</a> / 列表
    </strong>
</div>

<div id="search">
    <form>
        <div class="row">
            <div class="col-8">
                <div class="form-group">
                    <label>商品名称</label>
                    <input class="form-control" type="text" name="product_name" value="<?= $this->param('product_name')?>">
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label>商品CODE</label>
                    <input class="form-control" type="text" name="product_code" value="<?= $this->param('product_code')?>">
                </div>
            </div>
            <div class="col-8">
                <div class="form-group">
                    <label class="hide"></label>
                    <div>
                        <button type="submit">搜索</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<div class="table-responsive">
    <table class="table" id="data-list">
        <thead>
            <tr>
                <th class="text-center">商品名称</th>
                <th class="text-center">商品CODE</th>
                <th class="text-center">商品类别</th>
                <th class="text-center">商品状态</th>
                <th class="text-center">评论总次数</th>
                <th class="text-center">平均得分</th>
                <th class="text-center">1星次数</th>
                <th class="text-center">2星次数</th>
                <th class="text-center">3星次数</th>
                <th class="text-center">4星次数</th>
                <th class="text-center">5星次数</th>
            </tr>
        </thead>
        <tbody>
            <?php if ($productList) : ?>
                <?php foreach ($productList as $key => $row) :?>
                    <tr class="<?php if (($key + 1) % 2 == 1) : ?>odd-narmal<?php endif;?>">
                        <td class="text-center"><?= $row['product_name']?></td>
                        <td class="text-center"><?= $row['product_code']?></td>
                        <td class="text-center"><?= $row['attr_name']?></td>
                        <td class="text-center"><?= $row['product_status'] ? '有效' : '禁用'?></td>
                        <td class="text-center">
                            <?php if($row['reviewCount']) : ?>
                                <a href="<?= $this->url('review/row', array('id' => $row['product_id']))?>">
                                    <?php echo $row['reviewCount']?>
                                </a>
                            <?php else : ?>
                                0
                            <?php endif;?>
                        </td>
                        <td class="text-center">
                            <span title="<?php echo sprintf("%.2f", $row['reviewAve']);?>">
                                <i class="stars <?php echo "star-" . str_replace('.', '-', $row['reviewAveStar']);?>"></i>
                            </span>
                        </td>
                        <td class="text-center"><?= $row['reviewCount1']?></td>
                        <td class="text-center"><?= $row['reviewCount2']?></td>
                        <td class="text-center"><?= $row['reviewCount3']?></td>
                        <td class="text-center"><?= $row['reviewCount4']?></td>
                        <td class="text-center"><?= $row['reviewCount5']?></td>
                    </tr>
                <?php endforeach;?>
            <?php endif?>
        </tbody>
    </table>
</div>

<div id="paginator" class="row">
    <?= $this->render("includes/paginator"); ?>
</div>